<?php
return [
    'id'    => 4,
    'title' => 'The Green Correspondence',
    'color' => '#3A6B4A',

    'pages' => [
        '1_start' => [
            'prose'   => 'VGhlIHNvbGljaXRvcidzIGxpc3QgaGFzIHR3ZWx2ZSBpdGVtczogZnVybml0dXJlLCBzaWx2ZXJ3YXJlLCB0aGUgY29udGVudHMgb2YgdGhlIHN0dWR5LCB0aGUgZ2FyZGVuIHRvb2xzLiBIZSBtZW50aW9uZWQgdGhlIGxldHRlcnMgYXMgYW4gYWZ0ZXJ0aG91Z2h0IOKAlCAidGhlcmUgbWF5IGJlIHNvbWUgcGVyc29uYWwgY29ycmVzcG9uZGVuY2UiIOKAlCBhbmQgdGhlbiBoYW5kZWQgeW91IHRoZSBrZXkuCgpUaGUga2V5IGlzIHRoZSBvbGQga2luZCwgaGVhdnkgaXJvbiwgdGhlIHNvcnQgdGhhdCBjb21lcyBmcm9tIGEgaG91c2UgdGhhdCBoYXMgb25seSBldmVyIGhhZCBvbmUgbG9jay4gVGhlIGhvdXNlIGlzIG9uIGEgbGFuZSBvZiBlbG1zIHRoYXQgaGF2ZSBiZWVuIGhlcmUgc2luY2UgYmVmb3JlIHRoZSB0b3duIHdhcyBpbmNvcnBvcmF0ZWQ6IHRhbGwsIHRoZWlyIHJvb3Qgc3lzdGVtcyBwcm9iYWJseSB1bmRlcm1pbmluZyB0aGUgZm9vdHBhdGhzLCBlbnRpcmVseSBpbmRpZmZlcmVudCB0byBtdW5pY2lwYWwgcGxhbm5pbmcuCgpJbnNpZGUsIHRoZSBhaXIgaXMgb2Ygcm9vbXMgdGhhdCBoYXZlIGJlZW4ga2VwdCwgbm90IGFiYW5kb25lZCDigJQgYmVlc3dheCBhbmQgb2xkIHBhcGVyIGFuZCBzb21ldGhpbmcgdW5kZXJuZWF0aCwgc29tZXRoaW5nIGZhbWlsaWFyIGluIHRoZSB3YXkgb2YgcGxhY2VzIHlvdSd2ZSBiZWVuIGJlZm9yZSB3aXRob3V0IGJlaW5nIGFibGUgdG8gc2F5IHdoZXJlLiBUaGUgZnJvbnQgaGFsbCBoYXMgYSB0ZWxlcGhvbmUgb24gYSBzaWRlIHRhYmxlLiBUaGUgY2FsZW5kYXIgaW4gdGhlIGtpdGNoZW4gaXMgb3BlbiB0byBPY3RvYmVyIGFuZCBzb21lb25lIGhhcyBkcmF3biBhIHNtYWxsIGFzdGVyaXNrIG9uIHRoZSBmb3VydGVlbnRoIGluIGdyZWVuIGluay4KCllvdSBkb24ndCBrbm93IHdobyBBdWRyZXkgaXMgeWV0LiBZb3Ugd2lsbC4=',
            'choices'  => [
                ['text' => 'RmluZCB0aGUgbGV0dGVycyBmaXJzdA==', 'next' => '2_letters'],
                ['text' => 'V2FsayB0aHJvdWdoIHRoZSByb29tcyBmaXJzdA==', 'next' => '2_rooms'],
            ],
        ],

        '2_letters' => [
            'prose'   => 'VGhlIHN0dWR5IGlzIG9mZiB0aGUgaGFsbCwgbGluZWQgd2l0aCBzaGVsdmVzIGJ1aWx0IGZvciB0aGUgYm9va3MgY3VycmVudGx5IG9uIHRoZW0uIE1vc3QgYXJlIHJlZmVyZW5jZSDigJQgbnVyc2luZyBlbmN5Y2xvcGFlZGlhcywgYSBkaWN0aW9uYXJ5IG9mIGJvdGFuaWNhbCB0ZXJtcywgdGhyZWUgdm9sdW1lcyBvZiBhbiBhdGxhcyB0aGF0IHN0b3BzIGF0IDE5ODcuIE9uIHRoZSBib3R0b20gc2hlbGYsIHN0YWNrZWQgaG9yaXpvbnRhbGx5LCB0YWtpbmcgdXAgdGhlIHdob2xlIHJ1bjogdGhyZWUgc2hvZWJveGVzIGxhYmVsbGVkIGluIGdyZWVuIGluay4gVGhlIHRvcCBvbmUgcmVhZHM6IEEsIDE5NjHigJMxOTcxLgoKT24gdGhlIGRlc2ssIGxhaWQgZmxhdDogYSBidW5kbGUgb2YgZW52ZWxvcGVzIHRpZWQgd2l0aCBraXRjaGVuIHR3aW5lLiBUaGUgdG9wIGVudmVsb3BlIGlzIHRoZSBtb3N0IHJlY2VudC4gRGlmZmVyZW50IGhhbmR3cml0aW5nIGZyb20gdGhlIG9uZXMgYmVsb3cg4oCUIHNoYWtpZXIsIHRoZSBncmVlbiBpbmsgZmFkZWQgdG8gc29tZXRoaW5nIGFsbW9zdCBncmV5LiBZb3UgdHVybiBpdCBvdmVyLiBVbnNlYWxlZC4KCkluc2lkZTogYSBzaW5nbGUgZm9sZGVkIHNoZWV0LiBEZWFyIEEgYXQgdGhlIHRvcCwgYW5kIHRoZW4gdGhlIGJlZ2lubmluZyBvZiBhIHNlbnRlbmNlIHRoYXQgc3RvcHMgbWlkLXdvcmQuCgpJIGhhdmUgYmVlbiB0aGlua2luZyBhYm91dCBob3cgdG8gc2F5IHRoaXMgZm9y4oCUCgpUaGUga25vY2sgYXQgdGhlIGJhY2sgZG9vciBpcyB0aHJlZSB0aW1lcywgdGhlIGtub2NrIG9mIHNvbWVvbmUgd2hvIGtub3dzIHRoZSBob3VzZS4=',
            'choices'  => [
                ['text' => 'QW5zd2VyIHRoZSBrbm9jaw==', 'next' => '3_fallon'],
            ],
        ],

        '2_rooms' => [
            'prose'   => 'WW91IGdvIHRocm91Z2ggdGhlIHJvb21zIGFzIHlvdSBnbyB0aHJvdWdoIHRoZSBiZWxvbmdpbmdzIG9mIHRoZSBkZWFkOiBtZXRob2RpY2FsbHksIHdpdGhvdXQgbG9va2luZyB0b28gY2xvc2VseS4KClRoZSBraXRjaGVuOiBhIGNhbGVuZGFyIHdpdGggZ3JlZW4gaW5rIGFzdGVyaXNrcyBvbiBkYXRlcyB0aHJvdWdoIHRoZSB5ZWFyLCB0aGVuIG5vdGhpbmcgYWZ0ZXIgT2N0b2Jlci4gQSBjZXJhbWljIGphciBsYWJlbGxlZCBDQVNURVIgU1VHQVIgdGhhdCBob2xkcywgd2hlbiB5b3UgbG9vaywgYnV0dG9ucy4gQSBzaW5nbGUgcGhvdG9ncmFwaCBvbiB0aGUgd2luZG93c2lsbCDigJQgdHdvIHdvbWVuIGluIGxhdGUgbWlkZGxlIGFnZSBzdGFuZGluZyBpbiBhIGdhcmRlbiwgdGhlIHRhbGxlciBvbmUgc3F1aW50aW5nIGF0IHRoZSBzdW4uIE9uIHRoZSBiYWNrLCBpbiBmYW1pbGlhciBncmVlbiBpbms6IE0gYW5kIEEsIEJhbGxhcmF0LCBDaHJpc3RtYXMgMTk5My4KClRoZSBiZWRyb29tOiBhIGNoYWlyIGF0IHRoZSB3aW5kb3csIHdvcm4gaW4gdGhlIHBhcnRpY3VsYXIgd2F5IG9mIGhhYml0dWFsIHVzZS4gQm9va3Mgb24gdGhlIG5pZ2h0c3RhbmQg4oCUIGEgbm92ZWwsIGEgbGlicmFyeSBib29rIHR3byB5ZWFycyBvdmVyZHVlLCBhbmQgdW5kZXJuZWF0aCBpdCBhIHNtYWxsIGxlYXRoZXIgam91cm5hbCB3aXRoIG5vIGxvY2suIFRoZSBmaXJzdCBwYWdlIGhhcyBhIHByZXNzZWQgZmxvd2VyIG9uIGl0LCBkcmllZCBmbGF0LCBzdGlsbCBncmVlbi4gTm8gd3JpdGluZy4KClRoZSBzdHVkeTogc2hlbHZlcywgcmVmZXJlbmNlIGJvb2tzLCB0aHJlZSBzaG9lYm94ZXMgbGFiZWxsZWQgaW4gZ3JlZW4sIGFuZCBvbiB0aGUgZGVzayBhIGJ1bmRsZSBvZiBlbnZlbG9wZXMgdGllZCB3aXRoIGtpdGNoZW4gdHdpbmUuCgpZb3UgY29tZSBiYWNrIHRvIHRoZSBidW5kbGUuIFNvbWUgdGhpbmdzIHB1bGwuCgpUaGUga25vY2sgYXQgdGhlIGJhY2sgZG9vciBpcyB0aHJlZSB0aW1lcy4=',
            'choices'  => [
                ['text' => 'QW5zd2VyIHRoZSBrbm9jaw==', 'next' => '3_fallon'],
            ],
        ],

        '3_fallon' => [
            'prose'   => 'U2hlIGlzIHNtYWxsLCBkaXJlY3QsIGFuZCBob2xkaW5nIGEgY292ZXJlZCBwbGF0ZSBvZiBzb21ldGhpbmcgdGhhdCBzbWVsbHMgb2YgbGVtb24uIFNoZSBoYXMgY2xlYXJseSBkZWNpZGVkIHdoYXQgc2hlJ3MgZ29pbmcgdG8gc2F5IGFuZCBpcyBnb2luZyB0byBzYXkgaXQuCgpIZXIgbmFtZSBpcyBLYXRobGVlbiBGYWxsb24uIFNoZSBoYXMga25vd24gTWFyZ2FyZXQgZm9yIHRoaXJ0eS1vbmUgeWVhcnMsIHNpbmNlIHRoZSBGYWxsb24gZmFtaWx5IG1vdmVkIG9udG8gdGhlIGxhbmUgaW4gMTk5Mi4gU2hlIGtub3dzIHdoYXQncyBpbiB0aGF0IGJ1bmRsZSwgb3IgdGhlIHNoYXBlIG9mIGl0LCBhbmQgc2hlIHdhbnRzIHRvIGtub3cgd2hhdCB5b3UncmUgcGxhbm5pbmcgdG8gZG8gd2l0aCBpdC4KCiJNYXJnYXJldCB3cm90ZSB0byBoZXIgc2lzdGVyIGZvciBmb3J0eSB5ZWFycywiIHNoZSBzYXlzLiAiR3JlZW4gaW5rLCBhbHdheXMg4oCUIGJvdGggb2YgdGhlbS4gSXQgd2FzIGEgam9rZSBiZXR3ZWVuIHRoZW0gYWJvdXQgc29tZXRoaW5nLiBNYXJnYXJldCBzYWlkIHNoZSdkIGZvcmdvdHRlbiB3aGF0LCBidXQgSSBkaWRuJ3QgYmVsaWV2ZSBoZXIuIFNoZSBoYWRuJ3QgZm9yZ290dGVuIGFueXRoaW5nLiIgQSBwYXVzZS4gIkF1ZHJleSBkaWVkIGluIE9jdG9iZXIuIE1hcmdhcmV0IG9ubHkgZm91bmQgb3V0IGluIEphbnVhcnksIHdoZW4gdGhlIHNvbGljaXRvciB0cmFja2VkIGhlciBkb3duLiBTaGUgZGlkbid0IGVhdCBwcm9wZXJseSBmb3IgdGhyZWUgd2Vla3MuIgoKU2hlIGV4dGVuZHMgdGhlIHBsYXRlLiBMZW1vbiBjYWtlLgoKIlRoZWlyIG1vdGhlcidzIG5hbWUgd2FzIEVsc2llLCIgc2hlIHNheXMuICJTaGUgZGllZCBpbiAxOTc4LiBJZiB5b3UgcmVhZCB0aGUgbGV0dGVycyBpbiBvcmRlciwgeW91J2xsIGhpdCBhIGdhcCB0aGF0IGxhc3RzIGVsZXZlbiB5ZWFycy4gVGhlIGxldHRlcnMgYmVmb3JlIGl0IGFyZSBkaWZmZXJlbnQgZnJvbSB0aGUgb25lcyBhZnRlci4iIFNoZSBwYXVzZXMuICJJIHRob3VnaHQgeW91IHNob3VsZCBrbm93IHRoYXQgYmVmb3JlIHlvdSBzdGFydGVkIGRlY2lkaW5nIHdoYXQgbWF0dGVycy4i',
            'choices'  => [
                ['text' => 'SW52aXRlIGhlciBpbg==', 'next' => '4_invite'],
                ['text' => 'VGhhbmsgaGVyLCB0YWtlIHRoZSBjYWtl', 'next' => '4_polite'],
            ],
        ],

        '4_invite' => [
            'prose'   => 'U2hlIGNvbWVzIGluIHRoZSB3YXkgb2Ygc29tZW9uZSB3aG8ga25vd3Mgd2hlcmUgdGhlIGtldHRsZSBpcywgd2hpY2ggdHVybnMgb3V0IHRvIGJlIGNvcnJlY3QuIFdoaWxlIGl0IGhlYXRzIHNoZSB0YWxrcy4KCk1hcmdhcmV0IGFuZCBBdWRyZXkgZ3JldyB1cCBvdXRzaWRlIEJlbmRpZ28uIFRoZWlyIGZhdGhlciBkaWVkIHdoZW4gdGhleSB3ZXJlIHlvdW5nIOKAlCBBdWRyZXkgd2FzIG5pbmUsIE1hcmdhcmV0IHR3ZWx2ZS4gVGhlaXIgbW90aGVyIEVsc2llIHJhbiBhIHNtYWxsIGJvYXJkaW5nIGhvdXNlIGFuZCB3b3JrZWQgYXMgYSBjb29rIGF0IHRoZSBzY2hvb2wuIFRoZSBzaXN0ZXJzIHdlcmUgY2xvc2UgaW4gdGhlIHdheSBjaGlsZHJlbiBiZWNvbWUgY2xvc2Ugd2hlbiB0aGUgaG91c2Vob2xkIGhhcyB0byBydW4uCgoiTWFyZ2FyZXQgdHJhaW5lZCBhcyBhIGJvb2trZWVwZXIuIEF1ZHJleSBiZWNhbWUgYSBudXJzZSDigJQgZGlzdHJpY3QgbnVyc2luZyBvdXQgaW4gdGhlIFdpbW1lcmEgZm9yIHllYXJzLCB0aGVuIEJhbGxhcmF0LiIgU2hlIGN1dHMgdHdvIHBpZWNlcyBvZiBjYWtlIHdpdGhvdXQgYXNraW5nLiAiVGhleSB3cm90ZSB0byBlYWNoIG90aGVyIGZyb20gdGhlIHRpbWUgQXVkcmV5IGxlZnQgZm9yIG51cnNpbmcgY29sbGVnZS4gRXZlcnkgd2VlayBzb21ldGltZXMsIGluIHRoZSBlYXJseSB5ZWFycy4iCgpTaGUgc2V0cyBhIGN1cCBpbiBmcm9udCBvZiB5b3UuCgoiVGhlcmUgd2VyZSBhbHNvIGVsZXZlbiB5ZWFycyB3aGVuIHRoZXkgZGlkbid0IHdyaXRlIGF0IGFsbC4gVGhhdCBlbmRlZCBpbiAxOTg5LiBJIGtuZXcgTWFyZ2FyZXQgZnJvbSAxOTkyLiBCeSB0aGVuIHNoZSBhbmQgQXVkcmV5IGhhZCBsdW5jaCB0d2ljZSBhIHllYXIgYW5kIHdyb3RlIGluIGJldHdlZW4uIFlvdSBjb3VsZCBzZWUgd2hhdCB0aGV5IHdlcmUgdG8gZWFjaCBvdGhlciwgZXZlbiB0aGVuIOKAlCBzb21ldGhpbmcgaGFkIGhhcHBlbmVkIGFuZCB0aGV5IGhhZCBkZWNpZGVkIHRvIGtlZXAgZ29pbmcgYW55d2F5LiIgU2hlIGxvb2tzIGF0IGhlciBjYWtlLiAiV2hhdCBoYXBwZW5lZCBpcyBpbiB0aGUgYnVuZGxlLiI=',
            'choices'  => [
                ['text' => 'UmVhZCB0aGUgbGV0dGVycw==', 'next' => '5_open'],
            ],
        ],

        '4_polite' => [
            'prose'   => 'U2hlIGFjY2VwdHMgdGhpcyB3aXRob3V0IG9mZmVuY2Ug4oCUIHNoZSB3YXMgcmVhZHkgZm9yIGl0LiBTaGUgaGFuZHMgeW91IHRoZSBjb3ZlcmVkIHBsYXRlIGFueXdheS4gTGVtb24gY2FrZSwgc3RpbGwgd2FybS4KCiJNYXJnYXJldCBhbmQgQXVkcmV5IGdyZXcgdXAgb3V0c2lkZSBCZW5kaWdvLCIgc2hlIHNheXMuICJBdWRyZXkgd2FzIHRoZSBudXJzZSwgTWFyZ2FyZXQgdGhlIGJvb2trZWVwZXIuIFRoZXkgd3JvdGUgdG8gZWFjaCBvdGhlciBmb3IgZm9ydHkgeWVhcnMuIFRoZXJlJ3MgYSBnYXAgb2YgZWxldmVuIHllYXJzIGluIHRoZSBtaWRkbGUuIiBTaGUgcGF1c2VzLiAiVGhlaXIgbW90aGVyIGRpZWQgaW4gMTk3OCwganVzdCBiZWZvcmUgdGhlIGdhcCBzdGFydHMuIEkgdGhvdWdodCB5b3Ugc2hvdWxkIGtub3cgdGhhdCBiZWZvcmUgeW91IHN0YXJ0ZWQgZGVjaWRpbmcgd2hhdCBtYXR0ZXJzLiIKClNoZSBkb2Vzbid0IGxvb2sgYmFjayBhcyBzaGUgZ29lcy4gSGVyIGZvb3RzdGVwcyBvbiB0aGUgcGF0aCBhcmUgdW5odXJyaWVkLgoKWW91IHN0YW5kIGluIHRoZSBkb29yd2F5IHdpdGggdGhlIGNha2UuIFRoZSBlbG0gaW4gdGhlIGZyb250IGdhcmRlbiBtb3ZlcyBzbGlnaHRseS4gSW5zaWRlLCBvbiB0aGUgZGVzaywgdGhlIGJ1bmRsZSB3YWl0cy4=',
            'choices'  => [
                ['text' => 'T3BlbiB0aGUgYnVuZGxl', 'next' => '5_open'],
            ],
        ],

        '5_open' => [
            'prose'   => 'VHdvIGh1bmRyZWQgYW5kIHNldmVudGVlbiBsZXR0ZXJzLiBZb3UgY291bnQgdGhlbSB3aXRob3V0IG1lYW5pbmcgdG8uCgpUaGUgdGhyZWUgc2hvZWJveGVzIGhvbGQgQXVkcmV5J3Mgc2lkZSDigJQgcmV0cmlldmVkIGFmdGVyIGhlciBkZWF0aCBhbmQgcmV0dXJuZWQgdG8gTWFyZ2FyZXQgd2l0aCBoZXIgZWZmZWN0cywgc3RvcmVkIGhlcmUgc29ydGVkIGJ5IGRlY2FkZS4gVGhlIGJ1bmRsZSBvbiB0aGUgZGVzayBpcyBNYXJnYXJldCdzIHNpZGUsIHdoYXQgc2hlIGtlcHQgb2YgaGVyIG93bi4gQm90aCBzaWRlcyBvZiBmb3J0eSB5ZWFycywgYm90aCBpbiBncmVlbiBpbmsuCgpUaGUgaGFuZHdyaXRpbmcgY2hhbmdlcyBvdmVyIHRpbWU6IGxvb3NlciBpbiB0aGUgbGF0ZSAxOTYwcywgY29udHJvbGxlZCBpbiB0aGUgd2F5IG9mIGRpZmZpY3VsdCBwZXJpb2RzIGluIHRoZSAxOTcwcywgYW5kIGFmdGVyIDE5ODkgc29tZXRoaW5nIGRpZmZlcmVudCDigJQgY2FyZWZ1bCBhdCBmaXJzdCwgbGlrZSB3b3JrLCBhbmQgbGF0ZXIgc29tZXRoaW5nIGVhc2llci4gU29tZXRoaW5nIHRoYXQgaGFzIGxlYXJuZWQgdG8gZ28gdGhlIGxvbmcgd2F5IHJvdW5kIGFuZCBoYXMgbWFkZSBwZWFjZSB3aXRoIGl0LgoKWW91IHNpdCBkb3duLg==',
            'choices'  => [
                ['text' => 'UmVhZCB0aGUgbGV0dGVycyBiZWZvcmUgdGhlIGdhcA==', 'next' => '6_before'],
                ['text' => 'UmVhZCB0aGUgZmlyc3QgbGV0dGVyIGFmdGVyIHRoZSBnYXA=', 'next' => '6_after'],
            ],
        ],

        '6_before' => [
            'prose'   => 'VGhlIGVhcmx5IGxldHRlcnMgYXJlIGZ1bGwuIFJlY2lwZXMgZXhjaGFuZ2VkIGFjcm9zcyB0aGUgZGlzdGFuY2UgYmV0d2VlbiBCZW5kaWdvIGFuZCB0aGUgV2ltbWVyYSwgdGhlbiBsYXRlciBiZXR3ZWVuIGhlcmUgYW5kIEJhbGxhcmF0LiBBcmd1bWVudHMgYWJvdXQgYSBwYXJ0aWN1bGFyIGNvdXNpbi4gT2JzZXJ2YXRpb25zIGFib3V0IHdlYXRoZXIgdGhhdCBhcmUgcmVhbGx5IGFib3V0IG90aGVyIHRoaW5ncy4gSW4gdGhlIGxhdGUgMTk2MHMgYm90aCBoYW5kd3JpdGluZ3MgZ2V0IGxvb3NlciwgbGFyZ2VyIOKAlCBzb21ldGhpbmcgZ29vZCB3YXMgaGFwcGVuaW5nIGZvciBib3RoIG9mIHRoZW0uIFRoZW4gdGhlIDE5NzBzOiBzbWFsbGVyLCB0aWdodGVyLCB0aGUgcGFydGljdWxhciBjb21wcmVzc2lvbiBvZiB3b21lbiB3aXRoIHRvbyBtdWNoIHRvIGRvLgoKVGhlbiB0aHJlZSBsZXR0ZXJzIGZyb20gMTk3NywgYWxsIEF1ZHJleSdzLiBUaGUgaGFuZHdyaXRpbmcgb2Ygc29tZW9uZSB0cmFpbmVkIHRvIG9ic2VydmUgYW5kIGRvY3VtZW50LgoKVGhlIGZpcnN0IGFza3Mgc3BlY2lmaWMgcXVlc3Rpb25zIGFib3V0IHRoZWlyIG1vdGhlcjogd2hpY2ggZG9jdG9yLCB3aGljaCBtZWRpY2F0aW9ucywgd2hldGhlciBNYXJnYXJldCBoYXMgc3Bva2VuIHRvIHRoZSBkaXN0cmljdCBudXJzZXMgd2hvIGNvbWUgb24gVGh1cnNkYXlzLiBUaGUgc2Vjb25kIGlzIHNob3J0ZXIgYW5kIGhhcyBiZWVuIG9wZW5lZCBhbmQgcmVmb2xkZWQgbWFueSB0aW1lcy4gTWFyZ2FyZXQsIEkgbmVlZCB5b3UgdG8gY2FsbCBtZSBiZWZvcmUgeW91IG1ha2UgYW55IGZ1cnRoZXIgZGVjaXNpb25zLiBJIG1lYW4gdGhpcy4KClRoZSB0aGlyZCBpcyB0d2VsdmUgcGFnZXMuCgpFbHNpZSBNYXJzaCB3YXMgbW92ZWQgdG8gYSBudXJzaW5nIGhvbWUgaW4gTWF5IG9mIDE5NzcuIFNoZSBkaWVkIHRoZXJlIGluIEp1bmUgb2YgMTk3OC4gQXVkcmV5IGhhZCBub3QgYmVlbiBjb25zdWx0ZWQgYWJvdXQgdGhlIG1vdmUuIFNoZSBmb3VuZCBvdXQgdGhyZWUgd2Vla3MgYWZ0ZXIgdGhlIGZhY3QuCgpUd2VsdmUgcGFnZXMgb2YgdmVyeSBjb250cm9sbGVkIGdyZWVuIGluay4gWW91IHJlYWQgYWxsIG9mIGl0LiBBdCB0aGUgZW5kOiBJIGtub3cgeW91IHRob3VnaHQgeW91IHdlcmUgZG9pbmcgd2hhdCB3YXMgYmVzdC4gSSBrbm93IHlvdSB3ZXJlIHRpcmVkIGFuZCBhZnJhaWQgYW5kIHlvdSB3ZXJlIHRoZSBvbmUgd2hvIHdhcyB0aGVyZS4gSSBhbSBhc2tpbmcgeW91IHRvIHVuZGVyc3RhbmQgdGhhdCBzaGUgd2FzIGFsc28gbWluZS4=',
            'choices'  => [
                ['text' => 'RmluZCBNYXJnYXJldCdzIHJlc3BvbnNl', 'next' => '7_response'],
            ],
        ],

        '6_after' => [
            'prose'   => 'VGhlIGZpcnN0IGxldHRlciBhZnRlciB0aGUgZ2FwIGlzIEF1ZHJleSdzLCAxOTg5LiBUaGUgaGFuZHdyaXRpbmcgaXMgdGhlIHNhbWUgYnV0IHNvbWV0aGluZyBpbiBpdCBoYXMgY2hhbmdlZCDigJQgbGVzcyBjb21wcmVzc2lvbiwgYXMgaWYgc29tZSBsb25nLWhlbGQgYnJlYXRoIGhhcyBiZWVuIGxldCBvdXQuCgpEZWFyIE1hZ2dpZSwgSSBhbSBnb2luZyB0byB0cnkuCgpFbGV2ZW4gd29yZHMuIFRoZW4gdGhyZWUgbGluZXMgb2Ygc3BhY2UuIFRoZW46CgpJIHNwZW50IGEgbG9uZyB0aW1lIGJlaW5nIGFuZ3J5IGFuZCBJIHdpbGwgYmUgaG9uZXN0IHRoYXQgSSBhbSBub3QgZW50aXJlbHkgZG9uZS4gQnV0IEkgYW0gdGlyZWQgb2YgYmVpbmcgdW5kb25lIGJ5IGl0LiBJIHRoaW5rIE11bSB3b3VsZCBiZSB0aXJlZCBvZiBpdCB0b28uCgpJIGRvbid0IGtub3cgd2hhdCB3ZSBhcmUgZ29pbmcgdG8gYmUgYWZ0ZXIgdGhpcy4gQnV0IEkgdGhpbmsgd2Ugc2hvdWxkIGZpbmQgb3V0LiBJZiB5b3Ugd2FudCB0by4KCkFuZCBiZW5lYXRoIGl0LCBhZGRlZCBpbiBhIGRpZmZlcmVudCBwZW4sIGFzIGlmIHNoZSB3ZW50IGJhY2s6IEkgc3RpbGwgaGF2ZSB0aGUgcmVjaXBlIHlvdSBzZW50IG1lIGZvciB0aGUgQ2hyaXN0bWFzIGNha2UuIEkgaGF2ZSBtYWRlIGl0IGV2ZXJ5IHllYXIuIEl0IGlzIG5ldmVyIHF1aXRlIHJpZ2h0LgoKTm8gc2lnbmF0dXJlLiBKdXN0IEEsIGFuZCBhIHNtYWxsIGdyZWVuIGFzdGVyaXNrLg==',
            'choices'  => [
                ['text' => 'RmluZCB3aGF0IE1hcmdhcmV0IHdyb3RlIGJhY2s=', 'next' => '7_response'],
            ],
        ],

        '7_response' => [
            'prose'   => 'TWFyZ2FyZXQncyByZXNwb25zZSB0byBBdWRyZXkncyAxOTc4IGxldHRlciB0YWtlcyB1cCBvbmUgcGFnZSBhbmQgaXMgd3JpdHRlbiBpbiBoZXIgbW9zdCBjYXJlZnVsIGhhbmQuCgpEZWFyIEEsIEkgYW0gbm90IGFza2luZyB5b3UgdG8gZm9yZ2l2ZSBtZSB5ZXQuIEkgYW0gYXNraW5nIHlvdSB0byBrbm93IHRoYXQgSSBrbm93LiBUaGF0IHNoZSB3YXMgeW91cnMgdG9vLiBUaGF0IHlvdSBoYWQgdGhlIHJpZ2h0IHRvIGJlIHRoZXJlLiBUaGF0IEkgdG9vayBzb21ldGhpbmcgZnJvbSB5b3UgdGhhdCBJIGNhbm5vdCBnaXZlIGJhY2suCgpJIHdvdWxkIGxpa2UsIHdoZW4geW91IGFyZSByZWFkeSwgdG8gdGVsbCB5b3Ugd2hhdCB0aGUgbGFzdCB5ZWFyIHdhcyBsaWtlLiBOb3QgdG8gZXhwbGFpbiDigJQgdGhlcmUgaXMgbm8gZXhwbGFuYXRpb24gdGhhdCBpcyBhbHNvIGhvbmVzdC4gT25seSB3aGF0IGhhcHBlbmVkLCBhbmQgd2hhdCBJIHdhcyB0aGlua2luZyB3aGVuIEkgZGlkIGl0LiBJIGJlbGlldmUgeW91IGRlc2VydmUgdG8ga25vdyB0aGUgc3BlY2lmaWNzLCBldmVuIGlmIHRoZXkgYXJlIG5vdCBiZXR0ZXIgdGhhbiB5b3UgaW1hZ2luZS4KCkkgaGF2ZSBrZXB0IHRoZSBncmVlbiBpbmsuCgpCZWxvdyB0aGlzLCBpbiBmcmVzaGVyIHdyaXRpbmcsIGFkZGVkIHllYXJzIGxhdGVyIGluIGEgZGlmZmVyZW50IGhhbmQ6IFNoZSB3cm90ZSB0aGlzLiBTaGUgc2F0IGluIHRoaXMgY2hhaXIgYW5kIHdyb3RlIHRoaXMgYW5kIHRoZW4gc2hlIGtlcHQgd3JpdGluZyB0byBtZSBmb3IgdGhpcnR5IG1vcmUgeWVhcnMuIFRoYXQgaXMgdGhlIGtpbmQgb2YgcGVyc29uIHNoZSB3YXMuCgpUaGUgc2Vjb25kIGhhbmR3cml0aW5nIGlzIEF1ZHJleSdzLg==',
            'terminal' => true,
            'choices'  => [
                ['text' => 'R28gdXAgdG8gdGhlIGF0dGlj', 'next' => '8_attic'],
            ],
        ],

        '8_attic' => [
            'prose'   => 'VGhlIGF0dGljIGlzIHRpZGllciB0aGFuIGF0dGljcyB1c3VhbGx5IGFyZSwgd2hpY2ggdGVsbHMgeW91IHNvbWV0aGluZyBhYm91dCBNYXJnYXJldC4gQm94ZXMgbGFiZWxsZWQgaW4gZ3JlZW4gaW5rOiBwaG90b2dyYXBocyAoMTk2MHMpLCBnYXJkZW4gcmVjb3JkcywgTXVtJ3MgdGhpbmdzIChrZWVwKSwgYW5kIGluIHRoZSBjb3JuZXIsIHB1c2hlZCB0byB0aGUgYmFjazogTXVtJ3MgdGhpbmdzIChyZXR1cm4gdG8gQSDigJQgdW5jb2xsZWN0ZWQpLgoKVGhhdCBsYXN0IGJveCBpcyBzbWFsbC4gWW91IHB1bGwgaXQgb3V0LgoKSW5zaWRlOiBhIGNoaWxkLXNpemVkIGtuaXR0ZWQgY2FyZGlnYW4gaW4gYSB5ZWxsb3cgdGhhdCBoYXMgZ29uZSB0aGUgY29sb3VyIG9mIG9sZCBjcmVhbS4gQSBiaXJ0aGRheSBjYXJkIGluIGEgaGFuZCBvbGRlciB0aGFuIGVpdGhlciBzaXN0ZXIncyDigJQgVG8gb3VyIEF1ZHJleSwgd2hvIGlzIHRlbiB0b2RheSBhbmQgYWxyZWFkeSBrbm93cyBtb3JlIHRoYW4gc2hlIGxldHMgb24uIExvdmUgYWx3YXlzLCBNdW0uIEFuZCB1bmRlcm5lYXRoLCBpbiBhIGZsYXQgZW52ZWxvcGUsIGEgZm9sZGVkIHNoZWV0IG9mIHBhcGVyIGNvdmVyZWQgaW4gY2FyZWZ1bCwgdW5mYW1pbGlhciB3cml0aW5nLgoKVGhlaXIgbW90aGVyJ3MgaGFuZHdyaXRpbmcuCgpUaGUgZW52ZWxvcGUgaXMgYWRkcmVzc2VkOiBGb3IgQXVkcmV5IOKAlCB3aGVuIHNoZSB3YW50cyBpdC4KCkl0IGhhcyBub3QgYmVlbiBvcGVuZWQu',
            'choices'  => [
                ['text' => 'T3BlbiBpdA==', 'next' => '9_elsie'],
                ['text' => 'VGFrZSBpdCBkb3duIHdpdGggdGhlIGJveA==', 'next' => '9_sealed'],
            ],
        ],

        '9_elsie' => [
            'prose'   => 'VGhlIGxldHRlciBpcyBkYXRlZCAxOTc2LiBFbHNpZSB3cm90ZSBpdCB3aGlsZSBzaGUgd2FzIHN0aWxsIGhlcnNlbGYsIGJlZm9yZSB0aGUgaWxsbmVzcy4KClNoZSB3cml0ZXMgYWJvdXQgdGhlIGJvYXJkaW5nIGhvdXNlLiBBYm91dCB0aGUgc2lzdGVycycgZmF0aGVyIOKAlCBub3QgaW4gZ3JpZWYgYnV0IGluIGFjY3VyYWN5LCB0ZWxsaW5nIEF1ZHJleSB0aGluZ3Mgc2hlIHRob3VnaHQgQXVkcmV5IHNob3VsZCBrbm93LiBTaGUgd3JpdGVzIGFib3V0IGEgd2VlayBhdCBMb3JuZSB3aGVuIEF1ZHJleSB3YXMgZm91ciBhbmQgTWFyZ2FyZXQgd2FzIHNldmVuIGFuZCB0aGUgdGhyZWUgb2YgdGhlbSB3ZW50IHRvIHRoZSBiZWFjaC4gQXVkcmV5IHdhcyBmcmlnaHRlbmVkIG9mIHRoZSB3YXZlcy4gTWFyZ2FyZXQgaGVsZCB5b3VyIGhhbmQgdGhlIHdob2xlIHRpbWUgYW5kIGRpZG4ndCBvbmNlIHNheSBzaGUgd2FzIGJvcmVkIG9yIHRoYXQgc2hlJ2QgcmF0aGVyIGJlIGluIHRoZSB3YXRlciBoZXJzZWxmLCBhbmQgc2hlIHdhcyBzZXZlbiB5ZWFycyBvbGQuIEkgd2FudCB5b3UgdG8gcmVtZW1iZXIgdGhhdCBhYm91dCBoZXIuCgpOZWFyIHRoZSBlbmQ6IFRoZXJlIHdpbGwgcHJvYmFibHkgYmUgYSB0aW1lIHdoZW4geW91IGFyZSB2ZXJ5IGFuZ3J5IHdpdGggaGVyLiBTaGUgd2lsbCBoYXZlIGVhcm5lZCBpdCwgb3Igc2hlIHdpbGwgdGhpbmsgc2hlIGhhcywgd2hpY2ggY29tZXMgdG8gbXVjaCB0aGUgc2FtZSB0aGluZy4gSSBhbSBhc2tpbmcgeW91IGluIGFkdmFuY2UgdG8gZ2l2ZSBpdCB0aW1lLiBTaGUgaGFzIGEgZ29vZCBoZWFydCBhbmQgc2hlIGlzIGZyaWdodGVuZWQgb2YgaXQuCgpUaGlzIGlzIG5vdCBiZWNhdXNlIHNoZSBtYXR0ZXJzIG1vcmUgdGhhbiB5b3UuIFRoaXMgaXMgYmVjYXVzZSB5b3UgYXJlIHN0cm9uZ2VyIHRoYW4gc2hlIGtub3dzLCBhbmQgSSB3YW50IHRvIHNhdmUgaGVyLgoKRWxzaWUgTWFyc2gsIDE5NzYsIGluIGEgbGV0dGVyIHNoZSBhZGRyZXNzZWQgdG8gaGVyIHlvdW5nZXIgZGF1Z2h0ZXIgYW5kIG5ldmVyIHNlbnQu',
            'choices'  => [
                ['text' => 'R28gYmFjayBkb3duIGFuZCBmaW5kIHRoZSBsYXN0IGxldHRlcg==', 'next' => '10_last'],
            ],
        ],

        '9_sealed' => [
            'prose'   => 'WW91IHB1dCB0aGUgZW52ZWxvcGUgaW4geW91ciBiYWcgd2l0aG91dCBvcGVuaW5nIGl0LiBJdCB3YXMgbm90IGFkZHJlc3NlZCB0byB5b3UuCgpUaGVyZSBpcyBhIHF1ZXN0aW9uIG9mIHdobyBpdCB3YXMgYWRkcmVzc2VkIGZvci4gQXVkcmV5IGRpZWQgaW4gT2N0b2Jlci4gTWFyZ2FyZXQgZGllZCBpbiBNYXkuIE5laXRoZXIgb2YgdGhlbSB3aWxsIHJlYWQgaXQgbm93LiBZb3UgdGhpbmsgYWJvdXQgTXJzIEZhbGxvbiBuZXh0IGRvb3IsIG9yIHdob2V2ZXIgZXZlbnR1YWxseSBjb21lcyBmb3IgdGhlIHJlc3Qgb2YgdGhlc2UgYm94ZXMuIFlvdSB0aGluayBhYm91dCB0aGUgZmFjdCB0aGF0IEVsc2llIGFkZHJlc3NlZCBpdCBhbmQga2VwdCBpdCBoZXJzZWxmIGFuZCBuZXZlciBnYXZlIGl0LiBUaGF0IHRoZSBrZWVwaW5nIHdhcyBhbHNvIGEgY2hvaWNlLgoKU29tZSB0aGluZ3MgYXJlIHdyaXR0ZW4gdG8gYmUgaGVsZCByYXRoZXIgdGhhbiBkZWxpdmVyZWQuIFRoZSBhY3Qgb2Ygd3JpdGluZyBpcyB0aGUgYWN0OyB0aGUgYXJyaXZhbCBpcyBhIGRpZmZlcmVudCBtYXR0ZXIuCgpZb3UgcHV0IHRoZSBib3ggaW4geW91ciBiYWcgYXMgd2VsbC4gVGhlIHNvbGljaXRvciB3aWxsIGhhdmUgYW4gYWRkcmVzcyBmb3Igc29tZW9uZSBpbiB0aGUgZmFtaWx5Lg==',
            'choices'  => [
                ['text' => 'R28gYmFjayBkb3duIGFuZCBmaW5kIHRoZSBsYXN0IGxldHRlcg==', 'next' => '10_last'],
            ],
        ],

        '10_last' => [
            'prose'   => 'VGhlIHVuc2VudCBsZXR0ZXIgb24gdGhlIGRlc2suIFlvdSBvcGVuIGl0IG5vdy4KCk1hcmdhcmV0J3MgaGFuZHdyaXRpbmcsIHNoYWtpZXIgdGhhbiB0aGUgMTk5MHMgbGV0dGVycyBidXQgdGhlIGdyZWVuIGluayB0aGUgc2FtZS4gVGhpcyB3YXMgd3JpdHRlbiBpbiBKYW51YXJ5LCB0aHJlZSB3ZWVrcyBhZnRlciBNYXJnYXJldCBmb3VuZCBvdXQgYWJvdXQgQXVkcmV5J3MgZGVhdGguCgpEZWFyIEEsCgpJIGhhdmUgYmVlbiB0cnlpbmcgdG8gZmluZCB0aGUgcmlnaHQgdGltZSB0byBhc2sgeW91IHNvbWV0aGluZyBmb3IgYXBwcm94aW1hdGVseSB0aGlydHkgeWVhcnMgYW5kIEkgdGhpbmsgSSBoYXZlIHRvIGFjY2VwdCB0aGF0IHRoZSByaWdodCB0aW1lIGlzIG5vdCBnb2luZyB0byBhbm5vdW5jZSBpdHNlbGYuCgpJIHdvdWxkIGxpa2UgdG8gY29tZSBhbmQgc3RheSwgaWYgeW91J2xsIGhhdmUgbWUuIEp1c3QgYSBmZXcgZGF5cy4gSSBoYXZlIE11bSdzIENocmlzdG1hcyBjYWtlIHJlY2lwZSDigJQgbm90IHRoZSBvbmUgeW91IGhhdmUsIHdoaWNoIEkgdGhpbmsgd2FzIHRoZSB2ZXJzaW9uIGZyb20gd2hlbiB3ZSB3ZXJlIHNtYWxsLCBiZWZvcmUgc2hlIHN0YXJ0ZWQgdXNpbmcgYnJvd25lZCBidXR0ZXIuIEkgaGF2ZSB0aGUgbGF0ZXIgb25lLCB0aGUgYmV0dGVyIG9uZS4gSSB3b3JrZWQgaXQgb3V0IGZyb20gbWVtb3J5IG92ZXIgYWJvdXQgZWlnaHQgeWVhcnMgb2YgdHJ5aW5nLiBJIHNob3VsZCBoYXZlIGJyb3VnaHQgaXQgaW4gcGVyc29uIHllYXJzIGFnby4gSSBrZXB0IG1lYW5pbmcgdG8uCgpJIHdvdWxkIGxpa2UgdG8gc2l0IGluIHlvdXIga2l0Y2hlbi4gSSB3b3VsZCBsaWtlIHRvIGhhdmUgYSBmZXcgZGF5cyB3aXRob3V0IGFueSBvY2Nhc2lvbi4KCkxvdmUsIE1hZ2dpZS4KClAuUy4gSSBzdGlsbCBoYXZlIHRoZSBncmVlbiBpbmsu',
            'terminal' => true,
            'choices'  => [
                ['text' => 'RmluaXNoIHRoZSBpbnZlbnRvcnk=', 'next' => '11_end_keep'],
                ['text' => 'RHJpdmUgdG8gQmFsbGFyYXQ=', 'next' => '11_end_send'],
            ],
        ],

        '11_end_keep' => [
            'prose'   => 'WW91IGZpbmlzaCB0aGUgaW52ZW50b3J5LiBUd2VsdmUgaXRlbXMgcGx1cyBjb3JyZXNwb25kZW5jZS4gWW91IG5vdGUgdGhlIGxldHRlcnMgb24gdGhlIHNvbGljaXRvcidzIGxpc3QgYXMgcGVyc29uYWwgY29ycmVzcG9uZGVuY2UsIHRvIGJlIHJldGFpbmVkIHdpdGggdGhlIGZhbWlseSByZWNvcmRzLiBXaGljaCBpcyB3aGF0IHRoZXkgYXJlLgoKT24gdGhlIHdheSBvdXQgeW91IHRha2UgdGhlIGNha2UuIE1ycyBGYWxsb24gaXMgYXQgaGVyIHdpbmRvdzsgeW91IHdhdmUsIGFuZCBhZnRlciBhIG1vbWVudCBzaGUgd2F2ZXMgYmFjay4KCllvdSBzaXQgaW4gdGhlIGNhciBmb3IgYSB3aGlsZSBiZWZvcmUgc3RhcnRpbmcgaXQuIFRoZSB1bnNlbnQgbGV0dGVyIGlzIGluIHlvdXIgYmFnLCBhbmQgdGhlIGJveCBmcm9tIHRoZSBhdHRpYywgYW5kIHRoZSBzcGVjaWZpYyB3ZWlnaHQgb2Yga25vd2luZyB3aGF0IHRoZSBsYXN0IHRoaW5nIHdhcyB0aGF0IE1hcmdhcmV0IHdhbnRlZCB0byBhc2suCgpTb21lIGxldHRlcnMgZG9uJ3QgYXJyaXZlLiBUaGUgZm9ydHkgeWVhcnMgb2YgZ3JlZW4gaW5rIHN0aWxsIGZvdW5kIHRoZWlyIHdheSwgd2hpY2ggaXMgbW9yZSB0aGFuIG1vc3QgY29ycmVzcG9uZGVuY2VzIG1hbmFnZS4KClRoZSBnYXRlIGNsb3NlcyBvbiBpdHMgb3duIHdlaWdodC4gWW91IGRyaXZlIGhvbWUu',
            'ending'   => true,
        ],

        '11_end_send' => [
            'prose'   => 'QmFsbGFyYXQgaXMgdHdvIGhvdXJzLiBZb3UgdGFrZSB0aGUgY2FrZS4KCkEuIEcuIE1hcnNoIOKAlCBCZWxvdmVkIHNpc3Rlci4gVGhlIGdyYXZlIGlzIG5vdCBoYXJkIHRvIGZpbmQuIFNvbWVvbmUgZWxzZSdzIGZsb3dlcnMsIGFuZCBiZW5lYXRoIHRoZW0sIHJlY2VudDogYSBzbWFsbCBidW5kbGUgb2Ygc29tZXRoaW5nIGRyaWVkIGFuZCBncmVlbiwgdGllZCB3aXRoIGdyZWVuIHRocmVhZC4gTXJzIEZhbGxvbiwgeW91IHRoaW5rLiBPZiBjb3Vyc2UuCgpZb3UgcHV0IHRoZSBsZXR0ZXIgb24gdGhlIHN0b25lLiBZb3Ugc3RheSBhIHdoaWxlLiBUaGUgYWZ0ZXJub29uIGxpZ2h0IGlzIHRoZSBwYXJ0aWN1bGFyIGdvbGQgb2YgbGF0ZSBhdXR1bW4sIGZhbGxpbmcgb24gZXZlcnl0aGluZyB3aXRob3V0IHByZWZlcmVuY2UsIGFuZCB0aGUgd2luZCBmcm9tIHRoZSB3ZXN0IHNtZWxscyBvZiBjdXQgZ3Jhc3MgYW5kIHNvbWV0aGluZyBlbHNlLCBzb21ldGhpbmcgdGhhdCBpc24ndCBsb3NzIGV4YWN0bHksIG9yIG5vdCBvbmx5LgoKT24gdGhlIGRyaXZlIGJhY2sgeW91IHRoaW5rIGFib3V0IEVsc2llIGluIDE5NzYsIHdyaXRpbmcgdG8gaGVyIHlvdW5nZXIgZGF1Z2h0ZXIgaW4gYWR2YW5jZSBhYm91dCB0aGUgdGhpbmcgc2hlIHdhcyBnb2luZyB0byBuZWVkLiBBYm91dCB0aGlydHkgeWVhcnMgYWZ0ZXIgdGhlIGdhcCDigJQgbHVuY2hlcyBpbiBCYWxsYXJhdCwgbGV0dGVycyBnb2luZyBib3RoIHdheXMsIG5vdCB0aGUgc2FtZSBhcyB3aGF0IHdhcyBsb3N0IGJ1dCBzb21ldGhpbmcgcGVyaGFwcyB0cnVlciBmb3IgaGF2aW5nIGJlZW4gcmVidWlsdC4gQWJvdXQgYSBDaHJpc3RtYXMgY2FrZSByZWNpcGUgYXJyaXZlZCBhdCBvdmVyIGVpZ2h0IHllYXJzIG9mIHRyeWluZywgYW5kIHRoZSByaWdodCB0aW1lIHRvIGJyaW5nIGl0IHRoYXQga2VwdCBub3QgYXJyaXZpbmcsIHVudGlsIGl0IGNvdWxkbid0LgoKWW91IHRoaW5rIHRoaXMgbWF5IGJlIHdoYXQgZmFpdGhmdWxuZXNzIGlzLiBOb3QgdGhlIGNsZWFuIHZlcnNpb24g4oCUIHRoZSBsb25nIHdheSByb3VuZCwgdGhlIHZlcnNpb24gd2l0aCBhIGdhcCBpbiB0aGUgbWlkZGxlLCB0aGUgc3RpbGwgdHJ5aW5nLgoKWW91IGRyaXZlIGhvbWUu',
            'ending'   => true,
        ],

    ],
];
