<?php
return [
    'id'    => 'q21',
    'title' => 'The Valley of Stones',
    'color' => '#6A5A70',

    'pages' => [
        '1_start' => [
            'prose'   => 'VGhlIHZhbGxleSBkb2Vzbid0IGxvb2sgbGlrZSBhIGRlc3RpbmF0aW9uIHNvIG11Y2ggYXMgYSBkZWNpc2lvbiBzb21lb25lIG1hZGUgYSB2ZXJ5IGxvbmcgdGltZSBhZ28gYW5kIG5ldmVyIGZpbmlzaGVkIGV4cGxhaW5pbmcg4oCUIHN0YW5kaW5nIHN0b25lcyBzY2F0dGVyZWQgYWNyb3NzIG9wZW4gZ3JvdW5kIGluIHJvd3MgdGhhdCBhbG1vc3QsIGJ1dCBkb24ndCBxdWl0ZSwgbWFrZSBzZW5zZSBmcm9tIGFueSBzaW5nbGUgdmFudGFnZSBwb2ludCwgbW9zcy1kYXJrIGFuZCB0YWxsZXIgdGhhbiB5b3UgZXhwZWN0ZWQsIHN0cmV0Y2hpbmcgZnVydGhlciB0aGFuIHlvdSBjYW4gZWFzaWx5IGNvdW50LgoKVGhpcyBpc24ndCBhIHRvdXJpc3Qgc2l0ZSwgd2hhdGV2ZXIgdGhlIHJvYWQgc2lnbnMgZnVydGhlciBiYWNrIHN1Z2dlc3RlZC4gSXQncyBhIHdvcmtpbmcgbGFuZHNjYXBlIOKAlCBzaGVlcCBncmF6aW5nIGJldHdlZW4gdGhlIHN0b25lcywgYSBmYXJtZXIncyBjYXJ0IHRyYWNrIHJ1bm5pbmcgc3RyYWlnaHQgdGhyb3VnaCB0aGUgbWlkZGxlIG9mIHRoZSBvbGRlc3QgYWxpZ25tZW50IGFzIHRob3VnaCB0aGUgc3RvbmVzIHdlcmUgc2ltcGx5IHBhcnQgb2YgdGhlIGZ1cm5pdHVyZSBvZiB0aGUgcGxhY2UgcmF0aGVyIHRoYW4gYW55dGhpbmcgcmVxdWlyaW5nIHNwZWNpYWwgdHJlYXRtZW50LgoKVGhlIHByZXNzZWQgbW91bnRhaW4gZmxvd2VyIHJpZGVzIHNhZmUgaW4gdGhlIGJvdGFuaWNhbCBib29rIG5vdywgZmlsZWQgbmV4dCB0byBpdHMgaGlsbC1mb3JtIGNvdXNpbi4gSmFtZXMgaGFzIGdvbmUgdmVyeSBzdGlsbCBhbmQgYWxlcnQsIHRoZSB3YXkgaGUgZG9lcyBpbiBvbGQgcGxhY2VzLiBGcmVkIGlzIGFscmVhZHkgdmlicmF0aW5nIHdpdGggYmFyZWx5LWNvbnRhaW5lZCBvcGluaW9ucyBhYm91dCBsaWNoZW4gZ3Jvd3RoIHJhdGVzIG9uIHN0b25lIHRoaXMgYWdlLgoKQSBzY2hvbGFyIHdobyBoYXMgc3BlbnQgZGVjYWRlcyBjYXRhbG9ndWluZyB0aGlzIHZhbGxleSB3b3JrcyBmcm9tIGEgc21hbGwgaHV0IGF0IGl0cyBlZGdlLCBtZXRob2RpY2FsIGFuZCBzbG93LiBPciB0aGUgbG9jYWwgc2hlcGhlcmRzIGFuZCBmYXJtZXJzLCB3aG8ga25vdyB0aGUgc3RvbmVzJyBzdG9yaWVzIHdpdGhvdXQgYW55IG9mIHRoZSBhY2FkZW1pYyBmcmFtZXdvcmssIGFyZSB2aXNpYmxlIHdvcmtpbmcgdGhlIGZhciBmaWVsZC4=',
            'choices' => [
                ['text' => 'RmluZCB0aGUgc2Nob2xhcg==', 'next' => '2_scholar'],
                ['text' => 'QXNrIHRoZSBzaGVwaGVyZHM=', 'next' => '2_oral'],
            ],
        ],

        '2_scholar' => [
            'prose'   => 'VGhlIHNjaG9sYXIncyBodXQgaXMgc3RhY2tlZCBmbG9vciB0byBjZWlsaW5nIHdpdGggcnViYmluZ3MsIHBob3RvZ3JhcGhzLCBhbmQgbm90ZWJvb2tzIGluIGEgaGFuZCBzbyBzbWFsbCBhbmQgY2FyZWZ1bCBpdCBsb29rcyBhbG1vc3QgdHlwZXNldC4gSGUgZXhhbWluZXMgdGhlIHByZXNzZWQgZmxvd2VyIHlvdSBzaG93IGhpbSB3aXRoIHJlYWwgYXR0ZW50aW9uLCB0dXJuaW5nIGl0IHVuZGVyIGEgZ2xhc3MuCgoiSXMgdGhpcyBMaW1vbmVsbGEgbWVyaWRpYW5hLCBoaWxsIGZvcm0/IiBoZSBhc2tzLCBhbmQgZG9lc24ndCB3YWl0IGZvciB5b3VyIGFuc3dlciBiZWZvcmUgY29udGludWluZy4gIlNoZSBuYW1lZCB0aGF0LiBJIGhhdmUgaGVyIGNvcnJlc3BvbmRlbmNlIHNvbWV3aGVyZSBpbiBoZXJlIOKAlCBzaGUgd3JvdGUgdG8gaGFsZiB0aGUgYW1hdGV1ciBib3RhbmljYWwgc29jaWV0aWVzIGluIEV1cm9wZSwgeW91IGtub3csIHVuZGVyIGhlciBtYWlkZW4gbmFtZS4iIEhlIGxvb2tzIHVwIHByb3Blcmx5LiAiU2hlIHdhcyBoZXJlIHRvby4gVGhlcmUncyBhIHN0b25lIHdpdGggaGVyIGluaXRpYWxzIG9uIGl0LCBpZiB5b3Uga25vdyB3aGVyZSB0byBsb29rLiBJJ3ZlIGFsd2F5cyB3b25kZXJlZCB3aG8gY2FydmVkIGl0LiIKCkhlIGxlYWRzIHlvdSBvdXQgaW50byB0aGUgZmllbGQgd2l0aG91dCBmdXJ0aGVyIGNlcmVtb255LCBtb3Zpbmcgd2l0aCB0aGUgc3VyZWZvb3RlZG5lc3Mgb2Ygc29tZW9uZSB3aG8gaGFzIHdhbGtlZCB0aGlzIGV4YWN0IGdyb3VuZCBmb3IgZm9ydHkgeWVhcnMu',
            'choices' => [
                ['text' => 'Rm9sbG93IGhpbSBpbnRvIHRoZSBmaWVsZA==', 'next' => '3_chaiwalla'],
            ],
        ],

        '2_oral' => [
            'prose'   => 'VGhlIHNoZXBoZXJkcyB3b3JraW5nIHRoZSBmYXIgZmllbGQgYXJlIHVuaHVycmllZCBhYm91dCBldmVyeXRoaW5nLCBpbmNsdWRpbmcgeW91ciBxdWVzdGlvbnMsIGJ1dCBldmVudHVhbGx5IG9uZSBvZiB0aGUgb2xkZXIgd29tZW4g4oCUIHNoYXJwLWV5ZWQsIHdlYXRoZXJlZCwgY2xlYXJseSB0aGUgb25lIHdob3NlIHdvcmQgc2V0dGxlcyBhcmd1bWVudHMg4oCUIHRha2VzIHJlYWwgaW50ZXJlc3QgaW4gdGhlIHByZXNzZWQgZmxvd2VyLgoKIlRoZSB3b21hbiB3aG8gbmFtZWQgdGhhdCBmbG93ZXIgY2FydmVkIGEgc3RvbmUgaGVyZSwiIHNoZSBzYXlzLCB3aXRob3V0IG5lZWRpbmcgdG8gY29uc3VsdCBhbnlvbmUgZWxzZSBhYm91dCBpdC4gIkxvbmcgYmVmb3JlIG15IHRpbWUsIGJ1dCBteSBncmFuZG1vdGhlciB0b2xkIGl0IHRvIG1lLCBhbmQgaGVycyB0b2xkIGhlci4gU2hlIHNhaWQgaXQgd2FzIHRoZSBsYXN0IHdvcmQgb2YgYSBsb25nIHNlbnRlbmNlLiIgU2hlIGRvZXNuJ3QgZXhwbGFpbiBmdXJ0aGVyLCBqdXN0IHR1cm5zIGFuZCBzdGFydHMgd2Fsa2luZywgZXhwZWN0aW5nIHlvdSB0byBmb2xsb3cuCgpZb3UgZm9sbG93LiBUaGUgc3RvbmVzIGNsb3NlIGluIGFyb3VuZCB5b3UgYm90aCwgdGFsbGVyIHRoZSBmdXJ0aGVyIHlvdSBnbywgdW50aWwgdGhlIHdob2xlIHZhbGxleSBzdGFydHMgdG8gZmVlbCBsZXNzIGxpa2UgYSBmaWVsZCBhbmQgbW9yZSBsaWtlIGEgcm9vbSB3aXRoIG5vIHJvb2Yu',
            'choices' => [
                ['text' => 'Rm9sbG93IGhlciBkZWVwZXIgaW50byB0aGUgc3RvbmVz', 'next' => '3_chaiwalla'],
            ],
        ],

        '3_chaiwalla' => [
            'prose'   => 'VGhlcmUncyBhIHNtYWxsIGZpcmUgYnVybmluZyBiZXR3ZWVuIHR3byBvZiB0aGUgb2xkZXN0IHN0b25lcywgYnJhc3MgcG90IGJhbGFuY2VkIG92ZXIgaXQsIGV4YWN0bHkgd2hlcmUgYSBmaXJlIGhhcyBubyBwYXJ0aWN1bGFyIGJ1c2luZXNzIGJlaW5nIGFsbG93ZWQgYnV0IGNsZWFybHkgYWx3YXlzIGlzLgoKSGUncyBub3Qgc3VycHJpc2VkIHRvIHNlZSB5b3UuIEhlJ3MgYmFyZWx5IGV2ZW4gbG9va2luZyB1cCB3aGVuIHlvdSBhcnJpdmUsIGFzIHRob3VnaCBoZSdkIHNpbXBseSBiZWVuIHdhaXRpbmcgZm9yIHlvdSB0byBmaW5pc2ggd2hhdGV2ZXIgY29udmVyc2F0aW9uIGdvdCB5b3UgaGVyZS4KCiJTaGUgbWFkZSBtZSBwcm9taXNlIHRvIGJlIGhlcmUgZm9yIHRoaXMgcGFydCwiIGhlIHNheXMsIGJlZm9yZSB5b3UndmUgc2FpZCBhbnl0aGluZyBhdCBhbGwuICJGb3J0eSB5ZWFycyBhZ28uIEkgbWFkZSBhIGxvdCBvZiBwcm9taXNlcyB0byBoZXIgYXQgc2V2ZW50ZWVuLCB0aGUgd2F5IHlvdSBkby4gSSBoYXZlbid0IGFsd2F5cyBiZWVuIGNlcnRhaW4gSSdkIGtlZXAgZXZlcnkgb25lIG9mIHRoZW0uIiBIZSBsb29rcyB1cCBhdCB5b3Ugbm93LCBwcm9wZXJseS4gIkJ1dCBoZXJlIEkgYW0uIgoKSGUgZG9lc24ndCBwb3VyIHRoZSBjaGFpIHlldC4gRm9yIG9uY2UsIGhlIHNlZW1zIHRvIGJlIHdhaXRpbmcgZm9yIHNvbWV0aGluZyBlbHNlIGZpcnN0Lg==',
            'choices' => [
                ['text' => 'QXNrIGhpbSB3aGF0IGhlJ3MgYmVlbiB3YWl0aW5nIHRvIHRlbGwgeW91', 'next' => '4_decode'],
            ],
            'terminal' => true,
        ],

        '4_decode' => [
            'prose'   => 'IllvdSd2ZSBiZWVuIGNvbGxlY3RpbmcgcGllY2VzIG9mIGEgc2VudGVuY2Ugc2luY2UgdGhlIHNlY29uZCBzdG9wIG9uIHRoaXMgd2hvbGUgcm9hZCwiIGhlIHNheXMuICJUaGUgbWFya2V0IHRvd24uIFlvdSByZW1lbWJlci4iIFlvdSBkby4gIkkga25vdyBhbGwgb2YgaXQuIEkndmUga25vd24gaXQgc2luY2UgYmVmb3JlIHlvdSB3ZXJlIGJvcm4uIFNoZSByZWNpdGVkIGl0IHRvIG1lIG9uY2UsIHRoZSBuaWdodCBiZWZvcmUgc2hlIGxlZnQgaG9tZSBmb3IgZ29vZCwgYW5kIHRvbGQgbWUgSSdkIGtub3cgd2hlbiBpdCB3YXMgdGltZSB0byBzYXkgaXQgYmFjay4iCgpIZSBzYXlzIGl0IHNsb3dseSwgZ2l2aW5nIGVhY2ggcGFydCBpdHMgb3duIHdlaWdodCwgdGhlIGZpcmUgYmV0d2VlbiB5b3UgYm90aCBob2xkaW5nIHVubmF0dXJhbGx5IHN0ZWFkeSBpbiBhIHZhbGxleSB0aGF0IGlzbid0IHNoZWx0ZXJlZCBmcm9tIHRoZSB3aW5kIGF0IGFsbC4KCiJXaGVyZSBJIHdhbGtlZCwgSSBsZWZ0IHNvbWV0aGluZyBvZiB3aGF0IEkgY2FycmllZCwiIGhlIHNheXMuICJUaGUgbGFzdCBvZiBpdCByZXN0cyB3aGVyZSBJIGZpcnN0IGJlZ2FuIHRvIHVuZGVyc3RhbmQgd2hhdCBjYXJyeWluZyBtZWFucy4gVGhhdCB3YXMgYXQgaG9tZSwgaW4gdGhlIHJvb20gd2hlcmUgc2hlIHNob3dlZCBtZSB3aGF0IHNoZSBoYWQgbWFkZS4gSSBoYXZlIGNhcnJpZWQgaXQgZXZlciBzaW5jZS4iCgpIZSBwYXVzZXMuCgoiQ29tZSBob21lLCIgaGUgc2F5cywgYW5kIHRoZSB3aG9sZSBzZW50ZW5jZSBmaW5hbGx5IGNsb3Nlcywgc2V2ZW4gZnJhZ21lbnRzIGFuZCBhIGxpZmV0aW1lIG9mIGNhcnJ5aW5nIHJlc29sdmluZyBpbnRvIGZvdXIgd29yZHMgcGxhaW4gZW5vdWdoIHRoYXQgeW91IGFsbW9zdCBsYXVnaCBhdCBob3cgc2ltcGxlIGl0IHR1cm5zIG91dCB0byBiZSwgdW5kZXJuZWF0aCBldmVyeXRoaW5nLg==',
            'choices' => [
                ['text' => 'R28gZmluZCB0aGUgc3RvbmUgd2l0aCBoZXIgaW5pdGlhbHM=', 'next' => '5_stone'],
            ],
        ],

        '5_stone' => [
            'prose'   => 'VGhlIHN0b25lIHRoZSBzY2hvbGFyIG9yIHRoZSBzaGVwaGVyZCBzaG93ZWQgeW91IHR1cm5zIG91dCB0byBiZSB0aGUgdGFsbGVzdCBpbiB0aGlzIHBhcnRpY3VsYXIgcm93IOKAlCBhbmQgY2FydmVkIGludG8gaXRzIGZhY2UsIHdlYXRoZXJlZCBidXQgdW5taXN0YWthYmxlLCBhIHJlbGllZjogc3BpcmFscyB3aXRoaW4gc3BpcmFscywgYSBwYXR0ZXJuIHRoYXQgbG9va3MgYWJzdHJhY3QgdW50aWwgeW91J3ZlIHN0YXJlZCBhdCBpdCBsb25nIGVub3VnaCB0byBzZWUgaXQncyBhY3R1YWxseSBhIHJvYWQsIGN1cmxpbmcgaW4gb24gaXRzZWxmIGFuZCBlbmRpbmcsIGRlbGliZXJhdGVseSwgYXQgYSBzbWFsbCBjYXJ2ZWQgZG9vci4KClRoaXMgb25lIHlvdSBjYW4ndCB0YWtlLiBJdCdzIHN0b25lLCBhbmQgaXQncyBlbm9ybW91cywgYW5kIGl0J3MgY2xlYXJseSBtZWFudCB0byBzdGF5IGV4YWN0bHkgd2hlcmUgaXQncyBzdG9vZCBmb3IgaG93ZXZlciBsb25nIGl0J3Mgc3Rvb2QgdGhlcmUuCgpJbnN0ZWFkIHlvdSBtYWtlIGEgcnViYmluZyDigJQgY2hhcmNvYWwgYWdhaW5zdCBwYXBlciwgcHJlc3NlZCBjYXJlZnVsbHkgaW50byBldmVyeSBncm9vdmUsIHRoZSB3aG9sZSBkZXNpZ24gdHJhbnNmZXJyaW5nIGxpbmUgYnkgbGluZSB1bnRpbCB5b3UncmUgaG9sZGluZyBhIGNvcHkgZ29vZCBlbm91Z2ggdG8gZm9sZCBhbmQgY2FycnkuCgpUaGUgc2Nob2xhciwgb3IgdGhlIHNoZXBoZXJkLCBwcmVzc2VzIHNvbWV0aGluZyBlbHNlIGludG8geW91ciBoYW5kcyBhcyB5b3UgZmluaXNoOiBhIHNtYWxsIGNsYXkgcG90IG9mIHRoaWNrIGJsYWNrIGluay4gIkZvciB0aG9zZSB3aG8ndmUgcmVhZCB0aGUgdmFsbGV5IHByb3Blcmx5LCIgc2hlIOKAlCBvciBoZSDigJQgc2F5cy4gIkxvY2FsIHRyYWRpdGlvbi4gWW91J3ZlIGVhcm5lZCBpdC4iCgpGcmVkIGV4YW1pbmVzIHRoZSBpbmsgd2l0aCBzdWRkZW4sIGZvY3VzZWQgaW50ZXJlc3QuICJPYWsgZ2FsbCBhbmQgaXJvbiBveGlkZSwiIGhlIHNheXMgcXVpZXRseS4gIlRoZSBzYW1lIG1hdGVyaWFscyBhcyBoZXIgYm90YW5pY2FsIGxhYmVscy4gVGhlIGV4YWN0IHNhbWUgaW5rLiIgSGUgZG9lc24ndCBzYXkgYW55dGhpbmcgZWxzZSBmb3IgYSB3aGlsZS4=',
            'choices' => [
                ['text' => 'UHV0IHRoZSBmbG93ZXIgYXdheSBhbmQgcmVzdCBhIG1vbWVudA==', 'next' => '6_recognition'],
            ],
        ],

        '6_recognition' => [
            'prose'   => 'V2hpbGUgeW91J3JlIHBhY2tpbmcgdGhlIHJ1YmJpbmcgYXdheSwgRnJlZCB0YWtlcyB0aGUgcHJlc3NlZCBtb3VudGFpbiBmbG93ZXIgZnJvbSB0aGUgYm90YW5pY2FsIGJvb2sgb25lIG1vcmUgdGltZSwgdHVybmluZyBpdCBvdmVyIGJlc2lkZSBpdHMgaGlsbC1mb3JtIGNvdXNpbiBmcm9tIHRoZSBBbHNhY2UgZmFpci4KCiJTaGUgbmFtZWQgdGhlIGhpbGwgc3BlY2llcyBmb3IgdGhlIGhpbGwsIiBoZSBzYXlzIHNsb3dseSwgImJlY2F1c2Ugc2hlIGNvdWxkbid0IGdvIGJhY2sgdG8gdGhlIG1vdW50YWluLiIgSGUgbG9va3MgdXAsIHNhdGlzZmllZCB3aXRoIGhpbXNlbGYgaW4gdGhlIHdheSBoZSBnZXRzIHdoZW4gYSBwaWVjZSBvZiBib3RhbnkgaGFzIGZpbmFsbHkgZXhwbGFpbmVkIGEgcGllY2Ugb2YgYSBwZXJzb24uICJTaGUgbmFtZWQgaXQgYWZ0ZXIgdGhlIHBsYWNlIHNoZSBjaG9zZSBpbnN0ZWFkIG9mIHRoZSBvbmUgc2hlIGNvdWxkbid0IHJldHVybiB0by4iCgpUaGUgY2hhaXdhbGxhLCBjcm91Y2hlZCBieSB0aGUgZmlyZSwgc2F5cyB0aGUgZXhhY3Qgc2FtZSB0aGluZyBhIGJlYXQgbGF0ZXIsIGluIGFsbW9zdCB0aGUgZXhhY3Qgc2FtZSB3b3Jkcywgd2l0aG91dCBoYXZpbmcgaGVhcmQgYSBzeWxsYWJsZSBvZiBGcmVkJ3MgdmVyc2lvbi4KClRoZXkgYm90aCBzdG9wLiBUaGV5IGxvb2sgYXQgZWFjaCBvdGhlciDigJQgcGFycm90IGFuZCBzdHJhbmdlciwgYm90YW55IGFuZCBmb3J0eSB5ZWFycyBvZiBtZW1vcnksIGFycml2aW5nIGF0IHByZWNpc2VseSB0aGUgc2FtZSB1bmRlcnN0YW5kaW5nIGZyb20gY29tcGxldGVseSBkaWZmZXJlbnQgZGlyZWN0aW9ucy4KCk5laXRoZXIgc2F5cyBhbnl0aGluZyBhYm91dCBpdC4gQnV0IHNvbWV0aGluZyBwYXNzZXMgYmV0d2VlbiB0aGVtIHRoYXQgbG9va3MsIHVubWlzdGFrYWJseSwgbGlrZSByZXNwZWN0Lg==',
            'choices' => [
                ['text' => 'U2l0IGJ5IHRoZSBmaXJlIGZvciB0aGUgZXZlbmluZw==', 'next' => '7_evening'],
            ],
        ],

        '7_evening' => [
            'prose'   => 'VGhlIGNoYWl3YWxsYSBmaW5hbGx5IHBvdXJzIHRoZSBjaGFpIOKAlCBkaWZmZXJlbnQgYWdhaW4gZnJvbSBldmVyeSB2ZXJzaW9uIHlvdSd2ZSBoYWQgb24gdGhpcyB3aG9sZSByb2FkLCBzb21ldGhpbmcgaW4gaXQgZGFyayBhbmQgc2xpZ2h0bHkgc21va3kgdGhhdCBtdXN0IGJlIHBhcnRpY3VsYXIgdG8gdGhpcyB2YWxsZXksIHRoaXMgZmlyZSwgdGhpcyBleGFjdCBtb21lbnQuCgoiQnJpdHRhbnkgY2hhaSwiIGhlIHNheXMsIGJ5IHdheSBvZiBleHBsYW5hdGlvbiwgYXMgdGhvdWdoIHRoYXQgc2V0dGxlcyBpdC4KCkphbWVzIGhhcyBjdXJsZWQgdXAgbmVhciB0aGUgZmlyZSdzIGVkZ2UsIGVudGlyZWx5IHVuYm90aGVyZWQgYnkgdGhlIGVub3JtaXR5IG9mIHN0b25lcyBzdXJyb3VuZGluZyBoaW0uIEZyZWQgaXMgcXVpZXQsIHN0aWxsIHR1cm5pbmcgdGhlIGNvaW5jaWRlbmNlIG9mIGhpcyBhbmQgdGhlIGNoYWl3YWxsYSdzIHNoYXJlZCBjb25jbHVzaW9uIG92ZXIgaW4gaGlzIG1pbmQsIHZpc2libHkgcGxlYXNlZCB3aXRoIGhpbXNlbGYgYW5kIHRyeWluZyBub3QgdG8gc2hvdyBpdCB0b28gbXVjaC4KClRoZSBkZWNvZGVkIG1lc3NhZ2Ugc2l0cyBpbiB5b3VyIGNoZXN0IGxpa2Ugc29tZXRoaW5nIGZpbmFsbHkgc2V0IGRvd24gYWZ0ZXIgYmVpbmcgY2FycmllZCBhIGxvbmcgd2F5LiBDb21lIGhvbWUuIFlvdSBrbm93LCBub3csIG1vcmUgb3IgbGVzcyBleGFjdGx5IHdoZXJlIHRoYXQgaXMsIGFuZCBob3cgbXVjaCBmdXJ0aGVyIHlvdSBoYXZlIGxlZnQgdG8gZ28gdG8gZ2V0IHRoZXJlLgoKIlR3byBtb3VudGFpbnMgbGVmdCwiIHRoZSBjaGFpd2FsbGEgc2F5cywgd2F0Y2hpbmcgdGhlIGZpcmUuICJUaGVuIHRoZSBsZXR0ZXIuIFRoZW4gdGhlIGRvb3IuIiBIZSBkb2Vzbid0IHNheSBpdCBsaWtlIGEgd2FybmluZy4gSGUgc2F5cyBpdCBsaWtlIGEgbWFuIGNvdW50aW5nIGRvd24gdG8gc29tZXRoaW5nIGhlJ3MgYmVlbiB3YWl0aW5nIGEgdmVyeSBsb25nIHRpbWUgdG8gc2VlLg==',
            'choices' => [
                ['text' => 'QXNrIGhpbSBpZiBoZSdsbCBiZSB0aGVyZSBhdCB0aGUgZG9vciB0b28=', 'next' => '8_end_ask'],
                ['text' => 'TGV0IGhpbSBrZWVwIGhpcyBvd24gY291bnNlbA==', 'next' => '8_end_quiet'],
            ],
        ],

        '8_end_ask' => [
            'prose'   => 'IldpbGwgeW91IGJlIHRoZXJlPyIgeW91IGFzay4gIkF0IHRoZSBkb29yLiBBdCB0aGUgZW5kIG9mIGl0LiIKCkhlIGNvbnNpZGVycyB0aGlzIHdpdGggcmVhbCBjYXJlLCB0aGUgZmlyZWxpZ2h0IGRvaW5nIHNvbWV0aGluZyBnZW50bGUgdG8gdGhlIGxpbmVzIG9mIGhpcyBmYWNlLiAiSSBkb24ndCBrbm93IHlldCwiIGhlIHNheXMsIHdoaWNoIGlzLCB5b3UncmUgcmVhbGlzaW5nLCB0aGUgbW9zdCBob25lc3QgdGhpbmcgaGUncyBzYWlkIHRvIHlvdSBhY3Jvc3MgZXZlcnkgc2luZ2xlIG9uZSBvZiB0aGVzZSBzdHJhbmdlIG1lZXRpbmdzLiAiSSd2ZSBuZXZlciBhY3R1YWxseSBsZXQgbXlzZWxmIHRoaW5rIHRoYXQgZmFyIGFoZWFkLiBJdCBmZWx0IGxpa2UgdGVtcHRpbmcgc29tZXRoaW5nLiIKCkhlIHBvdXJzIHlvdSBtb3JlIGNoYWkgaW5zdGVhZCBvZiBhbnN3ZXJpbmcgbW9yZSBmdWxseSB0aGFuIHRoYXQuCgoiQXNrIG1lIGFnYWluIGF0IHRoZSBkb29yLCIgaGUgc2F5cy4gIkknbGwgaGF2ZSBhIGJldHRlciBhbnN3ZXIgYnkgdGhlbi4gSSB0aGluayBJIG1pZ2h0IGV2ZW4gbWVhbiBpdCBwcm9wZXJseSwgYnkgdGhlIHRpbWUgeW91IGdldCB0aGVyZS4iCgpZb3UgZG9uJ3QgcHVzaCBmdXJ0aGVyLiBTb21lIGRvb3JzLCB5b3UncmUgbGVhcm5pbmcg4oCUIGV2ZW4gZnJvbSBhIG1hbiB3aG8gbW9zdGx5IGRlYWxzIGluIHRoZSBtZXRhcGhvcmljYWwga2luZCDigJQgb3BlbiBiZXR0ZXIgaW4gdGhlaXIgb3duIHRpbWUu',
            'ending'  => true,
        ],

        '8_end_quiet' => [
            'prose'   => 'WW91IGRvbid0IGFzay4gVGhlcmUncyBzb21ldGhpbmcgaW4gdGhlIHdheSBoZSdzIHNpdHRpbmcsIHdhdGNoaW5nIHRoZSBmaXJlLCB0aGF0IHN1Z2dlc3RzIGhlJ3MgYWxyZWFkeSBhc2tpbmcgaGltc2VsZiB0aGUgc2FtZSBxdWVzdGlvbiBhbmQgZG9lc24ndCBuZWVkIHlvdXIgdmVyc2lvbiBvZiBpdCBhZGRlZCBvbiB0b3AuCgpJbnN0ZWFkIHlvdSBzaXQgd2l0aCBoaW0gYSB3aGlsZSBsb25nZXIgaW4gdGhlIHBhcnRpY3VsYXIgcXVpZXQgb2YgdHdvIHBlb3BsZSB3aG8ndmUganVzdCB3YXRjaGVkIGEgdmVyeSBsb25nIHNlbnRlbmNlIGZpbmFsbHkgY2xvc2UsIGJvdGggYXdhcmUgdGhhdCB0aGUgY2xvc2luZyBvZiBpdCBtZWFucyBzb21ldGhpbmcgaXMgcHJvcGVybHksIGZpbmFsbHkgZW5kaW5nLCBldmVuIGFzIHNvbWV0aGluZyBlbHNlIGlzIGp1c3QgYWJvdXQgdG8gYmVnaW4uCgpGcmVkIGZhbGxzIGFzbGVlcCBmaXJzdCwgaGVhZCB0dWNrZWQsIGVudGlyZWx5IHVuYm90aGVyZWQgYnkgdGhlIGVub3JtaXR5IG9mIHN0b25lcyBhcm91bmQgaGltLiBKYW1lcyBmb2xsb3dzIHNvb24gYWZ0ZXIuIFRoZSBjaGFpd2FsbGEgc3RheXMgYXdha2UgYSB3aGlsZSBsb25nZXIsIHdhdGNoaW5nIHRoZSBmaXJlLCBhbmQgeW91IGZpbmQgeW91J3JlIGNvbnRlbnQgdG8gc2ltcGx5IGV4aXN0IG5lYXIgaGltIGluIHRoZSBkYXJrIHdpdGhvdXQgZWl0aGVyIG9mIHlvdSBuZWVkaW5nIHRvIGZpbGwgaXQgd2l0aCBhbnl0aGluZyBtb3JlLgoKVHdvIG1vdW50YWlucyBsZWZ0LiBUaGVuIHRoZSBsZXR0ZXIuIFRoZW4gdGhlIGRvb3IuIFlvdSdsbCBmaW5kIG91dCB3aGF0IGhlIGRlY2lkZXMgd2hlbiB5b3UgYm90aCBnZXQgdGhlcmUg4oCUIGFuZCBmb3IgdG9uaWdodCwgdGhhdCdzIGV4YWN0bHkgZW5vdWdoIG5vdC1rbm93aW5nIHRvIGNhcnJ5IGNvbWZvcnRhYmx5Lg==',
            'ending'  => true,
        ],

    ],
];
