<?php
return [
    'id'    => 'q19',
    'title' => 'The Deep Passage',
    'color' => '#3A7A6A',

    'pages' => [
        '1_start' => [
            'prose'   => 'VGhlIGNvYXN0IGhlcmUgaXMgYWxsIHNoZWVyIGRlc2NlbnQg4oCUIGNsaWZmcyBkcm9wcGluZyBzdHJhaWdodCBpbnRvIHdhdGVyIHNvIGJsdWUgaXQgbG9va3MgbGl0IGZyb20gYmVuZWF0aCByYXRoZXIgdGhhbiBsaXQgZnJvbSBhYm92ZSwgYSBzbWFsbCBkb2NrIGNyb3dkZWQgd2l0aCBlcXVpcG1lbnQgdGhhdCBtYWtlcyBpdCBwbGFpbiB0aGlzIGlzbid0IGEgZmlzaGluZyB0b3duLCBub3QgcHJpbWFyaWx5LiBTb21ld2hlcmUgb3V0IHBhc3QgdGhlIHBvaW50LCB0aGUgc2VhYmVkIGRyb3BzIGF3YXkgZW50aXJlbHkgaW50byB3YXRlciBkZWVwIGVub3VnaCB0aGF0IHRoZSBjaGFydHMgc2ltcGx5IHN0b3AgYm90aGVyaW5nIHdpdGggbnVtYmVycy4KClRoZSBtb25hc3RlcnkgaGVyYnMgcmlkZSBpbiB5b3VyIHBhY2ssIHN0aWxsIGZyYWdyYW50LCBzdGlsbCBmYWludGx5IG1lZGljaW5hbCBldmVuIHRocm91Z2ggdGhlIGNsb3RoLiBKYW1lcyBoYXMgdGFrZW4gdG8gc2l0dGluZyB2ZXJ5IHN0aWxsIHdoZW5ldmVyIHRoZSBzZWEgaXMgbWVudGlvbmVkLCB3aGljaCB5b3UncmUgc3RhcnRpbmcgdG8gcmVhZCBhcyBmb2N1cyByYXRoZXIgdGhhbiBmZWFyLgoKQSBkaXZpbmcgYmVsbCB3YWl0cyBhdCB0aGUgZG9jayDigJQgYnJhc3MtZml0dGVkLCB0aGljay1nbGFzc2VkLCBleGFjdGx5IGFzIGltcHJvYmFibGUgYXMgaXQgc291bmRzLiBPciB0aGVyZSdzIHBhc3NhZ2Ugd2l0aCB0aGUgbG9jYWwgc2VhLWZvbGssIHdobyBrbm93IHRoaXMgc3RyZXRjaCBvZiB3YXRlciB0aGUgd2F5IGZhcm1lcnMga25vdyBhIGZpZWxkLCBhbmQgd2hvIGFyZSBhbHJlYWR5IGxvYWRpbmcgZ2VhciBvbnRvIGEgYm9hdCB0aGF0IGxvb2tzIGNvbnNpZGVyYWJseSBsZXNzIHJlYXNzdXJpbmcgdGhhbiB0aGUgYmVsbCBidXQgaGFzLCB5b3Ugc3VzcGVjdCwgbWFkZSB0aGlzIGV4YWN0IGNyb3NzaW5nIGEgdGhvdXNhbmQgdGltZXMgd2l0aG91dCBpbmNpZGVudC4=',
            'choices' => [
                ['text' => 'VGFrZSB0aGUgZGl2aW5nIGJlbGw=', 'next' => '2_bell'],
                ['text' => 'R28gd2l0aCB0aGUgc2VhLWZvbGs=', 'next' => '2_passage'],
            ],
        ],

        '2_bell' => [
            'prose'   => 'VGhlIGNhcHRhaW4gaW5zaXN0cyBvbiB0aGUgaGVyYnMgYmVmb3JlIGFueXRoaW5nIGVsc2Ug4oCUIGJyZXdlZCBzdHJvbmcsIG5vIGFyZ3VtZW50IGVudGVydGFpbmVkLCB0aGUgd2hvbGUgcHJvY2VkdXJlIGNvbmR1Y3RlZCB3aXRoIHRoZSBzZXJpb3VzbmVzcyBvZiBhIG1hbiB3aG8gaGFzIHNlZW4gd2hhdCB0aGUgZGVlcCBkb2VzIHRvIHBlb3BsZSB3aG8gZ28gZG93biB1bnByZXBhcmVkLiBGcmVkIHN1cGVydmlzZXMgdGhlIGJyZXdpbmcgd2l0aCBhbiBpbnRlbnNpdHkgdGhhdCBib3JkZXJzIG9uIGFsYXJtaW5nLCBhZGp1c3RpbmcgdGhlIGhlYXQgdHdpY2UsIHRhc3RpbmcgaXQgb25jZSwgcHJvbm91bmNpbmcgaXQgZmluYWxseSwgZ3J1ZGdpbmdseSwgYWRlcXVhdGUuCgpUaGUgYmVsbCBpdHNlbGYgaXMgY3JhbXBlZCBhbmQgY29sZCBhbmQgbGluZWQgd2l0aCBicmFzcyBmaXR0aW5ncyBnb25lIGdyZWVuIHdpdGggZGVjYWRlcyBvZiBzYWx0LiBKYW1lcyBmaW5kcyB0aGUgb25lIHdhcm0gcGF0Y2ggbmVhciB0aGUgc21hbGwgaGVhdGluZyBlbGVtZW50IGFuZCByZWZ1c2VzIHRvIG1vdmUgZnJvbSBpdCBmb3IgdGhlIGVudGlyZSBkZXNjZW50LgoKVGhlIHdhdGVyIG91dHNpZGUgdGhlIHRoaWNrIGdsYXNzIGdvZXMgZnJvbSBibHVlIHRvIGdyZWVuIHRvIGEgYmx1ZS1ibGFjayB0aGF0IHN0b3BzIGJlaW5nIGEgY29sb3VyIGF0IGFsbCBzb21ld2hlcmUgcGFzdCBhIGh1bmRyZWQgZmVldCwgYW5kIHRoZSBjYXB0YWluIGxvd2VycyB5b3Ugd2l0aCB0aGUgdW5odXJyaWVkLCBwcmFjdGljZWQgY2FsbSBvZiBzb21lb25lIHdobyBoYXMgbWFkZSB0aGlzIGV4YWN0IGRlc2NlbnQgbW9yZSB0aW1lcyB0aGFuIGhlIGNvdWxkIGNvdW50LiBJdCBpcywgYWdhaW5zdCBhbGwgZXhwZWN0YXRpb24sIGVudGlyZWx5IHBlYWNlZnVsLg==',
            'choices' => [
                ['text' => 'V2F0Y2ggdGhlIGRhcmsgcmlzZSB0byBtZWV0IHlvdQ==', 'next' => '3_seamount'],
            ],
        ],

        '2_passage' => [
            'prose'   => 'VGhlIHNlYS1mb2xrIHNoYXJlIHRoZSBoZXJicyBhcm91bmQgdGhlIGRlY2sgYXMgb3JkaW5hcnkgcHJlcGFyYXRpb24sIG5vIGNlcmVtb255IHRvIGl0IOKAlCBjb2xkLXdhdGVyIGRpdmluZywgaW4gdGhpcyB0cmFkaXRpb24sIGFwcGFyZW50bHkgcmVxdWlyZXMgZXhhY3RseSB0aGlzIGFuZCBub3RoaW5nIG1vcmUgZHJhbWF0aWMuIEZyZWQgaGFzIHN0cm9uZyBvcGluaW9ucyBhYm91dCB0aGUgYnJld2luZyB0ZW1wZXJhdHVyZSBhbmQgZXhwcmVzc2VzIGFsbCBvZiB0aGVtLCBhdCBsZW5ndGgsIHRvIGEgY3JldyB3aG8gbm9kIHBvbGl0ZWx5IGFuZCBjb250aW51ZSBkb2luZyB0aGluZ3MgdGhlaXIgb3duIHdheSByZWdhcmRsZXNzLgoKSmFtZXMsIGZvciByZWFzb25zIGtub3duIG9ubHkgdG8gaGltc2VsZiwgc3BlbmRzIHRoZSBlbnRpcmUgcHJlcGFyYXRpb24gcGVyY2hlZCBvbiBGcmVkJ3MgaGVhZCwgd2hpY2ggRnJlZCBiZWFycyB3aXRoIHRoZSBsb25nLXN1ZmZlcmluZyBkaWduaXR5IG9mIHNvbWVvbmUgd2hvIGhhcyBkZWNpZGVkIGNvbXBsYWluaW5nIGFib3V0IGl0IHdvdWxkIG9ubHkgZW5jb3VyYWdlIGZ1cnRoZXIgc2l0dGluZy4KClRoZSBjcm9zc2luZyBvdXQgdG8gb3BlbiB3YXRlciBpcyBicmlzayBhbmQgYnVzaW5lc3NsaWtlLCB0aGUgY3JldyBtb3Zpbmcgd2l0aCB0aGUgdW5ib3RoZXJlZCBjb21wZXRlbmNlIG9mIHBlb3BsZSBmb3Igd2hvbSB0aGlzIGlzIHNpbXBseSBUdWVzZGF5LiBCeSB0aGUgdGltZSB0aGUgYm9hdCBhbmNob3JzIGFib3ZlIG9wZW4gd2F0ZXIgZ29uZSBkYXJrIGJsdWUtYmxhY2sgYmVuZWF0aCB5b3UsIHlvdSd2ZSBzdG9wcGVkIGJlaW5nIG5lcnZvdXMgYW5kIHN0YXJ0ZWQsIGluc3RlYWQsIGJlaW5nIGdlbnVpbmVseSBjdXJpb3VzIGFib3V0IHdoYXQncyBkb3duIHRoZXJlLg==',
            'choices' => [
                ['text' => 'R28gZG93biBhbmQgc2Vl', 'next' => '3_seamount'],
            ],
        ],

        '3_seamount' => [
            'prose'   => 'VGhlIHNlYW1vdW50IHJpc2VzIGZyb20gdGhlIGRhcmsgYmVsb3cgbGlrZSBzb21ldGhpbmcgdGhlIG9jZWFuIGdyZXcgcmF0aGVyIHRoYW4gc29tZXRoaW5nIGl0IG1lcmVseSBjb250YWlucywgYW5kIG5lYXIgaXRzIHBlYWssIGFuY2hvcmVkIGZhc3QgYWdhaW5zdCB0aGUgY3VycmVudCwgYSBjaGVzdCDigJQgb2xkLCBzZWEtd29ybiwgdW5taXN0YWthYmx5IGdyYW5kbW90aGVyJ3MuCgpZb3UncmUgbm90IGFsb25lIGF0IGl0LgoKQSBmaWd1cmUgaXMgYWxyZWFkeSB0aGVyZSwgd29ya2luZyBhdCB0aGUgbGF0Y2ggd2l0aCB0aGUgdGlnaHQsIGNvbnRyb2xsZWQgZnJ1c3RyYXRpb24gb2Ygc29tZW9uZSB3aG8gaGFzIGJlZW4gYXQgaXQgYSB3aGlsZSBhbmQgaXMgbm90IHVzZWQgdG8gZmFpbGluZyBhdCB0aGluZ3MuIFNoZSBzZWVzIHlvdSBiZWZvcmUgeW91IGZ1bGx5IHNlZSBoZXIsIGFuZCBmb3Igb25lIGxvbmcsIHN0cmFuZ2UsIHNpbGVudCBtb21lbnQgdW5kZXJ3YXRlciDigJQgbm8gd29yZHMgcG9zc2libGUgZG93biBoZXJlLCBub3RoaW5nIGJ1dCBnZXN0dXJlIGFuZCBleHByZXNzaW9uIOKAlCB5b3UgYW5kIFBldHJhIHNpbXBseSBsb29rIGF0IGVhY2ggb3RoZXIgYWNyb3NzIHRoZSBzZWFtb3VudCwgYm90aCBlbnRpcmVseSB1bnN1cnByaXNlZCBhbmQgYm90aCwgc29tZWhvdywgZXhhY3RseSB3aGVyZSB5b3Ugd2VyZSBhbHdheXMgZ29pbmcgdG8gZW5kIHVwLgoKU2hlIGdlc3R1cmVzIGF0IHRoZSBsYXRjaC4gTm90IHByb3VkIGVub3VnaCwgYXBwYXJlbnRseSwgdG8ga2VlcCBzdHJ1Z2dsaW5nIHdpdGggaXQgYWxvbmUgd2hpbGUgeW91IHdhdGNoLg==',
            'choices' => [
                ['text' => 'U3dpbSBvdmVyIGFuZCB0cnkgaXQgdG9nZXRoZXI=', 'next' => '4_latch'],
            ],
            'terminal' => true,
        ],

        '4_latch' => [
            'prose'   => 'Rm91ciBoYW5kcyB3b3JrIGJldHRlciB0aGFuIHR3bywgaXQgdHVybnMgb3V0LCBldmVuIG9uIGEgbWVjaGFuaXNtIHRoaXMgc21hbGwg4oCUIHNoZSBob2xkcyB0aGUgY2hlc3Qgc3RlYWR5IHdoaWxlIHlvdSB3b3JrIHRoZSBpbnRlcmxvY2tlZCBwaWVjZXMsIHRoZSB0d28gb2YgeW91IGZhbGxpbmcgaW50byBhIHdvcmRsZXNzIHJoeXRobSBuZWl0aGVyIG9mIHlvdSBjb3VsZCBoYXZlIHBsYW5uZWQsIGNvbW11bmljYXRpbmcgZXZlcnl0aGluZyBpbiBnbGFuY2VzIGFuZCBzbWFsbCBhZGp1c3RtZW50cyBvZiBncmlwLgoKSXQgcmVzb2x2ZXMgdGhlIHdheSBpdCBhbHdheXMgZG9lcyBub3csIGFsbCBhdCBvbmNlLCB0aGUgcGFydGljdWxhciBjbGljayBvZiBzb21ldGhpbmcgdGhhdCB3YXMgYWx3YXlzIGdvaW5nIHRvIG9wZW4uCgpJbnNpZGU6IFNxdWFyZSAjMTksIGEgd2hhbGUgd29ya2VkIGluIGRlZXAgYmx1ZS1ibGFjayB0aHJlYWQsIHNtYWxsIHBvaW50cyBvZiBwYWxlIHNpbHZlciBzdGl0Y2hlZCB0aHJvdWdoIHRoZSB3YXRlciBhcm91bmQgaXQgbGlrZSBzb21ldGhpbmcgY2F1Z2h0IG1pZC1nbG93LiBBbmQgZm9sZGVkIGJlbmVhdGggaXQsIHRoZSBub3RlIOKAlCB0aGUgc2FtZSBvbmUsIHdvcmQgZm9yIHdvcmQsIHRoYXQgeW91IHJlYWQgaW4gdGhlIG1vbmFzdGVyeSBjcnlwdC4KCiJUaGUgbGFzdCB0aHJlZSBhcmUgdG9nZXRoZXIuIFRoZXkgd2FpdCBhdCB0aGUgYmVnaW5uaW5nLiIKClBldHJhIHJlYWRzIGl0IGFnYWluIGFueXdheSwgbW91dGhpbmcgdGhlIHdvcmRzIGJlaGluZCBoZXIgbWFzaywgYW5kIHlvdSB1bmRlcnN0YW5kLCB3YXRjaGluZyBoZXIsIHRoYXQgc2hlJ3MgcmVhZCBpdCBlbm91Z2ggdGltZXMgbm93IHRvIGhhdmUgaXQgbWVtb3Jpc2VkIGFuZCBzdGlsbCBuZWVkcyB0byBzZWUgaXQgYWdhaW4gcmVnYXJkbGVzcy4=',
            'choices' => [
                ['text' => 'SGVhZCBiYWNrIHVwIHRvZ2V0aGVy', 'next' => '5_surface'],
            ],
        ],

        '5_surface' => [
            'prose'   => 'WW91IHN1cmZhY2UgdG9nZXRoZXIsIHRyZWFkaW5nIHdhdGVyIGluIHRoZSBzdWRkZW4gYnJpZ2h0bmVzcyBhZnRlciBhbGwgdGhhdCBibHVlLWJsYWNrIGRhcmssIGJvdGggZ2FzcGluZyBhIGxpdHRsZSwgYm90aCBncmlubmluZyBiZWZvcmUgZWl0aGVyIG9mIHlvdSBtZWFucyB0by4KClBldHJhIGxhdWdocyBmaXJzdCDigJQgcHJvcGVybHksIHVuZ3VhcmRlZCwgYSBzb3VuZCB5b3UgaGF2ZW4ndCBoZWFyZCBmcm9tIGhlciBvbmNlIGluIHRoaXMgd2hvbGUgbG9uZywgY2FyZWZ1bCBhY3F1YWludGFuY2Ug4oCUIGFuZCB5b3UgbGF1Z2ggYmFjayBiZWZvcmUgeW91J3ZlIGRlY2lkZWQgdG8sIHRoZSB0d28gb2YgeW91IGJvYmJpbmcgaW4gb3BlbiB3YXRlciB3aXRoIG1hdGNoaW5nIHNxdWFyZXMgZm9sZGVkIHNhZmUgaW4geW91ciBiYWdzIGFuZCBhYnNvbHV0ZWx5IG5vdGhpbmcgc2Vuc2libGUgbGVmdCB0byBzYXkgYWJvdXQgYW55IG9mIGl0LgoKIkkgY291bGRuJ3QgZ2V0IGl0IG9wZW4sIiBzaGUgYWRtaXRzLCBvbmNlIHNoZSdzIGdvdCBoZXIgYnJlYXRoIGJhY2suICJXZWVrcy4gSSBjYW1lIGJhY2sgdHdpY2UuIiBTaGUgZG9lc24ndCBzb3VuZCBlbWJhcnJhc3NlZCBhYm91dCBpdCwgd2hpY2ggaXRzZWxmIGZlZWxzIG5ldy4gIkkgdGhpbmsgaXQgd2FudGVkIGJvdGggb2YgdXMuIgoKU29tZXRoaW5nIGluIGhvdyBzaGUgc2F5cyBpdCBsYW5kcyBkaWZmZXJlbnRseSB0aGFuIGFueXRoaW5nIHNoZSdzIHNhaWQgYmVmb3JlLiBOb3QgYSBjb25jZXNzaW9uLiBKdXN0IGEgZmFjdCwgZmluYWxseSBzcG9rZW4gcGxhaW5seSwgYmV0d2VlbiB0d28gcGVvcGxlIHdobyd2ZSBzdG9wcGVkIG5lZWRpbmcgdG8gYmUgY2FyZWZ1bCB3aXRoIGVhY2ggb3RoZXIu',
            'choices' => [
                ['text' => 'Q2xpbWIgYmFjayBhYm9hcmQ=', 'next' => '6_coral'],
            ],
        ],

        '6_coral' => [
            'prose'   => 'QmFjayBvbiB0aGUgdmVzc2VsLCB3cmFwcGVkIGluIGJsYW5rZXRzIGFuZCBjb25zaWRlcmFibHkgd2FybWVyLCBGcmVkIG1ha2VzIGFuIGVub3Jtb3VzIGZ1c3Mgb3ZlciBzb21ldGhpbmcgd2VkZ2VkIGludG8gdGhlIGNoZXN0J3Mgb2xkIHJvcGUgYmluZGluZyDigJQgYSBzbWFsbCBrbm90IG9mIGNvcmFsLCBwYWxlIGFuZCBicmFuY2hpbmcsIGNsZWFybHkgYW5jaWVudC4KCiJDYXJ5b3BoeWxsaWEgc21pdGhpaSwiIGhlIGFubm91bmNlcywgdHVybmluZyBpdCBpbiB0aGUgbGlnaHQuICJHcm93cyBhdCByb3VnaGx5IG9uZSBtaWxsaW1ldHJlIGEgeWVhci4iIEhlIGRvZXMgdGhlIGFyaXRobWV0aWMgYWxvdWQsIHNsb3dseSwgZm9yIGVmZmVjdC4gIlRoaXMgcGllY2UgaXMgYXQgbGVhc3QgdHdvIGh1bmRyZWQgeWVhcnMgb2xkLiBTb21lb25lIGFuY2hvcmVkIHRoYXQgY2hlc3QgYSB2ZXJ5IGxvbmcgdGltZSBhZ28g4oCUIG9yIGl0IHNpbXBseSBkcmlmdGVkIHRoZXJlIGFuZCBmb3VuZCBpdHMgb3duIHJlc3RpbmcgcGxhY2UsIHdoaWNoIEkgZmluZCwgaG9uZXN0bHksIGFsbW9zdCBtb3JlIG1vdmluZy4iCgpIZSB3cmFwcyBpdCB3aXRoIHJlYWwgY2FyZS4gIk1hcmluZSBiaW9sb2d5IGlzbid0IHN0cmljdGx5IG15IGFyZWEsIiBoZSBhZGRzLCBzb21ld2hhdCBncnVkZ2luZ2x5LCAiYnV0IEknbSBwcmVwYXJlZCB0byBtYWtlIGFuIGV4Y2VwdGlvbi4iCgpQZXRyYSwgZHJ5aW5nIG9mZiBuZWFyYnksIHdhdGNoZXMgaGltIHdvcmsgd2l0aCBhbiBleHByZXNzaW9uIHlvdSBoYXZlbid0IHNlZW4gb24gaGVyIGJlZm9yZSDigJQgc29tZXRoaW5nIGNsb3NlciB0byBmb25kbmVzcyB0aGFuIHRoZSB3YXJ5IHRvbGVyYW5jZSBzaGUncyBzaG93biBoaW0gdW50aWwgbm93Lg==',
            'choices' => [
                ['text' => 'SGVhZCBpbiB0byB0aGUgY29hc3QgY2FtcA==', 'next' => '7_evening'],
            ],
        ],

        '7_evening' => [
            'prose'   => 'VGhlIGNhcHRhaW4gZmVlZHMgeW91IGhvdCBzb3VwIG9uIHRoZSBkZWNrIGJlZm9yZSB5b3UndmUgZXZlbiBwcm9wZXJseSBmaW5pc2hlZCBkcnlpbmcgb2ZmLCBhbmQgb25jZSB5b3UncmUgYmFjayBhdCB0aGUgY29hc3QgY2FtcCB0aGF0IGV2ZW5pbmcsIHNvbWVvbmUgcHJvZHVjZXMgZ2luZ2VyIGJlZXIgYW5kIGEgZmlyZSBhbmQgdGhlIHBhcnRpY3VsYXIgZWFzZSBvZiBwZW9wbGUgd2hvJ3ZlIHN1cnZpdmVkIHNvbWV0aGluZyB0b2dldGhlciwgaG93ZXZlciBzbWFsbC4KCkphbWVzIGhhcyBpbnN0YWxsZWQgaGltc2VsZiBvbiBGcmVkJ3MgaGVhZCBhZ2FpbiwgYXBwYXJlbnRseSBhIHByZWZlcnJlZCBwZXJjaCBub3csIGFuZCBzaG93cyBubyBzaWduIG9mIHJlbG9jYXRpbmcgZGVzcGl0ZSBGcmVkJ3Mgb25nb2luZywgaW5jcmVhc2luZ2x5IHRoZWF0cmljYWwgY29tbWVudGFyeSBvbiBiaW9sdW1pbmVzY2VuY2UsIHdoaWNoIEphbWVzIGlzIHZlcnkgY2xlYXJseSBub3QgbGlzdGVuaW5nIHRvIGFuZCBoYXMsIGVxdWFsbHkgY2xlYXJseSwgbm8gaW50ZW50aW9uIG9mIG1vdmluZyBhd2F5IGZyb20uCgpQZXRyYSBzaXRzIGFjcm9zcyB0aGUgZmlyZSBmcm9tIHlvdSwgY29yYWwtcGllY2Ugc3RvcmllcyBhbmQgcnVuZSBmcmFnbWVudHMgc3ByZWFkIGxvb3NlbHkgYmV0d2VlbiB5b3Ugbm93IGluc3RlYWQgb2YgZ3VhcmRlZCwgdGhlIHR3byBvZiB5b3UgY29tcGFyaW5nIG5vdGVzIHByb3Blcmx5IGZvciB0aGUgZmlyc3QgdGltZSB3aXRob3V0IGVpdGhlciBvbmUgaG9sZGluZyBhbnl0aGluZyBjYXJlZnVsbHkgYmFjay4KCiJJIHNob3VsZCB0ZWxsIHlvdSB3aGF0IEkga25vdyBhYm91dCB0aGUgbGFzdCBwYXJ0LCIgc2hlIHNheXMgZXZlbnR1YWxseSwgd2F0Y2hpbmcgdGhlIGZpcmUgcmF0aGVyIHRoYW4geW91LiAiSWYgeW91IHdhbnQgdG8gaGVhciBpdC4i',
            'choices' => [
                ['text' => 'WWVzIOKAlCB0ZWxsIG1lIGV2ZXJ5dGhpbmc=', 'next' => '8_end_share'],
                ['text' => 'Tm90IHRvbmlnaHQg4oCUIGp1c3Qgc2l0IGJ5IHRoZSBmaXJl', 'next' => '8_end_fire'],
            ],
        ],

        '8_end_share' => [
            'prose'   => 'WW91IGRvIHdhbnQgdG8gaGVhciBpdCwgYW5kIHNoZSB0ZWxscyB5b3Ug4oCUIG5vdCBldmVyeXRoaW5nLCBub3QgeWV0LCBidXQgbW9yZSB0aGFuIHNoZSdzIHRvbGQgYW55b25lIG9uIHRoaXMgd2hvbGUgcm9hZCwgdGhlIHBpZWNlcyBzaGUncyBiZWVuIHF1aWV0bHkgYXNzZW1ibGluZyBzaW5jZSB0aGUgY3J5c3RhbCBjaGFtYmVyLCBsYWlkIG91dCBub3cgd2l0aG91dCB0aGUgb2xkIGNhcmVmdWwgZWRnZXMgYXJvdW5kIHRoZW0uCgpJdCBpc24ndCBhIGZ1bGwgcGljdHVyZS4gVGhlcmUgYXJlIHN0aWxsIGdhcHMsIHRoaW5ncyBzaGUncyBob2xkaW5nIGJhY2sgb3V0IG9mIGhhYml0IG1vcmUgdGhhbiBzdHJhdGVneSBhdCB0aGlzIHBvaW50LCB5b3Ugc3VzcGVjdC4gQnV0IGl0J3MgcmVhbCBpbmZvcm1hdGlvbiwgZnJlZWx5IGdpdmVuLCBhbmQgc29tZXdoZXJlIGluIHRoZSB0ZWxsaW5nIHlvdSByZWFsaXNlIHlvdSd2ZSBzdG9wcGVkIGtlZXBpbmcgc2NvcmUgb2Ygd2hvJ3MgYWhlYWQuCgpUaGUgZmlyZSBidXJucyBsb3cuIEZyZWQgaGFzIGZhbGxlbiBhc2xlZXAgbWlkLWxlY3R1cmUsIEphbWVzIHN0aWxsIHRyaXVtcGhhbnRseSBwZXJjaGVkIG9uIGhpcyBoZWFkLiBTb21ld2hlcmUgYmVoaW5kIHlvdSBib3RoLCB0aGUgc2VhIGtlZXBzIGRvaW5nIHdoYXQgaXQncyBhbHdheXMgZG9uZSwgcGF0aWVudCBhbmQgZW5vcm1vdXMgYW5kIGVudGlyZWx5IHVuYm90aGVyZWQgYnkgdGhlIHNtYWxsLCBzaWduaWZpY2FudCB0aGluZyB0aGF0IGhhcHBlbmVkIGluIGl0IHRvZGF5LgoKIldlJ3JlIG5vdCBkb2luZyB0aGlzIHNlcGFyYXRlbHkgYW55bW9yZSwiIFBldHJhIHNheXMsIG5vdCBxdWl0ZSBhIHF1ZXN0aW9uLCBpbnRvIHRoZSBsYXN0IG9mIHRoZSBmaXJlLiBZb3UgZmluZCB5b3UgYWdyZWUgd2l0aG91dCBuZWVkaW5nIHRvIHRoaW5rIGFib3V0IGl0Lg==',
            'ending'  => true,
        ],

        '8_end_fire' => [
            'prose'   => 'Ik5vdCB0b25pZ2h0LCIgeW91IHNheSwgYW5kIHNoZSBub2RzLCBlYXN5IGFib3V0IGl0LCBubyBvZmZlbmNlIHRha2VuLiAiSnVzdCBzaXQgYnkgdGhlIGZpcmUuIgoKU28geW91IGRvIOKAlCB0aGUgdHdvIG9mIHlvdSwgYW5kIHRoZSBmaXJlLCBhbmQgRnJlZCdzIG9uZ29pbmcgbGVjdHVyZSB0aGF0IG5laXRoZXIgb2YgeW91IGlzIHJlYWxseSBmb2xsb3dpbmcsIGFuZCBKYW1lcyB0cml1bXBoYW50IG9uIEZyZWQncyBoZWFkLCBhbmQgdGhlIHNlYSBzb21ld2hlcmUgYmVoaW5kIHlvdSBhbGwsIGNhbG0gbm93LCBob2xkaW5nIGl0cyB0d28taHVuZHJlZC15ZWFyLW9sZCBjb3JhbCBhbmQgaXRzIGFuY2llbnQgY2hlc3RzIGFuZCB3aGF0ZXZlciBlbHNlIGl0J3Mgc3RpbGwga2VlcGluZyBmb3IgbGF0ZXIuCgpUaGVyZSB3aWxsIGJlIHRpbWUgZm9yIHRoZSByZXN0IG9mIGl0LiBZb3UgY2FuIGJvdGggZmVlbCB0aGF0LCB3aXRob3V0IGVpdGhlciBvZiB5b3Ugc2F5aW5nIHNvIOKAlCB0aGUgb2xkIHVyZ2VuY3kgdG8gZ2V0IGFoZWFkLCB0byBrbm93IG1vcmUsIHRvIGFycml2ZSBmaXJzdCwgaGFzIHF1aWV0bHkgZ29uZSBvdXQgb2YgdGhlIGV2ZW5pbmcsIHJlcGxhY2VkIGJ5IHNvbWV0aGluZyBjYWxtZXIgYW5kIGNvbnNpZGVyYWJseSBoYXJkZXIgdG8gbmFtZS4KClBldHJhIHBva2VzIHRoZSBmaXJlIG9uY2UsIHVubmVjZXNzYXJpbHksIGp1c3QgdG8gaGF2ZSBzb21ldGhpbmcgdG8gZG8gd2l0aCBoZXIgaGFuZHMuIE5laXRoZXIgb2YgeW91IG1vdmVzIHRvIGxlYXZlIGl0LiBGb3IgdG9uaWdodCwgdGhhdCdzIHRoZSB3aG9sZSBvZiB3aGF0IG5lZWRzIHNheWluZy4=',
            'ending'  => true,
        ],

    ],
];
