<?php
return [
    'id'    => 'q16',
    'title' => 'The Underground River',
    'color' => '#2A8070',

    'pages' => [
        '1_start' => [
            'prose'   => 'VGhlIGNhdmUgbW91dGggc3dhbGxvd3MgZGF5bGlnaHQgaW4gb25lIGNsZWFuIGJpdGUg4oCUIHlvdSBzdGVwIGZyb20gZ3JlZW4gaGVhdCBpbnRvIGNvb2wgZGFyayBzbyB0b3RhbCBpdCB0YWtlcyBhIGZ1bGwgbWludXRlIGZvciB5b3VyIGV5ZXMgdG8gYWRtaXQgdGhlcmUncyBub3RoaW5nIG1vcmUgdG8gc2VlLiBTb21ld2hlcmUgYWhlYWQsIHdhdGVyIG1vdmVzIGFnYWluc3Qgc3RvbmUgd2l0aCB0aGUgcGF0aWVudCBzb3VuZCBvZiBzb21ldGhpbmcgdGhhdCBoYXMgbmV2ZXIgb25jZSBiZWVuIGluIGEgaHVycnkuCgpUaGUgdmluZSBjdXR0aW5nIHJpZGVzIGluIGl0cyBkYW1wIGNsb3RoLCB0dWNrZWQgYWdhaW5zdCB5b3VyIGNoZXN0IHdoZXJlIGl0J3Mgc3RheWVkIHdhcm0gYW5kLCBhZ2FpbnN0IGFsbCByZWFzb25hYmxlIGV4cGVjdGF0aW9uLCBhbGl2ZSDigJQgU2F5YSdzIHBhcnRpbmcgZ2lmdCwgc3RpbGwgYm91bmQgYXQgdGhlIGN1dCBlbmQsIGEgc2luZ2xlIHBhbGUgdGhyZWFkIG9mIG5ldyBncm93dGgganVzdCB2aXNpYmxlIGlmIHlvdSBsb29rIGNsb3NlbHkgZW5vdWdoLgoKVGhvbWFzLCB0aGUgcml2ZXIgZ3VpZGUsIGlzIHdhaXRpbmcgd2l0aCBhIG5hcnJvdyB3b29kZW4gYm9hdCBhbmQgYSBzaW5nbGUgbGFudGVybiwgb3Ig4oCUIGlmIHlvdSdkIHJhdGhlciBrZWVwIHlvdXIgZmVldCB1bmRlciB5b3Ug4oCUIGEgc3RvbmUgbGVkZ2UgcnVubmluZyB0aGUgbGVuZ3RoIG9mIHRoZSBwYXNzYWdlLCBzbGljayBidXQgd2Fsa2FibGUsIGZvciB0aG9zZSB3aG8gdHJ1c3Qgcm9jayBtb3JlIHRoYW4gd2F0ZXIgaW4gdGhlIGRhcmsu',
            'choices' => [
                ['text' => 'VGFrZSB0aGUgYm9hdA==', 'next' => '2_boat'],
                ['text' => 'V2FsayB0aGUgbGVkZ2U=', 'next' => '2_ledge'],
            ],
        ],

        '2_boat' => [
            'prose'   => 'VGhvbWFzIHBvbGVzIHRoZSBib2F0IGZvcndhcmQgd2l0aCB0aGUgdW5odXJyaWVkIGVjb25vbXkgb2Ygc29tZW9uZSB3aG8gaGFzIG1hZGUgdGhpcyBleGFjdCBjcm9zc2luZyBtb3JlIHRpbWVzIHRoYW4gaGUgY291bGQgY291bnQsIHRoZSBsYW50ZXJuIHRocm93aW5nIG9uZSBzbWFsbCBjaXJjbGUgb2YgbGlnaHQgdGhhdCBzZWVtcywgYWZ0ZXIgYSB3aGlsZSwgbGlrZSB0aGUgb25seSB0cnVlIHRoaW5nIGxlZnQgaW4gdGhlIHdvcmxkLiBKYW1lcyBzaXRzIHJpZ2lkIGluIHRoZSBib3csIGV5ZXMgZW5vcm1vdXMsIHdhdGNoaW5nIHRoZSBibGFjayB3YXRlciB3aXRob3V0IGJsaW5raW5nLCBmb3Igb25jZSBlbnRpcmVseSB3aXRob3V0IGNvbXBsYWludCBhYm91dCBpdC4KClNvbWV3aGVyZSBpbiB0aGF0IGZpcnN0IGhvdXIsIHlvdSBub3RpY2UgdGhlIHZpbmUgY3V0dGluZyBoYXMgY2hhbmdlZC4gQSB0aGluIHdoaXRlIHJvb3QsIG5vIGxvbmdlciB0aGFuIGEgZmluZ2VybmFpbCwgaGFzIHB1c2hlZCBvdXQgZnJvbSB0aGUgY3V0IGVuZCBhbmQgdHVybmVkIOKAlCBub3QgZG93biwgbm90IGFsb25nIHRoZSBib2F0J3MgZHJpZnQsIGJ1dCB0b3dhcmQgdGhlIGRhcmsgb24geW91ciBsZWZ0LCBzdGVhZHkgYXMgYSBjb21wYXNzIG5lZWRsZSBmaW5kaW5nIG5vcnRoLgoKRnJlZCBob2xkcyB0aGUgbGFudGVybiBjbG9zZSB0byBsb29rLiAiVGhpcyBzcGVjaWVzIGZvbGxvd3MgdW5kZXJncm91bmQgd2F0ZXIsIiBoZSBzYXlzIHNsb3dseS4gIkl0J3MgYmVlbiBncm93aW5nIHRvd2FyZCBzb21ldGhpbmcuIFRvd2FyZCB0aGUgZGVlcGVzdCB3YXRlciBpdCBjYW4gc2Vuc2UuIiBIZSB0dXJucyB0byBsb29rIHdoZXJlIHRoZSByb290IHBvaW50cywgaW50byBkYXJrbmVzcyB0aGF0IFRob21hcywgd2l0aG91dCBiZWluZyBhc2tlZCwgaXMgYWxyZWFkeSBzdGVlcmluZyB5b3UgdG93YXJkLiAiSSBiZWxpZXZlLCIgRnJlZCBzYXlzLCB3aXRoIHRoZSBwYXJ0aWN1bGFyIHNhdGlzZmFjdGlvbiBvZiBhIG1hbiBhYm91dCB0byBiZSByaWdodCwgIndlIGFyZSBiZWluZyBsZWQgc29tZXdoZXJlLiI=',
            'choices' => [
                ['text' => 'Rm9sbG93IHdoZXJlIHRoZSByb290IHBvaW50cw==', 'next' => '3_island'],
            ],
        ],

        '2_ledge' => [
            'prose'   => 'VGhlIGxlZGdlIGlzIG5hcnJvdyBhbmQgY29sZCB1bmRlcmZvb3QsIHNsaWNrIGluIHBhdGNoZXMgdGhhdCBtYWtlIHlvdSBncmF0ZWZ1bCBmb3IgZXZlcnkgaGFuZGhvbGQgdGhlIHN0b25lIG9mZmVycy4gRnJlZCBmbGllcyBhaGVhZCBpbiBzaG9ydCBidXJzdHMsIGFubm91bmNpbmcgZHJvcC1vZmZzIGJlZm9yZSB5b3UgcmVhY2ggdGhlbSwgd2hpY2ggeW91J3ZlIGRlY2lkZWQgdG8gYmUgZ3JhdGVmdWwgZm9yIHJhdGhlciB0aGFuIGFubm95ZWQgYnkuCgpJdCdzIG9uIGEgcmVzdCBzdG9wLCBjcm91Y2hlZCBhZ2FpbnN0IHRoZSByb2NrIHdpdGggdGhlIGxhbnRlcm4gYmV0d2VlbiB5b3UsIHRoYXQgeW91IG5vdGljZSB0aGUgdmluZSBjdXR0aW5nIGhhcyBiZWd1biB0byByb290IOKAlCBhIHNpbmdsZSBwYWxlIHRocmVhZCBwdXNoaW5nIGZyb20gdGhlIGN1dCBlbmQsIHR1cm5lZCB1bm1pc3Rha2FibHkgdG93YXJkIHRoZSB3YXRlciByYXRoZXIgdGhhbiBhbG9uZyB0aGUgbGVkZ2UgeW91J3ZlIGJlZW4gZm9sbG93aW5nLgoKRnJlZCBleGFtaW5lcyBpdCB3aXRoIHJlYWwgYXR0ZW50aW9uLiAiVGhpcyBzcGVjaWVzIGZvbGxvd3MgdW5kZXJncm91bmQgd2F0ZXIsIiBoZSBzYXlzLiAiSXQgZG9lc24ndCBjYXJlIHdoaWNoIHdheSBpcyBjb252ZW5pZW50IGZvciB3YWxraW5nLiBJdCBvbmx5IGNhcmVzIHdoZXJlIHRoZSB3YXRlciBydW5zIGRlZXBlc3QuIiBIZSBsb29rcyBvdXQgYWNyb3NzIHRoZSBibGFjayBsYWtlIGJlc2lkZSB5b3UsIHRvIGEgc2hhcGUgeW91IGhhZG4ndCBub3RpY2VkIHVudGlsIGhlIHBvaW50ZWQgYXQgaXQg4oCUIHBhbGUsIGxvdywgdW5taXN0YWthYmx5IGFuIGlzbGFuZC4gIkl0J3MgcG9pbnRpbmcgYXQgdGhhdCwiIGhlIHNheXMuICJJdCdzIGFsd2F5cyBwb2ludGluZyBhdCB0aGF0LiIgSGUgaXMsIHlvdSd2ZSBsZWFybmVkLCBhbHdheXMgcmlnaHQgYWJvdXQgdGhpcyBzb3J0IG9mIHRoaW5nLg==',
            'choices' => [
                ['text' => 'SGVhZCBmb3IgdGhlIGlzbGFuZA==', 'next' => '3_island'],
            ],
        ],

        '3_island' => [
            'prose'   => 'VGhlIGxha2Ugd2lkZW5zIGhlcmUgaW50byBzb21ldGhpbmcgY2xvc2VyIHRvIGEgY2F2ZXJuIHRoYW4gYSByaXZlciwgYmxhY2sgd2F0ZXIgc3RyZXRjaGluZyBmdXJ0aGVyIHRoYW4gdGhlIGxhbnRlcm4gY2FuIHByb3Blcmx5IGxpZ2h0LCBhbmQgaW4gdGhlIG1pZGRsZSBvZiBpdCwgZXhhY3RseSB3aGVyZSB0aGUgcm9vdCBwb2ludGVkLCBhIHNtYWxsIGlzbGFuZCByaXNlcyBwYWxlIGFuZCBiYXJlIGZyb20gdGhlIHdhdGVyIOKAlCBub3QgbXVjaCBiaWdnZXIgdGhhbiBhIHJvb20sIHJpbmdlZCB3aXRoIHN0b25lIHdvcm4gc21vb3RoIGJ5IGNlbnR1cmllcyBvZiBhIGxha2UgdGhhdCBuZXZlciBxdWl0ZSBmbG9vZHMgaXQgYW5kIG5ldmVyIHF1aXRlIGxlYXZlcyBpdCBkcnkuCgpUaG9tYXMgYnJpbmdzIHRoZSBib2F0IGFsb25nc2lkZSB3aXRob3V0IG5lZWRpbmcgdG8gYmUgdG9sZCB3aGVyZSB0byBhaW0uCgpPbiB0aGUgaXNsYW5kLCB1bm1pc3Rha2FibGUgZXZlbiBpbiBsYW50ZXJuLWxpZ2h0OiBhIGNoZXN0LCBoYWxmLXN1bmsgaW50byB0aGUgcGFsZSByb2NrIGFzIHRob3VnaCB0aGUgaXNsYW5kIGhhZCBncm93biB1cCBhcm91bmQgaXQgcmF0aGVyIHRoYW4gdGhlIG90aGVyIHdheSByb3VuZC4KCllvdSBjbGltYiBvdXQuIFRoZSBzdG9uZSBpcyBjb2xkIGFuZCBzdHJhbmdlIHVuZGVyIHlvdXIgaGFuZHMsIGFuZCBzb21ld2hlcmUgYWJvdmUgeW91LCBoaWdoIGluIHRoZSBkYXJrLCBzb21ldGhpbmcgaXMgY2FydmVkIGludG8gdGhlIGNhdmUgY2VpbGluZyB0aGF0IHRoZSBsYW50ZXJuIGhhc24ndCBmb3VuZCB5ZXQu',
            'choices' => [
                ['text' => 'S25lZWwgZG93biBhbmQgYmVnaW4=', 'next' => '4_chest'],
            ],
            'terminal' => true,
        ],

        '4_chest' => [
            'prose'   => 'WW91ciBoYW5kcyBrbm93IHRoZSBsYXRjaCBiZWZvcmUgeW91ciBtaW5kIGZ1bGx5IGNhdGNoZXMgdXAg4oCUIHNtYWxsIGludGVybG9ja2VkIHBpZWNlcywgZWFjaCBvbmUgd2FpdGluZyBvbiB0aGUgbGFzdCwgdGhlIHNhbWUgbWVjaGFuaXNtIGZyb20gdGhlIG1vdW50YWluIHNocmluZSBhbGwgdGhvc2UgbW9udGhzIGFnbywgZXhjZXB0IHRoaXMgdGltZSB5b3VyIGZpbmdlcnMgbW92ZSB3aXRob3V0IGhlc2l0YXRpb24sIHdpdGhvdXQgdGhlIGxvbmcgY29sZCBtaW51dGVzIG9mIHRyaWFsIGl0IHRvb2sgdGhlIGZpcnN0IHRpbWUuCgpJdCByZXNvbHZlcyBhbG1vc3QgYmVmb3JlIHlvdSd2ZSBwcm9wZXJseSBzdGFydGVkLCB0aGUgc2FtZSBwYXJ0aWN1bGFyIGNsaWNrIG9mIHNvbWV0aGluZyB0aGF0IHdhcyBhbHdheXMgZ29pbmcgdG8gb3Blbi4gWW91IHNpdCBiYWNrLCBmYWludGx5IHN1cnByaXNlZCBhdCB5b3Vyc2VsZi4KCkluc2lkZTogU3F1YXJlICMxNiwgYSBzbWFsbCBib2F0IG9uIGJsYWNrIHdhdGVyIHdvcmtlZCBpbiBzaWx2ZXItZ3JleSB0aHJlYWQsIGEgc2luZ2xlIHBvaW50IG9mIGdvbGQgbWFya2luZyBhIGxhbnRlcm4gdGhhdCBzZWVtcywgd2hlbiB5b3UgdGlsdCBpdCB0byB0aGUgbGlnaHQsIHRvIGFjdHVhbGx5IGNhdGNoIGFuZCBob2xkIHRoZSBnbG93IGZvciBhIG1vbWVudCBiZWZvcmUgcmVsZWFzaW5nIGl0LgoKVGhvbWFzLCB3YXRjaGluZyBmcm9tIHRoZSBib2F0LCBzYXlzIG5vdGhpbmcgYWJvdXQgdGhlIGxhdGNoIOKAlCBidXQgdGhlcmUncyBzb21ldGhpbmcgaW4gdGhlIHNldCBvZiBoaXMgc2hvdWxkZXJzIHRoYXQgc3VnZ2VzdHMgaGUncyBzZWVuIHRoaXMgcGFydGljdWxhciBraW5kIG9mIHF1aWV0IGNvbXBldGVuY2UgYXJyaXZlIGluIHNvbWVvbmUgYmVmb3JlLCBhIGxvbmcgdGltZSBhZ28sIG9uIHRoaXMgZXhhY3QgaXNsYW5kLg==',
            'choices' => [
                ['text' => 'TG9vayB1cCBhdCB0aGUgY2VpbGluZw==', 'next' => '5_ceiling'],
            ],
        ],

        '5_ceiling' => [
            'prose'   => 'IkhvbGQgdGhlIGxhbnRlcm4gdXAsIiBUaG9tYXMgc2F5cywgYW5kIHlvdSBkbywgYW5kIHRoZSBjZWlsaW5nIGFib3ZlIHRoZSBpc2xhbmQgcmVzb2x2ZXMgb3V0IG9mIHRoZSBkYXJrIOKAlCBhIHJ1bmUsIGRlZXAtY2FydmVkLCBmYXIgaGlnaGVyIHRoYW4gYW55IGhhbmQgY291bGQgcmVhY2ggc3RhbmRpbmcgb24gdGhlIGlzbGFuZCBhbG9uZS4KCiJBbiBvbGRlciB3b21hbiBwYWlkIG1lIHdlbGwgZm9yIGFuIGFmdGVybm9vbidzIHdvcmssIHRoaXJ0eS1zb21lIHllYXJzIGJhY2ssIiBUaG9tYXMgc2F5cywgbm90IHF1aXRlIGxvb2tpbmcgYXQgeW91LCB3YXRjaGluZyB0aGUgbWFyayBpbnN0ZWFkIGxpa2UgaXQgc3RpbGwgc3VycHJpc2VzIGhpbS4gIldhbnRlZCB0byByZWFjaCB0aGF0IHNwb3QgZXhhY3RseS4gSSB3YXMgdHdlbnR5LXRocmVlLCBzdHJvbmcgZW5vdWdoLCBhbmQgc2hlIGp1c3Qg4oCUIGNsaW1iZWQgdXAuIFN0b29kIG9uIG15IHNob3VsZGVycyBpbiB0aGUgbWlkZGxlIG9mIGFuIHVuZGVyZ3JvdW5kIGxha2UgbGlrZSBpdCB3YXMgdGhlIG1vc3QgcmVhc29uYWJsZSByZXF1ZXN0IGFueW9uZSBoYWQgZXZlciBtYWRlIG9mIG1lLiIgSGUgc2hha2VzIGhpcyBoZWFkIHNsb3dseS4gIkkndmUgdG9sZCB0aGF0IHN0b3J5IGF0IGV2ZXJ5IGNhbXBmaXJlIHNpbmNlLiBOb2JvZHkgZXZlciBiZWxpZXZlcyB0aGUgd2hvbGUgb2YgaXQuIEknbSBub3Qgc3VyZSBJIGRvLCBzb21lIG5pZ2h0cy4iCgpUaGUgcnVuZSBpdHNlbGYgaXMgZGVlcCBhbmQgc3VyZSwgY3V0IGJ5IGEgaGFuZCB0aGF0IGNsZWFybHkgd2Fzbid0IHNoYWtpbmcgZGVzcGl0ZSB0aGUgcG9zaXRpb24gaXQgbXVzdCBoYXZlIGJlZW4gY2FydmVkIGZyb20uIFlvdSBmaW5kIHlvdSBiZWxpZXZlIGV2ZXJ5IHdvcmQgb2YgVGhvbWFzJ3Mgc3Rvcnkgd2l0aG91dCBuZWVkaW5nIGNvbnZpbmNpbmcgYXQgYWxsLg==',
            'choices' => [
                ['text' => 'SGVhZCBiYWNrIGFjcm9zcyB0aGUgd2F0ZXI=', 'next' => '6_moss'],
            ],
        ],

        '6_moss' => [
            'prose'   => 'T24gdGhlIHBhZGRsZSBiYWNrIGFjcm9zcyB0aGUgYmxhY2sgd2F0ZXIsIEZyZWQgYnVzaWVzIGhpbXNlbGYgd2l0aCBzb21ldGhpbmcgYXQgdGhlIGNhdmUgd2FsbCBuZWFyIHRoZSB3YXRlcmxpbmUg4oCUIGEgcGF0Y2ggb2YgcGFsZSBtb3NzLCBkYW1wIGFuZCBmYWludGx5IGx1bWlub3VzIGluIHRoZSBsYW50ZXJuIGxpZ2h0LCB3aGljaCBoZSBoYXJ2ZXN0cyB3aXRoIG1vcmUgY2FyZSB0aGFuIHlvdSdkIGV4cGVjdCBmb3Igc29tZXRoaW5nIGdyb3dpbmcgd2lsZCBpbiBhIGNhdmUuCgpIZSBwYWNrcyBpdCBpbnRvIGEgc21hbGwgZGFtcCBwb3VjaCwgd3JhcHMgaXQgdHdpY2UsIGFuZCBoYW5kcyBpdCB0byB5b3Ugd2l0aG91dCBtdWNoIGNlcmVtb255LgoKIkV4dHJlbWVseSByYXJlLCIgaGUgc2F5cy4gIk1lZGljaW5hbGx5IHNpZ25pZmljYW50LCBpbiB0aGUgcmlnaHQgaGFuZHMuIiBIZSBkb2Vzbid0IHNheSB3aG9zZSBoYW5kcyB0aG9zZSBtaWdodCBiZS4gIlRoZSByaWdodCBwZXJzb24gd2lsbCBiZSB2ZXJ5IGdsYWQgdG8gcmVjZWl2ZSB0aGlzLiIgSGUgc2F5cyBpdCB0aGUgd2F5IGhlIHNheXMgbW9zdCB0aGluZ3MgaGUncyBub3QgeWV0IHJlYWR5IHRvIGZ1bGx5IGV4cGxhaW4g4oCUIGNvbmZpZGVudCwgY2VydGFpbiwgYW5kIGNvbXBsZXRlbHkgdW5mb3J0aGNvbWluZyBhYm91dCB0aGUgZGV0YWlscy4gWW91J3ZlIGxlYXJuZWQsIGJ5IG5vdywgbm90IHRvIHByZXNzIGhpbSB3aGVuIGhlIGdldHMgbGlrZSB0aGlzLiBIZSdzIHVzdWFsbHkgc2F2aW5nIHNvbWV0aGluZy4=',
            'choices' => [
                ['text' => 'TWFrZSBmb3IgdGhlIGZhciBjYW1w', 'next' => '7_camp'],
            ],
        ],

        '7_camp' => [
            'prose'   => 'VGhlIGZhciBzaWRlIG9mIHRoZSBjYXZlIG9wZW5zIGludG8gYSBwcm9wZXIgY2FtcCDigJQgYSBmaXJlIHNvbWVvbmUncyB0ZW5kZWQgZm9yIHllYXJzLCBibGFja2VuZWQgc3RvbmVzLCBhIHBvdCB0aGF0IFRob21hcyBmaWxscyB3aXRob3V0IGFza2luZyB3aGV0aGVyIHlvdSdyZSBodW5ncnksIHdoaWNoIGJ5IG5vdyB5b3UgcmVjb2duaXplIGFzIHNpbXBseSBob3cgdGhlIGdvb2Qgb25lcyBvcGVyYXRlLgoKU291cCwgdGhpY2sgd2l0aCBzb21ldGhpbmcgcm9vdC12ZWdldGFibGUgYW5kIHVuZmFtaWxpYXIsIHRhc3RlcyBiZXR0ZXIgdGhhbiBpdCBoYXMgYW55IHJpZ2h0IHRvIGFmdGVyIGEgZGF5IHNwZW50IG1vc3RseSBjb2xkIGFuZCBtb3N0bHkgdW5kZXJncm91bmQuIEphbWVzLCBkcmllZCBhbmQgd2FybSwgY2xhaW1zIHRoZSBzcG90IG5lYXJlc3QgdGhlIGZpcmUgYW5kIGRvZXNuJ3QgbW92ZSBhZ2Fpbi4KCiJBbm90aGVyIG9uZSBvZiB5b3UgY2FtZSB0aHJvdWdoLCBtb250aHMgYmFjaywiIFRob21hcyBzYXlzLCBoYWxmd2F5IHRocm91Z2ggaGlzIG93biBib3dsLCBjb252ZXJzYXRpb25hbCByYXRoZXIgdGhhbiBkcmFtYXRpYyBhYm91dCBpdC4gIllvdW5nZXIuIFNoYXJwZXIsIG1heWJlIOKAlCBrbmV3IGV4YWN0bHkgd2hhdCBzaGUgd2FudGVkIGJlZm9yZSBzaGUnZCBldmVuIHByb3Blcmx5IGFycml2ZWQuIERpZG4ndCBsaW5nZXIgdGhlIHdheSB5b3UgaGF2ZS4iIEhlIHNocnVncy4gIkRpZmZlcmVudCBwZW9wbGUgY3Jvc3MgdGhpcyBjYXZlIGRpZmZlcmVudCB3YXlzLiBOZWl0aGVyJ3Mgd3JvbmcuIgoKWW91IHRoaW5rIG9mIFBldHJhLCBzb21ld2hlcmUgYWhlYWQgb2YgeW91IG9uIHRoZSByb2FkLCBtb3ZpbmcgZmFzdCwgYW5kIGZpbmQgdGhlIHRob3VnaHQgZG9lc24ndCBzdGluZyB0aGUgd2F5IGl0IG9uY2Ugd291bGQgaGF2ZS4KClRoZSBmaXJlIGJ1cm5zIGxvdy4gVGhvbWFzIGRvZXNuJ3Qgc2VlbSBpbiBhbnkgaHVycnkgdG8gc2VlIHlvdSBvZmYsIGFuZCBvdXQgcGFzdCB0aGUgY2F2ZSBtb3V0aCwgdGhlIG9yZGluYXJ5IG5pZ2h0IGlzIHNldHRsaW5nIGluIG92ZXIgd2F0ZXIgYW5kIHJvb3Qgc3lzdGVtcyBhbmQgZXZlcnl0aGluZyBlbHNlIHRoZSBkYXkgaGFzIHF1aWV0bHkgdW50YW5nbGVkLgoKWW91IGNvdWxkIGFzayBUaG9tYXMgbW9yZSBhYm91dCB0aGUgeWVhcnMgc2luY2Ug4oCUIHdoYXQgaGFwcGVuZWQgdG8gdGhlIGJveSB3aG8gc3Rvb2QgdW5kZXJncm91bmQgd2l0aCBhIHN0cmFuZ2VyIG9uIGhpcyBzaG91bGRlcnMuIE9yIHlvdSBjb3VsZCBsZXQgdGhlIHN0b3J5IHN0YXkgZXhhY3RseSB0aGUgc2l6ZSBpdCBhbHJlYWR5IGlzLCBjb21wbGV0ZSBhbmQgd2VsbC10b2xkLCBhbmQgbGV0IHRoZSBldmVuaW5nIGJlIHNpbXBsZS4=',
            'choices' => [
                ['text' => 'QXNrIHdoYXQgdGhlIHllYXJzIHNpbmNlIGhhdmUgYmVlbiBsaWtl', 'next' => '8_end_years'],
                ['text' => 'TGV0IHRoZSBldmVuaW5nIHN0YXkgc2ltcGxl', 'next' => '8_end_simple'],
            ],
        ],

        '8_end_years' => [
            'prose'   => 'VGhvbWFzIGNvbnNpZGVycyB0aGUgcXVlc3Rpb24gd2l0aCB0aGUgc2FtZSB1bmh1cnJpZWQgY2FyZSBoZSBicmluZ3MgdG8gcG9saW5nIGEgYm9hdCB0aHJvdWdoIGFic29sdXRlIGRhcmsuCgoiSSBzdGF5ZWQsIiBoZSBzYXlzIGV2ZW50dWFsbHkuICJHdWlkZWQgdGhpcyByaXZlciBteSB3aG9sZSBsaWZlLCBtb3JlIG9yIGxlc3MuIE1hcnJpZWQsIGhhZCBjaGlsZHJlbiB3aG8gdGhpbmsgdGhpcyBjYXZlIGlzIHRoZSBtb3N0IGJvcmluZyBwbGFjZSBvbiBlYXJ0aCBiZWNhdXNlIGl0J3MganVzdCBEYWQncyB3b3JrLiBCdXJpZWQgbXkgZmF0aGVyIGhlcmUgdHdvIHdpbnRlcnMgYmFjayDigJQgdGhlcmUncyBhIHNwb3QgbmVhciB0aGUgZW50cmFuY2Ugd2hlcmUgdGhlIGFjb3VzdGljcyBhcmUgZ29vZCwgYW5kIHdlIHNhbmcuIiBIZSBsb29rcyBhdCB0aGUgd2F0ZXIuICJJIHRoaW5rIGFib3V0IGhlciBzb21ldGltZXMuIFlvdXIgZ3JhbmRtb3RoZXIuIFdvbmRlciBpZiBzaGUga25ldyB3aGF0IGFuIGFmdGVybm9vbidzIHN0cmFuZ2UgcmVxdWVzdCB3b3VsZCB0dXJuIGludG8sIGRlY2FkZXMgb24sIHN0aWxsIGJlaW5nIHRvbGQgYXQgdGhpcyBleGFjdCBmaXJlLiIKCiJJIHRoaW5rIHNoZSdkIGhhdmUgbGlrZWQga25vd2luZywiIHlvdSBzYXksIGFuZCBtZWFuIGl0LgoKIkkgdGhpbmsgc28gdG9vLCIgaGUgc2F5cywgYW5kIGZvciBhIG1vbWVudCBuZWl0aGVyIG9mIHlvdSBuZWVkcyB0byBzYXkgYW55dGhpbmcgZWxzZS4gVGhlIGZpcmUgaG9sZHMgaXRzIHNoYXBlLCBvcmRpbmFyeSBhbmQgd2FybSwgYW5kIHNvbWV3aGVyZSBiZWhpbmQgeW91IHRoZSBpc2xhbmQga2VlcHMgaXRzIHJ1bmUgaW4gdGhlIGRhcmssIHBhdGllbnQgdGhlIHdheSBzdG9uZSBpcyBwYXRpZW50LCB3YWl0aW5nIGZvciB3aG9ldmVyIG5lZWRzIGl0IHRvbGQgbmV4dC4=',
            'ending'  => true,
        ],

        '8_end_simple' => [
            'prose'   => 'WW91IGRvbid0IGFzay4gU29tZSBzdG9yaWVzIGFyZSBhbHJlYWR5IGV4YWN0bHkgdGhlIHJpZ2h0IHNpemUsIGFuZCBwdWxsaW5nIGF0IHRoZSBlZGdlcyBvZiBhIGdvb2Qgb25lIHJhcmVseSBpbXByb3ZlcyBpdC4KClRob21hcyBzZWVtcyB0byB1bmRlcnN0YW5kIHRoaXMgd2l0aG91dCBuZWVkaW5nIGl0IGV4cGxhaW5lZCDigJQgaGUgc2ltcGx5IGJhbmtzIHRoZSBmaXJlLCBvZmZlcnMgeW91IHRoZSBkcmllc3QgY29ybmVyIG9mIHRoZSBjYW1wIGZvciB0aGUgbmlnaHQsIGFuZCBnb2VzIGJhY2sgdG8gbWVuZGluZyBhIG5ldCB3aXRoIHRoZSB1bmh1cnJpZWQgYXR0ZW50aW9uIG9mIGEgbWFuIHdobyBoYXMgbmV2ZXIgb25jZSBiZWVuIGJvcmVkIGJ5IGhpcyBvd24gbGlmZS4KCllvdSBsaWUgYXdha2UgYSB3aGlsZSBsaXN0ZW5pbmcgdG8gd2F0ZXIgeW91IGNhbid0IHNlZSBtb3Zpbmcgc29tZXdoZXJlIGNsb3NlIGJ5LCB0aGUgY2F2ZSBtb3NzIHBvdWNoIHR1Y2tlZCBzYWZlIGJlc2lkZSB0aGUgc3F1YXJlLCB0aGUgdmluZSBjdXR0aW5nIOKAlCByb290bGVzcyBub3csIGl0cyB3b3JrIGRvbmUg4oCUIHJlc3RpbmcgaW4gaXRzIGRhbXAgY2xvdGggbGlrZSBzb21ldGhpbmcgdGhhdCBrbm93cyBpdCB3aWxsIGJlIHBsYW50ZWQgc29tZXdoZXJlIGdyZWVuIGJlZm9yZSB0b28gbG9uZy4KCkFib3ZlIHlvdSwgaW1wb3NzaWJseSBmYXIgYWJvdmUsIHRoZSBydW5lIGtlZXBzIGl0cyBzaGFwZSBpbiB0aGUgZGFyay4gSXQgZG9lc24ndCBuZWVkIGFuIGF1ZGllbmNlIHRvIG1lYW4gd2hhdCBpdCBtZWFucy4gU29tZSB0aGluZ3MsIHlvdSdyZSBsZWFybmluZywgYXJlIHRydWUgd2hldGhlciBvciBub3QgYW55b25lJ3MgdGhlcmUgdG8gcmVhZCB0aGVtLgoKWW91IHNsZWVwIGJldHRlciB0aGFuIHlvdSBoYXZlIGluIGRheXMsIHVuZGVyZ3JvdW5kLCBpbiB0aGUgZGFyaywgZW50aXJlbHkgdW5hZnJhaWQu',
            'ending'  => true,
        ],

    ],
];
