<?php
return [
    'id'    => 'q20',
    'title' => 'The Mountain of Her Youth',
    'color' => '#5A5A7A',

    'pages' => [
        '1_start' => [
            'prose'   => 'VGhlIG1vdW50YWluIHJpc2VzIHRoZSB3YXkgaG9tZSBtb3VudGFpbnMgYWx3YXlzIHNlZW0gdG8g4oCUIG5vdCB0aGUgdGFsbGVzdCB5b3UndmUgc2Vlbiwgbm90IHRoZSBtb3N0IGRyYW1hdGljLCBidXQgc29tZWhvdyBtb3JlIGluc2lzdGVudGx5IHJlYWwgdGhhbiBhbnkgb2YgdGhlIG90aGVycywgbGFyY2hlcyBkYXJrIGdyZWVuIGFnYWluc3QgZ3JleSBzY3JlZSwgYSBzY2F0dGVyaW5nIG9mIGZhcm1ob3VzZXMgbG93ZXIgZG93biB3aGVyZSB0aGUgc2xvcGUgZmluYWxseSBhZ3JlZXMgdG8gYmUgZ2VudGxlLgoKU29tZXdoZXJlIHVwIHRoZXJlLCBpbiBhIGhvdXNlIHlvdSBoYXZlbid0IHNlZW4geWV0LCBpcyB0aGUgcm9vbSB3aGVyZSBncmFuZG1vdGhlciB3YXMgYSBjaGlsZCBiZWZvcmUgc2hlIHdhcyBhbnl0aGluZyBlbHNlIOKAlCBiZWZvcmUgdGhlIHF1aWx0LCBiZWZvcmUgdGhlIGxldHRlcnMsIGJlZm9yZSBhbnkgb2YgdGhlIHZlcnNpb24gb2YgaGVyIHlvdSd2ZSBzcGVudCB0aGlzIHdob2xlIGpvdXJuZXkgYXNzZW1ibGluZyBwaWVjZSBieSBwaWVjZS4KClRoZSBzZWFtb3VudCBjb3JhbCByaWRlcyB3cmFwcGVkIGluIEZyZWQncyBjYXJlZnVsIHBhY2tpbmcsIHR3byBodW5kcmVkIHllYXJzIG9sZCBhbmQgZW50aXJlbHkgdW5ib3RoZXJlZCBieSB0aGUgY2hhbmdlIGluIGFsdGl0dWRlLiBKYW1lcyBoYXMgZ29uZSBxdWlldCBpbiB0aGUgcGFydGljdWxhciB3YXkgdGhhdCBzdWdnZXN0cyBoZSB1bmRlcnN0YW5kcywgc29tZWhvdywgdGhhdCB0aGlzIHN0b3AgbWF0dGVycyBkaWZmZXJlbnRseSB0aGFuIHRoZSBvdGhlcnMuCgpBIHRyYWNrIHdpbmRzIHVwIHBhc3QgYW4gb2xkIG1pbGwgYW5kIHRocm91Z2ggYSBzdGFuZCBvZiBsYXJjaGVzLCBncmFuZG1vdGhlcidzIG93biBjaGlsZGhvb2QgcGF0aCBieSBldmVyeSBhY2NvdW50IHlvdSd2ZSBnYXRoZXJlZC4gT3IgYSBwcm9wZXIgcm9hZCBjbGltYnMgbW9zdCBvZiB0aGUgd2F5IG5vdywgZmFzdGVyLCBvcmRpbmFyeSwgYnVpbHQgbG9uZyBhZnRlciBzaGUgbGVmdC4=',
            'choices' => [
                ['text' => 'VGFrZSBncmFuZG1vdGhlcidzIGNoaWxkaG9vZCBwYXRo', 'next' => '2_path'],
                ['text' => 'VGFrZSB0aGUgbW9kZXJuIHJvYWQ=', 'next' => '2_road'],
            ],
        ],

        '2_path' => [
            'prose'   => 'VGhlIHBhdGggY2xpbWJzIHBhc3QgYSBtaWxsIHdoZWVsIGdvbmUgc3RpbGwgYW5kIGdyZWVuIHdpdGggbW9zcywgdGhyb3VnaCBsYXJjaGVzIHRoYXQgbXVzdCBoYXZlIGJlZW4geW91bmcgdHJlZXMgdGhlbXNlbHZlcyB3aGVuIGdyYW5kbW90aGVyIGxhc3Qgd2Fsa2VkIHVuZGVyIHRoZW0sIGFuZCBhcm91bmQgdGhlIHNob3VsZGVyIG9mIHRoZSBwZWFrIHRvIGEgZmFybWhvdXNlIHRoYXQgbG9va3MgbGlrZSBpdCBncmV3IG91dCBvZiB0aGUgbW91bnRhaW4gcmF0aGVyIHRoYW4gYmVpbmcgYnVpbHQgb24gaXQuCgpBbiBvbGQgd29tYW4gaXMgYWxyZWFkeSBvdXRzaWRlIHdoZW4geW91IGFycml2ZSwgYXMgdGhvdWdoIHNoZSdkIGhlYXJkIHlvdSBjb21pbmcgZnJvbSBmdXJ0aGVyIGF3YXkgdGhhbiBzZWVtcyBwb3NzaWJsZS4gV2hlbiB0aGUgY29udmVyc2F0aW9uIHR1cm5zIOKAlCBhcyBpdCBkb2VzLCBxdWlja2x5IOKAlCB0byBncmFuZG1vdGhlcidzIGZvbmRuZXNzIGZvciBmYXJhd2F5IHRoaW5ncywgeW91IHNob3cgaGVyIHRoZSBjb3JhbC4KClNoZSBnb2VzIHZlcnkgcXVpZXQsIHR1cm5pbmcgaXQgb3ZlciBpbiBoYW5kcyBnb25lIHNvZnQgYW5kIHNwb3R0ZWQgd2l0aCBhZ2UuCgoiU2hlIHNlbnQgbWUgYSBsZXR0ZXIgYWJvdXQgYSBwaWVjZSBsaWtlIHRoaXMsIiBzaGUgc2F5cyBmaW5hbGx5LiAiU2FpZCBzaGUnZCBsZWZ0IGl0IGluIHRoZSB3YXRlciBmb3Igd2hvZXZlciBjYW1lIGxvb2tpbmcgbmV4dC4iIFNoZSBsb29rcyB1cCBhdCB5b3UgcHJvcGVybHkgZm9yIHRoZSBmaXJzdCB0aW1lLiAiVGhhdCB3YXMgbWVhbnQgZm9yIHlvdS4i',
            'choices' => [
                ['text' => 'R28gaW4gd2l0aCBoZXI=', 'next' => '3_ester'],
            ],
        ],

        '2_road' => [
            'prose'   => 'VGhlIG1vZGVybiByb2FkIGNsaW1icyBzdGVhZGlseSwgdW5yZW1hcmthYmxlLCBidWlsdCBsb25nIGFmdGVyIGdyYW5kbW90aGVyIHdvdWxkIGhhdmUgd2Fsa2VkIHRoaXMgZ3JvdW5kIG9uIGZvb3Qg4oCUIGZhc3RlciwgY2VydGFpbmx5LCBidXQgeW91IGZpbmQgeW91cnNlbGYgd2lzaGluZywgbW9yZSB0aGFuIG9uY2UsIHRoYXQgeW91J2QgdGFrZW4gdGhlIHNsb3dlciB3YXkgaW5zdGVhZC4KClRoZSBmYXJtaG91c2UgYXQgdGhlIHRvcCBsb29rcyBleGFjdGx5IGFzIG9sZCBhcyBldmVyeXRoaW5nIGFyb3VuZCBpdCwgYW5kIHRoZSB3b21hbiB3aG8gbWVldHMgeW91IGF0IHRoZSBkb29yIGlzIHNoYXJwLWV5ZWQgYW5kIGVudGlyZWx5IHVuc3VycHJpc2VkIGJ5IHlvdXIgYXJyaXZhbC4KCldoZW4geW91IHByb2R1Y2UgdGhlIGNvcmFsLCBzaGUgc3R1ZGllcyBpdCBhIGxvbmcgbW9tZW50LiAiSSBrbm93IHRoYXQgY29yYWwsIiBzaGUgc2F5cy4gIlNoZSBkcmV3IGl0IGluIGEgbGV0dGVyIG9uY2UuIFNhaWQgc2hlJ2QgcHV0IGl0IHNvbWV3aGVyZSBpdCB3b3VsZCB3YWl0LiIgU2hlIGRpc2FwcGVhcnMgaW5zaWRlIGFuZCByZXR1cm5zIHdpdGggYW4gb2xkIHRpbiwgd29ybiBzb2Z0IGF0IHRoZSBjb3JuZXJzLCBhbmQgaW5zaWRlIGl0LCBhIGxldHRlciB3aXRoIGEgY2FyZWZ1bCBpbmsgc2tldGNoOiB0aGUgY29yYWwsIGV4YWN0IGluIGV2ZXJ5IGJyYW5jaCBhbmQga25vdC4KCiJTaGUgYWx3YXlzIGRpZCBkcmF3IHRoaW5ncyBwcm9wZXJseSwiIHRoZSB3b21hbiBzYXlzLCBzb21ldGhpbmcgZm9uZCBhbmQgYSBsaXR0bGUgc2FkIGluIGl0Lg==',
            'choices' => [
                ['text' => 'R28gaW4gd2l0aCBoZXI=', 'next' => '3_ester'],
            ],
        ],

        '3_ester' => [
            'prose'   => 'IkknbSBFc3RlciwiIHNoZSBzYXlzLCBzZXR0aW5nIHRoZSBrZXR0bGUgb24gYmVmb3JlIHlvdSd2ZSBldmVuIHByb3Blcmx5IGludHJvZHVjZWQgeW91cnNlbGYuICJJJ3ZlIGJlZW4gZXhwZWN0aW5nIHNvbWVvbmUgZm9yIHNpeHR5IHllYXJzLCBvbiBhbmQgb2ZmLiBJJ2Qgc3RhcnRlZCB0byB3b25kZXIgaWYgSSdkIG1pc2p1ZGdlZCB0aGUgdGltaW5nLiIKClNoZSBnb2VzIGluc2lkZSB3aXRob3V0IGZ1cnRoZXIgY2VyZW1vbnkgYW5kIGNvbWVzIGJhY2sgaG9sZGluZyBTcXVhcmUgIzIwIOKAlCBhIHlvdW5nIHdvbWFuIG9uIGEgbW91bnRhaW4gcGF0aCwgbG9va2luZyBvdXR3YXJkLCBzdGl0Y2hlZCBpbiB0aHJlYWRzIHRoYXQgaGF2ZSBnb25lIHNsaWdodGx5IHNvZnQgd2l0aCBhZ2UgYnV0IGxvc3Qgbm9uZSBvZiB0aGVpciBjb2xvdXIuCgoiU2hlIHNhaWQgc29tZW9uZSB3b3VsZCBjb21lLCIgRXN0ZXIgc2F5cywgcHJlc3NpbmcgaXQgaW50byB5b3VyIGhhbmRzLiAiSSd2ZSBiZWVuIGtlZXBpbmcgdGhpcyBhIGxvbmcgdGltZS4gSSdtIHBsZWFzZWQsIGhvbmVzdGx5LCB0byBzdGlsbCBoYXZlIHRoZSB0YXNrLiBBIHBlcnNvbiBsaWtlcyB0byBmZWVsIHVzZWZ1bCwgYXQgbXkgYWdlLCBhbmQgdGhpcyBoYXMgYmVlbiBhIHZlcnkgZ29vZCB3YXkgdG8gZmVlbCBpdC4iCgpTaGUncyBlaWdodHktbmluZSwgc2hlIHRlbGxzIHlvdSBwbGFpbmx5IHdoZW4geW91IGFzaywgYW5kIGVudGlyZWx5IHVuYm90aGVyZWQgYnkgdGhlIG51bWJlci4=',
            'choices' => [
                ['text' => 'QXNrIGhlciB0byB0ZWxsIHlvdSBhYm91dCBncmFuZG1vdGhlciBhcyBhIGdpcmw=', 'next' => '4_stories'],
            ],
        ],

        '4_stories' => [
            'prose'   => 'RXN0ZXIgdGFsa3MgZm9yIGEgbG9uZyB3aGlsZSwgdW5odXJyaWVkLCB0aGUga2V0dGxlIHJlZmlsbGVkIHR3aWNlLCB0aGUgbGlnaHQgb3V0c2lkZSBnb2luZyBnb2xkIGFuZCB0aGVuIGdyZXkuCgoiSSBrbmV3IGhlciBhdCBlaWdodCwiIHNoZSBzYXlzLiAiU2tpbm55IHRoaW5nLCBhbHdheXMgc29tZXdoZXJlIHNoZSB3YXNuJ3Qgc3VwcG9zZWQgdG8gYmUuIEF0IHR3ZWx2ZSBzaGUgd2FzIGFscmVhZHkgdGFsa2luZyBhYm91dCBldmVyeXdoZXJlIHNoZSBtZWFudCB0byBnby4gQXQgc2V2ZW50ZWVuLCB0aGUgc3VtbWVyIHNoZSBmaW5hbGx5IGxlZnQsIEkgcmVtZW1iZXIgdGhpbmtpbmc6IG9mIGNvdXJzZS4gT2YgY291cnNlIGl0J3Mgbm93LiBTaGUnZCBiZWVuIGxlYXZpbmcgaGVyIHdob2xlIGNoaWxkaG9vZCwgcmVhbGx5IOKAlCB0aGUgYWN0dWFsIHdhbGtpbmcgYXdheSB3YXMganVzdCB0aGUgbGFzdCBiaXQgb2YgYSBtdWNoIGxvbmdlciBkZWNpc2lvbi4iCgpTaGUncyBxdWlldCBhIG1vbWVudCwgbG9va2luZyBhdCB0aGUgbW91bnRhaW4gdGhyb3VnaCB0aGUgd2luZG93LgoKIlNoZSB3ZW50IG91dHdhcmQsIiBFc3RlciBzYXlzLiAiSGVyIHNpc3RlciB3ZW50IGlud2FyZC4gVGhhdCB3YXMgYWx3YXlzIHRoZSBkaWZmZXJlbmNlIGJldHdlZW4gdGhlbSwgZXZlbiBhcyBnaXJscy4gSSBsb3ZlZCB0aGVtIGJvdGguIEkgbmV2ZXIgdW5kZXJzdG9vZCB3aHkgdGhhdCBoYWQgdG8gbWVhbiBjaG9vc2luZy4iCgpUaGUgZXZlbmluZyBzZXR0bGVzIGZ1bGx5IGRhcmsgYXJvdW5kIHRoZSBmYXJtaG91c2UuIFRoZXJlJ3MgYSBncmVhdCBkZWFsIG1vcmUsIHlvdSBzZW5zZSwgdGhhdCBFc3RlciBpc24ndCBmaW5pc2hlZCB0ZWxsaW5nIOKAlCBidXQgbW9ybmluZywgc2hlIHNheXMsIHdpbGwgZG8ganVzdCBhcyB3ZWxsIGZvciB0aGUgcmVzdCBvZiBpdC4=',
            'choices' => [
                ['text' => 'U2xlZXAsIGFuZCBsZXQgbW9ybmluZyBjb21l', 'next' => '5_petra_letters'],
            ],
            'terminal' => true,
        ],

        '5_petra_letters' => [
            'prose'   => 'UGV0cmEgYXJyaXZlcyB0aGUgbmV4dCBtb3JuaW5nLCB1bmFubm91bmNlZCBidXQgc29tZWhvdyBlbnRpcmVseSBleHBlY3RlZCwgYW5kIEVzdGVyIGdyZWV0cyBoZXIgYXQgdGhlIGRvb3Igd2l0aCB0aGUgc2FtZSB1bnN1cnByaXNlZCB3YXJtdGggc2hlIGdhdmUgeW91LCBhcyB0aG91Z2ggc2hlJ2Qgc2ltcGx5IGJlZW4gd2FpdGluZyBmb3IgdGhlIHNlY29uZCBoYWxmIG9mIGEgcGFpci4KClNoZSBnaXZlcyBQZXRyYSBoZXIgc3F1YXJlIHdpdGhvdXQgY2VyZW1vbnkuIFRoZW4gc2hlIGRpc2FwcGVhcnMgaW5zaWRlIGFuZCBjb21lcyBiYWNrIHdpdGggc29tZXRoaW5nIGVsc2Ug4oCUIGEgc21hbGwgYnVuZGxlIG9mIGxldHRlcnMsIHRpZWQgd2l0aCBhZ2Utc29mdGVuZWQgc3RyaW5nLCBhZGRyZXNzZWQgaW4gZ3JhbmRtb3RoZXIncyB1bm1pc3Rha2FibGUgaGFuZCB0byBhIG5hbWUgdGhhdCBtdXN0IGJlIHRoZSBzaXN0ZXIncy4KCiJUaGVzZSBhcmUgZm9yIHlvdSwiIEVzdGVyIHRlbGxzIFBldHJhLiAiTm90IGZvciB0aGUgcXVpbHQuIFlvdXIgZ3JhbmRtb3RoZXIgd3JvdGUgdGhlbSB0byBoZXIgc2lzdGVyLCBvdmVyIHRoZSB5ZWFycywgYW5kIGFza2VkIG1lIHRvIGtlZXAgdGhlbSBpbiBjYXNlIHRoZXkgd2VyZSBldmVyIG5lZWRlZCBmb3IgdGhlIG1lbmRpbmcgcmF0aGVyIHRoYW4gdGhlIGdyaWV2aW5nLiIgU2hlIGxvb2tzIGJldHdlZW4gdGhlIHR3byBvZiB5b3UuICJJJ3ZlIGhlbGQgdGhlbSBzaXh0eSB5ZWFycyBob3BpbmcgSSdkIG5ldmVyIGFjdHVhbGx5IGhhdmUgdG8gaGFuZCB0aGVtIG92ZXIg4oCUIHRoYXQgd291bGQgaGF2ZSBtZWFudCB0aGUgbWVuZGluZyBoYXBwZW5lZCB3aXRob3V0IHRoZW0uIEJ1dCBoZXJlIHlvdSBhcmUuIFNvIGhlcmUgdGhleSBhcmUuIgoKUGV0cmEgdGFrZXMgdGhlIGJ1bmRsZSBjYXJlZnVsbHksIGFuZCBmb3IgYSBsb25nIG1vbWVudCBzYXlzIG5vdGhpbmcgYXQgYWxsLCB0dXJuaW5nIHRoZW0gb3ZlciB0aGUgd2F5IHlvdSdkIHR1cm4gb3ZlciBzb21ldGhpbmcgeW91IHdlcmVuJ3QgcXVpdGUgc3VyZSB5b3Ugd2VyZSByZWFkeSB0byBob2xkLg==',
            'choices' => [
                ['text' => 'V2FsayB0aGUgY2hpbGRob29kIHBhdGggdG9nZXRoZXI=', 'next' => '6_flower'],
            ],
        ],

        '6_flower' => [
            'prose'   => 'TGF0ZXIsIHdhbGtpbmcgdGhlIGNoaWxkaG9vZCBwYXRoIHByb3Blcmx5IHRvZ2V0aGVyIOKAlCBhbGwgZm91ciBvZiB5b3Ugbm93LCBFc3RlciBsZWFkaW5nIGF0IGEgcGFjZSB0aGF0IG1ha2VzIGNsZWFyIHNoZSdzIHdhbGtlZCB0aGlzIGV4YWN0IGdyb3VuZCBtb3JlIHRpbWVzIHRoYW4gYW55b25lIGNvdWxkIGNvdW50IOKAlCBzaGUgc3RvcHMgdG8gcGljayBhIHNtYWxsIG1vdW50YWluIGZsb3dlciB3aXRob3V0IGJyZWFraW5nIHN0cmlkZSwgcHJlc3NpbmcgaXQgZmxhdCBiZXR3ZWVuIGhlciBmaW5nZXJzIG91dCBvZiB3aGF0IGxvb2tzIGxpa2UgcHVyZSBoYWJpdC4KCiJTaGUgZGlkIHRoaXMgb24gZXZlcnkgd2FsaywiIEVzdGVyIHNheXMsIGhhbmRpbmcgaXQgb3Zlci4gIkkgYWx3YXlzIHRob3VnaHQgaXQgd2FzIGp1c3QgYSB0aGluZyBzaGUgZGlkIHdpdGggaGVyIGhhbmRzLiBJIGRpZG4ndCB1bmRlcnN0YW5kLCB1bnRpbCB0aGlzIHdob2xlIGJ1c2luZXNzIHdpdGggdGhlIHF1aWx0LCB0aGF0IHNoZSB3YXMgYWN0dWFsbHkgd29ya2luZy4iCgpGcmVkIHRha2VzIHRoZSBmbG93ZXIgYW5kIGdvZXMgdmVyeSBzdGlsbCwgY2hlY2tpbmcgaXQgYWdhaW5zdCBzb21ldGhpbmcgaW4gaGlzIG1lbW9yeSBiZWZvcmUgaGUgc2F5cyBhIHdvcmQuCgoiVGhpcyBpcyB0aGUgc2FtZSBnZW51cywiIGhlIHNheXMgc2xvd2x5LCAiYXMgdGhlIHNwZWNpZXMgc2hlIG5hbWVkIGF0IHRoZSBmYWlyLiBUaGUgaGlsbCBmb3JtLiBUaGlzIGlzIHRoZSBtb3VudGFpbiBmb3JtIOKAlCB0aGUgb3JpZ2luYWwuIiBIZSBsb29rcyB1cCBhdCB0aGUgcGVhayBwcm9wZXJseSwgdW5kZXJzdGFuZGluZyBhcnJpdmluZyBhbGwgYXQgb25jZS4gIlNoZSBuYW1lZCB0aGUgaGlsbCBzcGVjaWVzIGFmdGVyIGhlcnNlbGYsIGluIGEgd2F5LiBBZnRlciB0aGUgcGxhY2Ugc2hlIGNob3NlIGluc3RlYWQgb2YgdGhpcyBvbmUuIFNoZSBjb3VsZG4ndCBjb21lIGJhY2sgdG8gdGhlIG1vdW50YWluLCBzbyBzaGUgbmFtZWQgc29tZXRoaW5nIGFmdGVyIHRoZSBwbGFjZSBzaGUgd2VudCB0byBpbnN0ZWFkLiIKCkhlIHByZXNzZXMgdGhlIGZsb3dlciBpbnRvIHRoZSBib3RhbmljYWwgYm9vaywgbmV4dCB0byBpdHMgaGlsbC1mb3JtIGNvdXNpbiwgYW5kIGRvZXNuJ3Qgc2F5IGFueXRoaW5nIGVsc2UgZm9yIGEgbG9uZyB3aGlsZS4gWW91IHN1c3BlY3QsIHdhdGNoaW5nIGhpbSwgdGhhdCB0aGlzIGlzIHRoZSBwcm91ZGVzdCBoZSdzIGJlZW4gb2YgYSBwaWVjZSBvZiBkZWR1Y3Rpb24gb24gdGhlIGVudGlyZSBqb3VybmV5Lg==',
            'choices' => [
                ['text' => 'SGVhZCBiYWNrIGZvciBFc3RlcidzIHN1cHBlcg==', 'next' => '7_evening'],
            ],
        ],

        '7_evening' => [
            'prose'   => 'RXN0ZXIgZmVlZHMgYWxsIGZvdXIgb2YgeW91IHByb3Blcmx5IHRoYXQgZXZlbmluZyDigJQgbW91bnRhaW4gc291cCB0aGljayBlbm91Z2ggdG8gc3RhbmQgYSBzcG9vbiBpbiwgZ2luZ2VyIHRlYSwgYnJlYWQgc3RpbGwgd2FybSwgYSBtZWFsIHRoYXQgZ29lcyBvbiBsb25nIHBhc3QgdGhlIHBvaW50IHdoZXJlIGFueW9uZSdzIGFjdHVhbGx5IHN0aWxsIGh1bmdyeSwgc2ltcGx5IGJlY2F1c2Ugbm9ib2R5IHdhbnRzIHRvIGJlIHRoZSBvbmUgdG8gZW5kIGl0LgoKUGV0cmEgc2l0cyB3aXRoIHRoZSBsZXR0ZXJzIHVub3BlbmVkIGJlc2lkZSBoZXIgcGxhdGUsIG5vdCBpZ25vcmluZyB0aGVtLCBleGFjdGx5IOKAlCBtb3JlIGxpa2Ugc29tZW9uZSBzaXR0aW5nIG5lYXIgc29tZXRoaW5nIGltcG9ydGFudCB0aGF0IGlzbid0IHF1aXRlIHJlYWR5IHRvIGJlIGRlYWx0IHdpdGggeWV0LCBhbmQgZG9lc24ndCBuZWVkIHRvIGJlIHRvbmlnaHQuCgpKYW1lcyBoYXMgY2xhaW1lZCB0aGUgd2FybWVzdCBjb3JuZXIgb2YgdGhlIGhlYXJ0aC4gRnJlZCBpcyBzdGlsbCBmYWludGx5IGx1bWlub3VzIHdpdGggdGhlIHNhdGlzZmFjdGlvbiBvZiBoaXMgb3duIGNsZXZlcm5lc3MuIEVzdGVyIHdhdGNoZXMgYWxsIG9mIHlvdSB3aXRoIHRoZSBwYXJ0aWN1bGFyIGNvbnRlbnRtZW50IG9mIHNvbWVvbmUgd2hvIGhhcyBmaW5hbGx5LCBhZnRlciBzaXh0eSB5ZWFycywgZ290dGVuIHRvIHNlZSBob3cgYSB2ZXJ5IGxvbmcgc3RvcnkgdHVybnMgb3V0LgoKIllvdSBjb3VsZCBzdGF5IGEgZmV3IG1vcmUgZGF5cywiIHNoZSBvZmZlcnMsIHdoZW4gdGhlIG1lYWwncyBmaW5hbGx5LCByZWx1Y3RhbnRseSBkb25lLiAiT3IgdGhlcmUncyBhIGxvbmcgcm9hZCBzdGlsbCBhaGVhZCBvZiB5b3UgYm90aCwgaWYgeW91J2QgcmF0aGVyIGtlZXAgbW92aW5nLiI=',
            'choices' => [
                ['text' => 'U3RheSBhIGZldyBkYXlzIHdpdGggRXN0ZXI=', 'next' => '8_end_stay'],
                ['text' => 'S2VlcCBtb3ZpbmcsIHRvZ2V0aGVyIHRoaXMgdGltZQ==', 'next' => '8_end_road'],
            ],
        ],

        '8_end_stay' => [
            'prose'   => 'WW91IHN0YXkuIFRoZXJlJ3Mgbm8gcmVhc29uIG5vdCB0bywgYW5kIGV2ZXJ5IHJlYXNvbiB0byDigJQgRXN0ZXIgaGFzIHNpeHR5IHllYXJzIG9mIHN0b3JpZXMgbGVmdCB1bnRvbGQsIGFuZCB5b3UgZmluZCwgdGhlIGxvbmdlciB5b3Ugc2l0IGluIHRoaXMgZmFybWhvdXNlLCB0aGF0IHlvdSdyZSBpbiBubyBodXJyeSB0byBsZWF2ZSBhIHBsYWNlIGdyYW5kbW90aGVyIGFjdHVhbGx5IGNhbWUgZnJvbSwgcmF0aGVyIHRoYW4gbWVyZWx5IHBhc3NlZCB0aHJvdWdoLgoKUGV0cmEgc3RheXMgdG9vLiBUaGUgbGV0dGVycyBzaXQgb24gdGhlIHdpbmRvd3NpbGwgb2YgdGhlIHJvb20gRXN0ZXIgZ2l2ZXMgaGVyLCBvcGVuZWQgbm93LCByZWFkIG9uY2UgdGhyb3VnaCBzbG93bHkgYW5kIHRoZW4gc2V0IGFzaWRlIHRvIGJlIHJlYWQgYWdhaW4gcHJvcGVybHkgbGF0ZXIsIHdoZW4gc2hlJ3MgcmVhZHkgZm9yIHRoZSB3aG9sZSBvZiBpdCByYXRoZXIgdGhhbiBqdXN0IHRoZSBiZWdpbm5pbmcuCgpGcmVkIHNwZW5kcyB0aGUgZGF5cyBjYXRhbG9ndWluZyB0aGUgbW91bnRhaW4ncyBmbG9yYSB3aXRoIHVucmVzdHJhaW5lZCBqb3ksIG11dHRlcmluZyBjb25zdGFudGx5IGFib3V0IHRoZSBoaWxsIHNwZWNpZXMgYW5kIGl0cyBvcmlnaW5zLiBKYW1lcyBhZG9wdHMgdGhlIGhlYXJ0aCBhcyBhIHBlcm1hbmVudCBhZGRyZXNzLiBFc3RlciB0ZWFjaGVzIHlvdSBib3RoLCBiYWRseSBhbmQgcGF0aWVudGx5LCBob3cgc2hlIG1ha2VzIHRoZSBzb3VwLCBhbmQgZG9lc24ndCBjb3JyZWN0IG11Y2gsIGFuZCBkb2Vzbid0IG5lZWQgdG8uCgpZb3UgbGVhdmUsIGV2ZW50dWFsbHksIHN0ZWFkaWVyIHRoYW4geW91IGFycml2ZWQg4oCUIGNhcnJ5aW5nIG5vdCBqdXN0IGEgc3F1YXJlIG5vdywgYnV0IHRoZSBhY3R1YWwgZ3JvdW5kIGdyYW5kbW90aGVyIGNhbWUgZnJvbSwgd2hpY2ggdHVybnMgb3V0IHRvIG1hdHRlciBtb3JlIHRoYW4geW91IGV4cGVjdGVkIGl0IHRvLg==',
            'ending'  => true,
        ],

        '8_end_road' => [
            'prose'   => 'WW91IGdvIG9uIHRvZ2V0aGVyIOKAlCBwcm9wZXJseSB0b2dldGhlciBub3csIGZvciB0aGUgZmlyc3QgdGltZSBvbiB0aGlzIHdob2xlIHJvYWQsIHRoZSB0d28gb2YgeW91IGFuZCBGcmVkIGFuZCBKYW1lcyBhbGwgbW92aW5nIHRoZSBzYW1lIGRpcmVjdGlvbiB3aXRoIHRoZSBzYW1lIHB1cnBvc2UgaW5zdGVhZCBvZiB0d28gc2VwYXJhdGUgam91cm5leXMgdGhhdCBrZXB0LCBjb2luY2lkZW50YWxseSwgYXJyaXZpbmcgYXQgdGhlIHNhbWUgcGxhY2VzLgoKUGV0cmEgY2FycmllcyB0aGUgbGV0dGVycyBjYXJlZnVsbHksIHVub3BlbmVkIHN0aWxsLCB0dWNrZWQgc29tZXdoZXJlIGNsb3NlLiBTaGUnbGwgcmVhZCB0aGVtIHdoZW4gc2hlJ3MgcmVhZHksIHNoZSBzYXlzLCBhbmQgeW91IGJlbGlldmUgaGVyLCBhbmQgZG9uJ3QgcHVzaC4KCkVzdGVyIHdhdmVzIHlvdSBib3RoIG9mZiBmcm9tIHRoZSBmYXJtaG91c2UgZG9vciwgc21hbGwgYW5kIHNoYXJwIGFuZCBlbnRpcmVseSBzYXRpc2ZpZWQsIHRoZSB3YXkgc29tZW9uZSBsb29rcyB3aGVuIGEgdmVyeSBsb25nIHdhaXQgaGFzIGZpbmFsbHksIHByb3Blcmx5LCBwYWlkIG9mZi4KCiJUaGUgbGFzdCB0aHJlZSBhcmUgdG9nZXRoZXIsIiBQZXRyYSBzYXlzLCBvbmNlIHRoZSBmYXJtaG91c2UgaXMgb3V0IG9mIHNpZ2h0IGJlaGluZCB5b3UsIGVjaG9pbmcgdGhlIG5vdGUgZnJvbSB0aGUgbW9uYXN0ZXJ5IGNyeXB0LCBmcm9tIHRoZSBzZWFtb3VudCwgZnJvbSB3aGVyZXZlciBlbHNlIGl0J3MgdHVybmVkIHVwIG9uIHRoaXMgd2hvbGUgcm9hZC4gIldoZXJldmVyIHRoYXQgZW5kcyB1cCBiZWluZy4gV2Ugc2hvdWxkIHByb2JhYmx5IGZpbmQgb3V0LiIKCiJUb2dldGhlciwiIHlvdSBhZ3JlZSwgYW5kIGZvciB0aGUgZmlyc3QgdGltZSBzaW5jZSB0aGUgYXR0aWMsIHRoZSB3b3JkIG1lYW5zIGV4YWN0bHkgd2hhdCBpdCBzYXlzLg==',
            'ending'  => true,
        ],

    ],
];
