<?php
return [
    'id'    => 'q18',
    'title' => 'The Monastery Library',
    'color' => '#8A2A2A',

    'pages' => [
        '1_start' => [
            'prose'   => 'VGhlIG1vbmFzdGVyeSBkb2Vzbid0IGFubm91bmNlIGl0c2VsZiBzbyBtdWNoIGFzIHNsb3dseSBzdG9wIGJlaW5nIGRlbmlhYmxlIOKAlCBhIHNoYXBlIG9uIHRoZSBtb3VudGFpbnNpZGUgdGhhdCBtaWdodCBiZSByb2NrIHVudGlsLCBhYnJ1cHRseSwgaXQgaXNuJ3QsIHdhbGxzIHRoZSBzYW1lIGdyZXkgYXMgZXZlcnl0aGluZyBhcm91bmQgdGhlbSwgYSBiZWxsIHRvd2VyIHJpc2luZyBpbnRvIGNsb3VkIHRoYXQgbmV2ZXIgcXVpdGUgbGV0cyB5b3Ugc2VlIHRoZSB0b3Agb2YgaXQuCgpUaGUgZmxvd2VyIHRpbiB0cmF2ZWxzIHdyYXBwZWQgaW4gb2lsY2xvdGggbm93LCB0dWNrZWQgYXMgY2FyZWZ1bGx5IGFzIGFueXRoaW5nIHlvdSd2ZSBjYXJyaWVkIG9uIHRoaXMgd2hvbGUgcm9hZCDigJQgTGFycydzIGdpZnQsIG9yIGdyYW5kbW90aGVyJ3MsIGRlcGVuZGluZyBob3cgZmFyIGJhY2sgeW91IHdhbnQgdG8gdHJhY2UgdGhlIG93bmVyc2hpcC4gRnJlZCBoYXMgYmVlbiB1bnVzdWFsbHkgY29udGVtcGxhdGl2ZSBzaW5jZSBMb2ZvdGVuLCBzdGlsbCBwcm9jZXNzaW5nLCB5b3Ugc3VzcGVjdCwgdGhlIHNjYWxlIG9mIHdoYXQgaGUncyBjYXJyeWluZyBhbiBvcGluaW9uIGFib3V0LgoKVHdvIHBhdGhzIGNsaW1iIHRvd2FyZCB0aGUgd2FsbHMuIEEgc3RvbmUtbWFya2VkIHBpbGdyaW0gcm9hZCwgbWFpbnRhaW5lZCwgY2Fpcm5zIGF0IHJlZ3VsYXIgaW50ZXJ2YWxzLCBjbGVhcmx5IHdhbGtlZCBieSBjZW50dXJpZXMgb2YgZmVldCB0aGF0IGtuZXcgZXhhY3RseSB3aGVyZSB0aGV5IHdlcmUgZ29pbmcuIE9yIGEgbG9uZ2VyIHJvdXRlIHRocm91Z2ggaGlnaCBhbHBpbmUgbWVhZG93cyDigJQgc3BlY3RhY3VsYXIsIEZyZWQgaW5zaXN0cywgYWxyZWFkeSBoYWxmd2F5IGNvbnZpbmNlZCBiZWZvcmUgeW91J3ZlIGNob3Nlbiwgb24gdGhlIHN0cmVuZ3RoIG9mIGEgc2luZ2xlIGZsb3dlciBoZSdzIHNwb3R0ZWQgZnJvbSBhbiBpbXBvc3NpYmxlIGRpc3RhbmNlLg==',
            'choices' => [
                ['text' => 'VGFrZSB0aGUgcGlsZ3JpbSByb2Fk', 'next' => '2_pilgrim'],
                ['text' => 'VGFrZSB0aGUgbWVhZG93IHBhdGg=', 'next' => '2_monk'],
            ],
        ],

        '2_pilgrim' => [
            'prose'   => 'VGhlIHBpbGdyaW0gcm9hZCBpcyBleGFjdGx5IHdoYXQgY2VudHVyaWVzIG9mIG1haW50ZW5hbmNlIHByb2R1Y2VzIOKAlCB3b3JuIHNtb290aCBpbiBwbGFjZXMsIG1hcmtlZCBjbGVhcmx5IGVub3VnaCB0aGF0IGxvc2luZyB5b3VyIHdheSB3b3VsZCB0YWtlIHJlYWwgZWZmb3J0LCBjYWlybnMgYXBwZWFyaW5nIGF0IGp1c3QgdGhlIG1vbWVudCB5b3UnZCBzdGFydCB0byB3b25kZXIgaWYgeW91IHdlcmUgc3RpbGwgb24gaXQuIEl0IGNsaW1icyBzdGVhZGlseSwgdW5odXJyaWVkLCB0aGUga2luZCBvZiByb2FkIGJ1aWx0IGJ5IHBlb3BsZSB3aG8gdW5kZXJzdG9vZCB0aGF0IG1vc3Qgam91cm5leXMgd29ydGggbWFraW5nIHNob3VsZG4ndCBiZSBydXNoZWQuCgpBdCB0aGUgZ2F0ZSwgYSBtb25rIGluIGdyZXkgcm9iZXMg4oCUIHRoZSBndWVzdG1hc3RlciwgaGUgaW50cm9kdWNlcyBoaW1zZWxmIGFzLCBCcm90aGVyIEFuc2VsbSDigJQgZ3JlZXRzIHlvdSB3aXRoIHRoZSBwcmFjdGljZWQgd2FybXRoIG9mIGEgbWFuIHdobyBoYXMgd2VsY29tZWQgc2V2ZXJhbCB0aG91c2FuZCBzdHJhbmdlcnMgYW5kIG5ldmVyIG9uY2UgbWFkZSBpdCBmZWVsIHJvdXRpbmUuCgpZb3Ugc2hvdyBoaW0gdGhlIGZsb3dlciB0aW4sIG1vcmUgb3V0IG9mIGhhYml0IHRoYW4gZXhwZWN0YXRpb24gYnkgbm93LiBIZSBvcGVucyBpdCBjYXJlZnVsbHksIGFuZCBzb21ldGhpbmcgY2hhbmdlcyBpbiBoaXMgZmFjZSBhbG1vc3QgaW1tZWRpYXRlbHkg4oCUIHJlY29nbml0aW9uLCBxdWljayBhbmQgY2VydGFpbi4KCiJUaGVzZSBtYXRjaCBvdXIgb3duIHJlY29yZHMsIiBoZSBzYXlzLCB0dXJuaW5nIGEgcHJlc3NlZCBzcGVjaW1lbiB0byB0aGUgbGlnaHQuICJTZXZlcmFsIG9mIHRoZW0gZXhhY3RseS4iIEhlIGxvb2tzIHVwIGF0IHlvdSBwcm9wZXJseSBmb3IgdGhlIGZpcnN0IHRpbWUuICJBIHdvbWFuIGxlZnQgY29waWVzIG9mIGhlciBmaWVsZCBub3RlcyBpbiBvdXIgbGlicmFyeSwgYSBsb25nIHRpbWUgYWdvLiBDb21lLiBZb3UnbGwgd2FudCB0byBzZWUgdGhpcyB5b3Vyc2VsZi4i',
            'choices' => [
                ['text' => 'Rm9sbG93IGhpbSBpbnNpZGU=', 'next' => '3_library'],
            ],
        ],

        '2_monk' => [
            'prose'   => 'VGhlIG1lYWRvdyBwYXRoIGNsaW1icyB0aHJvdWdoIGhpZ2ggYWxwaW5lIGdyYXNzbGFuZCwgc3BlY3RhY3VsYXIgaW4gZXhhY3RseSB0aGUgd2F5IEZyZWQgcHJvbWlzZWQg4oCUIHdpbGRmbG93ZXJzIHNjYXR0ZXJlZCB0aGljayBlbm91Z2ggdG8gc2VlbSBkZWxpYmVyYXRlLCB0aGUgbW9uYXN0ZXJ5J3MgYmVsbCB0b3dlciBhcHBlYXJpbmcgYW5kIHZhbmlzaGluZyBiZWhpbmQgcmlkZ2VsaW5lcyBhcyB0aGUgcGF0aCBzd2l0Y2hlcyBiYWNrIG9uIGl0c2VsZi4KCkZyZWQgc3BvdHMgYSBmbG93ZXIgcGFydHdheSB1cCBhbmQgZ29lcyB1bmNoYXJhY3RlcmlzdGljYWxseSBxdWlldCwgY2hlY2tpbmcgaXQgYWdhaW5zdCB0aGUgdGluIHR3aWNlIGJlZm9yZSBoZSBzYXlzIGFueXRoaW5nLgoKIlRoaXMgaXMgaW4gaGVyZSwiIGhlIHNheXMgZmluYWxseSwgdGFwcGluZyB0aGUgdGluLiAiU2FtZSBzcGVjaWVzLiBTYW1lIGFsdGl0dWRlLCBuZWFyIGVub3VnaC4iIEhlIGxvb2tzIGFyb3VuZCBhdCB0aGUgd2hvbGUgc3BlY3RhY3VsYXIgc3dlZXAgb2YgbWVhZG93LiAiU2hlIHdhbGtlZCB0aGlzIGV4YWN0IHBhdGguIgoKQXQgdGhlIGdhdGUsIEJyb3RoZXIgQW5zZWxtIOKAlCBncmV5LXJvYmVkLCB1bmh1cnJpZWQsIHRoZSBtb25hc3RlcnkncyBndWVzdG1hc3RlciDigJQgZ3JlZXRzIHlvdSB3YXJtbHksIGFuZCB3aGVuIHlvdSBzaG93IGhpbSB0aGUgdGluLCBoaXMgcmVhY3Rpb24gaXMgaW1tZWRpYXRlLgoKIlNoZSBsZWZ0IGZpZWxkIG5vdGVzIGluIG91ciBsaWJyYXJ5LCIgaGUgc2F5cywgbm90IGV2ZW4gbmVlZGluZyB0byBleGFtaW5lIGl0IGZ1bGx5IGJlZm9yZSBoZSByZWNvZ25pc2VzIHRoZSBoYW5kLiAiQSBsb25nIHRpbWUgYWdvLiBDb21lLiBZb3UnbGwgd2FudCB0byBzZWUgdGhpcyB5b3Vyc2VsZi4i',
            'choices' => [
                ['text' => 'Rm9sbG93IGhpbSBpbnNpZGU=', 'next' => '3_library'],
            ],
        ],

        '3_library' => [
            'prose'   => 'VGhlIGxpYnJhcnkgaXMgbm90aGluZyBsaWtlIHlvdSBleHBlY3RlZCBmcm9tIHRoZSBtb25hc3RlcnkncyBwbGFpbiBncmV5IHdhbGxzIOKAlCB2YXN0LCB2YXVsdGVkLCBsaW5lZCBmbG9vciB0byBjZWlsaW5nIHdpdGggdm9sdW1lcyB0aGF0IHNtZWxsIG9mIG9sZCBsZWF0aGVyIGFuZCBjYW5kbGUgc21va2UgYW5kIHNvbWV0aGluZyBlbHNlLCBzb21ldGhpbmcgdGhhdCBtaWdodCBqdXN0IGJlIHNpeCBjZW50dXJpZXMgb2YgY2FyZWZ1bCBhdHRlbnRpb24uCgoiV2Uga2VlcCB2aXNpdG9yIHJlY29yZHMsIiBCcm90aGVyIEFuc2VsbSBleHBsYWlucywgbGVhZGluZyB5b3UgYmV0d2VlbiBzaGVsdmVzIHdpdGggdGhlIHVuaHVycmllZCBjb25maWRlbmNlIG9mIGEgbWFuIHdobyBoYXMgd2Fsa2VkIHRoaXMgZXhhY3Qgcm91dGUgdGVuIHRob3VzYW5kIHRpbWVzLiAiU2l4IGh1bmRyZWQgeWVhcnMgb2YgdGhlbS4gRXZlcnlvbmUgd2hvJ3Mgc3RheWVkIGhlcmUsIGV2ZXJ5b25lIHdobydzIGxlZnQgc29tZXRoaW5nIGJlaGluZC4iIEhlIHB1bGxzIGEgbGVkZ2VyIGZyb20gYSBzaGVsZiB0aGF0IHNlZW1zLCBzb21laG93LCB0byBrbm93IGV4YWN0bHkgd2hlcmUgaXQgYmVsb25ncy4KCllvdXIgZ3JhbmRtb3RoZXIncyBuYW1lIGFwcGVhcnMgdGhyZWUgdGltZXMsIHRoaXJ0eSB5ZWFycyBhcGFydCBiZXR3ZWVuIHRoZSBmaXJzdCBhbmQgdGhlIGxhc3QuCgoiVGhyZWUgdmlzaXRzLCIgQW5zZWxtIHNheXMuICJUaGUgZmluYWwgb25lLCBzaGUgY2FtZSBzcGVjaWZpY2FsbHkgdG8gbGVhdmUgc29tZXRoaW5nIOKAlCBhIGNoZXN0LCBpbiB0aGUgY3J5cHQsIGFuZCBoZXIgZmllbGQgbm90ZXMgd2l0aCB1cywgZm9yIGtlZXBpbmcuIiBIZSBjbG9zZXMgdGhlIGxlZGdlciBnZW50bHkuICJTaGUgc2FpZCB0aGUgY3J5cHQgd291bGQga2VlcCB0aGUgY2hlc3Qgc2FmZXIgdGhhbiBhbnkgZG9vciB3aXRoIGEgbG9jayBldmVyIGNvdWxkLiI=',
            'choices' => [
                ['text' => 'R28gZG93biB0byB0aGUgY3J5cHQ=', 'next' => '4_crypt'],
            ],
        ],

        '4_crypt' => [
            'prose'   => 'VGhlIGNyeXB0IGlzIGNvbGQgaW4gYSB3YXkgdGhhdCBoYXMgbm90aGluZyB0byBkbyB3aXRoIHRlbXBlcmF0dXJlIOKAlCBvbGQgc3RvbmUsIG9sZCBzaWxlbmNlLCBhIHJvdyBvZiBuaWNoZXMgY3V0IGludG8gdGhlIHdhbGxzIHdoZXJlIGNhbmRsZXMgaGF2ZSBidXJuZWQgZm9yIGxvbmdlciB0aGFuIGFueW9uZSBjdXJyZW50bHkgYWxpdmUgaGFzIGJlZW4ga2VlcGluZyB0cmFjayBvZi4KCkFuc2VsbSBsZWFkcyB5b3UgdG8gb25lIG5pY2hlIG5lYXIgdGhlIGJhY2ssIHVucmVtYXJrYWJsZSBleGNlcHQgZm9yIHdoYXQgaXQgaG9sZHM6IGEgc21hbGwgY2hlc3QsIGFuZCBiZXNpZGUgaXQsIGNhcnZlZCBkaXJlY3RseSBpbnRvIHRoZSBzdG9uZSwgYSBydW5lIOKAlCB0aGUgc2V2ZW50aCB5b3UndmUgZm91bmQgb24gdGhpcyB3aG9sZSByb2FkLCBkZWVwIGFuZCBkZWxpYmVyYXRlLCBjYXRjaGluZyB0aGUgY2FuZGxlbGlnaHQgYXQgYW4gYW5nbGUgdGhhdCBtYWtlcyBpdCBsb29rLCBmb3IgYSBtb21lbnQsIGxpa2UgaXQncyBzdGlsbCBiZWluZyBjYXJ2ZWQuCgoiU2hlIGFza2VkIHRvIGJlIGxlZnQgYWxvbmUgd2l0aCB0aGlzIG5pY2hlLCBib3RoIHRpbWVzIHNoZSBjYW1lIGhlcmUgYXQgdGhlIGVuZCwiIEFuc2VsbSBzYXlzIHF1aWV0bHkuICJJIGRpZG4ndCBhc2sgd2hhdCBzaGUgZGlkIGluIHRoYXQgdGltZS4gU29tZSB0aGluZ3MgYXJlbid0IG1pbmUgdG8gYXNrIGFib3V0LiIKClRoZSBzaWxlbmNlIG9mIHRoZSBwbGFjZSBwcmVzc2VzIGluIGdlbnRseSwgbm90IHVua2luZGx5IOKAlCB0aGUgc3BlY2lmaWMgcXVpZXQgb2Ygc29tZXdoZXJlIGJ1aWx0IGZvciBleGFjdGx5IHRoaXMsIGZvciBwZW9wbGUgc3RhbmRpbmcgc3RpbGwgaW4gZnJvbnQgb2Ygc29tZXRoaW5nIHRoYXQgbWF0dGVycy4=',
            'choices' => [
                ['text' => 'T3BlbiB0aGUgY2hlc3Q=', 'next' => '5_note'],
            ],
            'terminal' => true,
        ],

        '5_note' => [
            'prose'   => 'VGhlIGxhdGNoIOKAlCB0aGUgc2FtZSBpbnRlcmxvY2tlZCBtZWNoYW5pc20sIGVhc2llciBub3cgdGhhbiBpdCdzIGV2ZXIgYmVlbiDigJQgcmVzb2x2ZXMgYWxtb3N0IGFzIHNvb24gYXMgeW91ciBmaW5nZXJzIGZpbmQgaXQsIGFuZCB5b3UgbGlmdCB0aGUgbGlkIHRvIGZpbmQgU3F1YXJlICMxOCBmb2xkZWQgb24gdG9wIG9mIGEgc2luZ2xlIGZvbGRlZCBub3RlLgoKVGhlIHNxdWFyZTogYSBiZWxsIHRvd2VyLCBncmV5IHRocmVhZCBvbiBwYWxlIGxpbmVuLCBtaXN0IHdvcmtlZCBpbiB3aXRoIHN1Y2ggcmVzdHJhaW50IHlvdSBhbG1vc3QgbWlzcyBpdCDigJQganVzdCBhIHNvZnRlbmluZyBhdCB0aGUgZWRnZXMsIGEgYmx1cnJpbmcgd2hlcmUgdGhlIHRvd2VyJ3Mgb3V0bGluZSBzaG91bGQgYmUgc2hhcnAgYW5kIGlzbid0LgoKVGhlIG5vdGUsIGluIGdyYW5kbW90aGVyJ3MgaGFuZDoKCiJUaGUgbGFzdCB0aHJlZSBhcmUgdG9nZXRoZXIuIFRoZXkgd2FpdCBhdCB0aGUgYmVnaW5uaW5nLiBZb3Ugd2lsbCBrbm93IHdoZW4geW91IGFyZSByZWFkeS4iCgpZb3UgcmVhZCBpdCB0d2ljZS4gSXQgZG9lc24ndCBleHBsYWluIGl0c2VsZiwgYW5kIHNvbWV0aGluZyBhYm91dCB0aGUgaGFuZHdyaXRpbmcg4oCUIHN0ZWFkeSwgdW5odXJyaWVkLCBlbnRpcmVseSBjZXJ0YWluIOKAlCBzdWdnZXN0cyBpdCB3YXMgbmV2ZXIgbWVhbnQgdG8uCgoiVGhlIG90aGVyIG9uZSByZWFkIHRoYXQgc2FtZSBub3RlIHR3byB3ZWVrcyBhZ28sIiBBbnNlbG0gc2F5cyBnZW50bHksIHdhdGNoaW5nIHlvdSBmb2xkIGl0IGF3YXkuICJTaGUgc2F0IHdpdGggaXQgYSBsb25nIHdoaWxlIHRvby4gTG9uZ2VyIHRoYW4gbW9zdCBwZW9wbGUgc2l0IHdpdGggYW55dGhpbmcsIHRoZXNlIGRheXMuIg==',
            'choices' => [
                ['text' => 'R28gYmFjayB0byB0aGUgbGlicmFyeQ==', 'next' => '6_fieldnotes'],
            ],
        ],

        '6_fieldnotes' => [
            'prose'   => 'QmFjayBpbiB0aGUgbGlicmFyeSwgQW5zZWxtIGxlYXZlcyB5b3UgYW5kIEZyZWQgdG8gdGhlIGZpZWxkIG5vdGVzIHdpdGhvdXQgY2VyZW1vbnksIGFuZCBGcmVkIGRpc2FwcGVhcnMgaW50byB0aGVtIHNvIGNvbXBsZXRlbHkgdGhhdCB0d28gaG91cnMgcGFzcyBiZWZvcmUgeW91IHRoaW5rIHRvIGNoZWNrIG9uIGhpbS4KCldoZW4gaGUgZmluYWxseSBzdXJmYWNlcywgaGUgaGFzIHRoZSBwYXJ0aWN1bGFyIGxvb2sgb2YgYSBtYW4gd2hvIGhhcyBqdXN0IG1ldCBzb21lb25lIGhlIGFkbWlyZXMgZmFyIHRvbyBtdWNoIHRvIGJlIGVudGlyZWx5IGNvbWZvcnRhYmxlIGFib3V0IGl0LgoKIlNoZSBzdWJtaXR0ZWQgdGhyZWUgbmV3IHNwZWNpZXMgZm9yIGZvcm1hbCBjbGFzc2lmaWNhdGlvbiwiIGhlIHNheXMsIHNldHRpbmcgdGhlIG5vdGVzIGRvd24gd2l0aCB1bnVzdWFsIGNhcmUuICJGcm9tIHRoaXMgcmFuZ2UgYWxvbmUuIEFsbCB0aHJlZSBhY2NlcHRlZC4iIEhlIHBhdXNlcywgYW5kIHNvbWV0aGluZyBpbiBoaXMgdm9pY2UgY2hhbmdlcywgcXVpZXRlciB0aGFuIHlvdSd2ZSBoZWFyZCBoaW0uICJTaGUncyBpbiB0aGUgbGl0ZXJhdHVyZS4gUHJvcGVybHkgaW4gaXQuIFVuZGVyIGhlciBtYWlkZW4gbmFtZSDigJQgSSBjaGVja2VkIHR3aWNlLCBJIHdhbnRlZCB0byBiZSBzdXJlIGl0IHdhcyByZWFsbHkgaGVyLiIKCkhlIHNpdHMgZG93biwgd2hpY2ggaGUgYWxtb3N0IG5ldmVyIGRvZXMgd2hlbiB0aGVyZSBhcmUgc3RpbGwgcGFnZXMgbGVmdCB1bnJlYWQuCgoiSSBzcGVuZCBteSB3aG9sZSBsaWZlIGNoYXNpbmcgcmFyZSBhbmQgdW5jYXRhbG9ndWVkIHRoaW5ncywiIGhlIHNheXMgZXZlbnR1YWxseS4gIkkgZG9uJ3QgdGhpbmsgSSBldmVyIGNvbnNpZGVyZWQgdGhhdCBzaGUgbWlnaHQgaGF2ZSBzaW1wbHkgZm91bmQgc29tZSBvZiB0aGVtIGZpcnN0LCBkZWNhZGVzIGJlZm9yZSBJIHN0YXJ0ZWQgbG9va2luZywgYW5kIHRoZW4gZ29uZSBxdWlldGx5IGhvbWUgdG8gcmFpc2UgYSBmYW1pbHkgaW5zdGVhZCBvZiBjaGFzaW5nIHRoZSBjcmVkaXQgZm9yIGl0LiI=',
            'choices' => [
                ['text' => 'TGV0IEFuc2VsbSBzaG93IHlvdSBvdXQ=', 'next' => '7_herbs'],
            ],
        ],

        '7_herbs' => [
            'prose'   => 'QmVmb3JlIHlvdSBsZWF2ZSB0aGUgbGlicmFyeSwgQnJvdGhlciBBbnNlbG0gcHJlc3NlcyBhIHNtYWxsIHBhY2tldCBpbnRvIHlvdXIgaGFuZHMg4oCUIGRyaWVkIGhlcmJzLCBjYXJlZnVsbHkgYnVuZGxlZCwgc21lbGxpbmcgb2Ygc29tZXRoaW5nIHNoYXJwIGFuZCBtZWRpY2luYWwuCgoiRm9yIGNvbGQgYW5kIGFsdGl0dWRlLCIgaGUgc2F5cy4gIkJyZXcgdGhlbSBzdHJvbmcuIFlvdSd2ZSBhIGxvbmcgcm9hZCBzdGlsbCBhaGVhZCBvZiB5b3UsIGJ5IHRoZSBsb29rIG9mIHRoYXQgcGFjay4iCgpGcmVkIHRha2VzIGFuIGltbWVkaWF0ZSBhbmQgdGhvcm91Z2ggaW50ZXJlc3QsIGlkZW50aWZ5aW5nIGVhY2ggY29tcG9uZW50IHdpdGggZ3Jvd2luZyBleGNpdGVtZW50IHRoYXQgdGlwcywgaGFsZndheSB0aHJvdWdoLCBpbnRvIHNvbWV0aGluZyBxdWlldGVyLgoKIlRocmVlIG9mIHRoZXNlIGFyZSBpbiB0aGUgdGluLCIgaGUgc2F5cyBzbG93bHksIGNoZWNraW5nIGJhY2sgYW5kIGZvcnRoIGJldHdlZW4gcGFja2V0IGFuZCB0aW4uICJVbmRlciBkaWZmZXJlbnQgY29tbW9uIG5hbWVzIOKAlCBsb2NhbCBuYW1lcywgbm90IHRoZSBvbmVzIHNoZSdkIGhhdmUga25vd24gdGhlbSBieS4gQnV0IHRoZSBzYW1lIHBsYW50cy4gU2hlIHdhcyBjb2xsZWN0aW5nIHRoZXNlIHRvbywgaGVyZSwgYW5kIEFuc2VsbSdzIHRyYWRpdGlvbiBoYXMgYmVlbiBjb2xsZWN0aW5nIHRoZW0gaW5kZXBlbmRlbnRseSBmb3IgY2VudHVyaWVzLiIgSGUgbG9va3MgdXAuICJUd28gcGVvcGxlLCBnYXRoZXJpbmcgdGhlIHNhbWUgaGFuZGZ1bCBvZiBwbGFudHMsIGRlY2FkZXMgYW5kIHRyYWRpdGlvbnMgYXBhcnQsIGZvciBlbnRpcmVseSBkaWZmZXJlbnQgcmVhc29ucywgYW5kIGFycml2aW5nIGF0IHRoZSBzYW1lIHJlc3BlY3QgZm9yIHRoZW0uIgoKQW5zZWxtLCBvdmVyaGVhcmluZywgb25seSBzbWlsZXMsIGFuZCBkb2Vzbid0IHNlZW0gYXQgYWxsIHN1cnByaXNlZC4=',
            'choices' => [
                ['text' => 'R28gdGhyb3VnaCB0byB0aGUgcmVmZWN0b3J5', 'next' => '8_refectory'],
            ],
        ],

        '8_refectory' => [
            'prose'   => 'U3VwcGVyIGlzIHRha2VuIGluIHRoZSByZWZlY3RvcnkgaW4gY29tcGxldGUgc2lsZW5jZSDigJQgdGhlIG1vbmFzdGVyeSdzIGN1c3RvbSwgQW5zZWxtIGV4cGxhaW5zIGJlZm9yZWhhbmQsIGFwb2xvZ2V0aWNhbGx5LCBhcyB0aG91Z2ggc2lsZW5jZSB3ZXJlIGFuIGluY29udmVuaWVuY2UgcmF0aGVyIHRoYW4gdGhlIGVudGlyZSBwb2ludC4gQWZ0ZXIgbW9udGhzIG9mIGEgcm9hZCB0aGF0IGhhcyByYXJlbHkgc3RvcHBlZCB0YWxraW5nLCB0aGUgcXVpZXQgbGFuZHMgb24geW91IGxpa2Ugc29tZXRoaW5nIHBoeXNpY2FsLCBzdHJhbmdlIGFuZCB0aGVuLCBncmFkdWFsbHksIHJlc3RvcmF0aXZlLgoKRnJlZCwgZm9yIG9uY2UsIGhhcyBub3RoaW5nIHRvIGFkZC4gSGUgZWF0cyBpbiBzaWxlbmNlIHdpdGggdGhlIHJlc3Qgb2YgeW91LCBhbmQgaXQgc3VpdHMgaGltIGJldHRlciB0aGFuIHlvdSdkIGhhdmUgZ3Vlc3NlZC4KCkFmdGVyd2FyZCwgaW4gdGhlIGd1ZXN0IHF1YXJ0ZXJzLCB0aGUgbm90ZSBzaXRzIGZvbGRlZCBpbiB5b3VyIHBhY2sgbmV4dCB0byB0aGUgc3F1YXJlLiBUaGUgbGFzdCB0aHJlZSBhcmUgdG9nZXRoZXIuIFRoZXkgd2FpdCBhdCB0aGUgYmVnaW5uaW5nLiBZb3UgZG9uJ3Qga25vdyB5ZXQgd2hhdCBpdCBtZWFucywgb25seSB0aGF0IGl0IG1hdHRlcnMsIGFuZCB0aGF0IHdoYXRldmVyJ3MgY29taW5nIHdpbGwgcmVxdWlyZSB5b3UgdG8gYWN0dWFsbHkgYXJyaXZlIHNvbWV3aGVyZSwgZXZlbnR1YWxseSwgcmF0aGVyIHRoYW4gc2ltcGx5IGtlZXAgbW92aW5nLgoKQW5zZWxtIGZpbmRzIHlvdSBiZWZvcmUgeW91IHNsZWVwLCB1bmh1cnJpZWQgYXMgZXZlci4gIllvdSBjb3VsZCBzdGF5IGFub3RoZXIgZGF5LCIgaGUgb2ZmZXJzLiAiUmVzdCBoZXJlLiBUaGUgbW91bnRhaW4gaXNuJ3QgZ29pbmcgYW55d2hlcmUuIiBPciB0aGUgcm9hZCwgYXMgaXQgYWx3YXlzIGRvZXMsIGlzIHdhaXRpbmcu',
            'choices' => [
                ['text' => 'U3RheSBhbm90aGVyIGRheSBpbiB0aGUgc2lsZW5jZQ==', 'next' => '9_end_stay'],
                ['text' => 'R28gb24gaW4gdGhlIG1vcm5pbmc=', 'next' => '9_end_go'],
            ],
        ],

        '9_end_stay' => [
            'prose'   => 'WW91IHN0YXkuIFRoZXJlJ3Mgbm90aGluZyB1cmdlbnQgZW5vdWdoIHRvIG91dHdlaWdoIG9uZSBtb3JlIGRheSBvZiB0aGlzIHBhcnRpY3VsYXIgcXVpZXQsIGFuZCBBbnNlbG0sIHdpdGhvdXQgbWFraW5nIGEgdGhpbmcgb2YgaXQsIGFycmFuZ2VzIGZvciB5b3UgdG8gc2ltcGx5IGV4aXN0IGluIHRoZSBtb25hc3RlcnkncyByaHl0aG0gZm9yIGEgd2hpbGUg4oCUIHByYXllcnMgYXQgaG91cnMgeW91IGRpZG4ndCBrbm93IGV4aXN0ZWQsIHNpbGVuY2UgYXQgbWVhbHMsIGEgZ2FyZGVuIHRvIHdhbGsgaW4gdGhhdCBGcmVkIHNwZW5kcyB0aGUgZW50aXJlIGRheSBjYXRhbG9ndWluZyB3aXRoIHF1aWV0LCBjb250ZW50ZWQgdGhvcm91Z2huZXNzLgoKWW91IGZpbmQsIGJ5IGV2ZW5pbmcsIHRoYXQgdGhlIHNpbGVuY2UgaGFzIGRvbmUgc29tZXRoaW5nIHRoZSBub2lzZSBvZiB0aGUgcm9hZCBuZXZlciBxdWl0ZSBtYW5hZ2VkIOKAlCBpdCdzIGxldCB5b3UgYWN0dWFsbHkgc2l0IHdpdGggdGhlIG5vdGUgaW5zdGVhZCBvZiBqdXN0IGNhcnJ5aW5nIGl0IGZvcndhcmQsIHVucmVhZCBpbiB5b3VyIG93biBtaW5kLCB0b3dhcmQgd2hhdGV2ZXIncyBuZXh0LgoKVGhlIGxhc3QgdGhyZWUgYXJlIHRvZ2V0aGVyLiBUaGV5IHdhaXQgYXQgdGhlIGJlZ2lubmluZy4KCllvdSBkb24ndCBzb2x2ZSBpdC4gWW91J3JlIG5vdCBtZWFudCB0bywgbm90IHlldC4gQnV0IHlvdSBsZWF2ZSB0aGUgZm9sbG93aW5nIG1vcm5pbmcgc3RlYWRpZXIgdGhhbiB5b3UgYXJyaXZlZCwgY2FycnlpbmcgaXQgdGhlIHdheSB5b3UnZCBjYXJyeSBzb21ldGhpbmcgZnJhZ2lsZSByYXRoZXIgdGhhbiBzb21ldGhpbmcgdXJnZW50LCBhbmQgdGhhdCwgeW91IHN1c3BlY3QsIHdhcyB0aGUgd2hvbGUgcG9pbnQgb2Ygc3RheWluZy4=',
            'ending'  => true,
        ],

        '9_end_go' => [
            'prose'   => 'WW91IGdvIG9uIGluIHRoZSBtb3JuaW5nLCB0aGUgbW91bnRhaW4ncyBzaWxlbmNlIGZvbGxvd2luZyB5b3UgZnVydGhlciBkb3duIHRoZSByb2FkIHRoYW4geW91IGV4cGVjdGVkIGl0IHRvLCBhIGtpbmQgb2YgcXVpZXQgeW91IGZpbmQgeW91cnNlbGYgcmVsdWN0YW50IHRvIGZ1bGx5IHNoYWtlIG9mZi4KCkFuc2VsbSB3YWxrcyB5b3UgdG8gdGhlIGdhdGUgaGltc2VsZi4gIlNpeCBjZW50dXJpZXMgb2YgdmlzaXRvcnMsIiBoZSBzYXlzLCAiYW5kIEkgc3RpbGwgZmluZCBJIHJlbWVtYmVyIHRoZSBvbmVzIHdobyBhY3R1YWxseSBsaXN0ZW5lZCB3aGlsZSB0aGV5IHdlcmUgaGVyZS4gWW91J2xsIGJlIG9uZSBJIHJlbWVtYmVyLiIgSXQgaXNuJ3QgZmxhdHRlcnkuIEhlIHNheXMgaXQgdGhlIHdheSBoZSBzYXlzIGV2ZXJ5dGhpbmcg4oCUIHBsYWlubHksIGFuZCBiZWNhdXNlIGl0J3MgdHJ1ZS4KClRoZSBub3RlIHJpZGVzIGluIHlvdXIgcGFjayBuZXh0IHRvIHRoZSBzcXVhcmUsIHVucmVzb2x2ZWQsIGFuZCB5b3UgZmluZCB5b3UgZG9uJ3QgbWluZCBjYXJyeWluZyBhIHF1ZXN0aW9uIHlvdSBjYW4ndCB5ZXQgYW5zd2VyLiBTb21lIHRoaW5ncywgdGhpcyByb2FkIGhhcyB0YXVnaHQgeW91LCBhcmUgbWVhbnQgdG8gYmUgY2FycmllZCBhIHdoaWxlIGJlZm9yZSB0aGV5J3JlIHVuZGVyc3Rvb2QuCgpCZWhpbmQgeW91LCB0aGUgYmVsbCB0b3dlciBkaXNhcHBlYXJzIGludG8gY2xvdWQgdGhlIHdheSBpdCBhbHdheXMgZG9lcywgcGF0aWVudCwgdW5ib3RoZXJlZCBieSB3aGV0aGVyIGFueW9uZSdzIHdhdGNoaW5nIGl0IGhhcHBlbi4gQWhlYWQsIHRoZSBsYXN0IHRocmVlIHNxdWFyZXMgYXJlIHdhaXRpbmcgc29tZXdoZXJlLCB0b2dldGhlciwgYXQgdGhlIGJlZ2lubmluZyBvZiBldmVyeXRoaW5nIOKAlCBhbmQgZm9yIHRoZSBmaXJzdCB0aW1lIHNpbmNlIHRoZSBhdHRpYywgeW91IGZpbmQgeW91cnNlbGYgdGhpbmtpbmcgcHJvcGVybHkgYWJvdXQgaG9tZS4=',
            'ending'  => true,
        ],

    ],
];
