<?php
// unlock.php — unlocks the user's vault and stores DEK in session
// Suppress any output before JSON
ob_start();
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

session_start();
require_once __DIR__ . '/init.php';
require_once __DIR__ . '/config_helper.php';

// Clear any output that might have been generated by includes
ob_clean();

header('Content-Type: application/json; charset=utf-8');

function b64u_enc(string $s): string {
  return rtrim(strtr(base64_encode($s), '+/', '-_'), '=');
}
function b64u_dec(string $s): string {
  $s = strtr($s, '-_', '+/'); return base64_decode($s . str_repeat('=', (4 - strlen($s) % 4) % 4));
}
function fail(string $msg, int $code = 400) {
  if (ob_get_level() > 0) {
    ob_clean();
  }
  http_response_code($code);
  echo json_encode(['error' => $msg], JSON_UNESCAPED_SLASHES);
  if (ob_get_level() > 0) {
    ob_end_flush();
  }
  exit;
}

try {
  if (empty($_SESSION['is_authenticated'])) {
    fail('Not authorised', 401);
  }
  if (!extension_loaded('sodium')) {
    fail('libsodium extension missing', 500);
  }

  // Ensure user_id is set (fallback to credential_id)
  if (empty($_SESSION['user_id']) && !empty($_SESSION['credential_id'])) {
    $_SESSION['user_id'] = $_SESSION['credential_id'];
  }

  // Accept JSON body or x-www-form-urlencoded (passphrase only)
  $raw = file_get_contents('php://input') ?: '';
  $in  = json_decode($raw, true);
  if (!is_array($in)) {
    // fallback for form posts
    $in = ['passphrase' => $_POST['passphrase'] ?? null];
  }
  $passphrase = isset($in['passphrase']) ? trim((string)$in['passphrase']) : null;
  $prfKeyB64u = isset($in['prfKey']) ? (string)$in['prfKey'] : null;

  $paths = getConfigPaths();                  // uses $_SESSION['user_id']
  $encPath  = $paths['enc'];
  $wrapDir  = $paths['wraps'];
  $passWrap = $paths['pass'];                 // wraps/passphrase.json

  if (!is_file($encPath)) {
    fail('No encrypted config found', 404);
  }

  $dek = null;

  if ($passphrase !== null && $passphrase !== '') {
    // ---- Passphrase path ----
    if (!is_file($passWrap)) {
      error_log("Passphrase wrap not found at: $passWrap");
      error_log("Config paths: " . json_encode($paths));
      error_log("User ID: " . ($_SESSION['user_id'] ?? 'not set'));
      fail('No passphrase wrap found at expected location', 404);
    }

    $wrapContent = file_get_contents($passWrap);
    if ($wrapContent === false) {
      error_log("Failed to read passphrase wrap file: $passWrap");
      fail('Failed to read passphrase wrap file', 500);
    }
    
    $meta = json_decode($wrapContent, true);
    if ($meta === null) {
      error_log("Invalid JSON in passphrase wrap: $wrapContent");
      fail('Invalid passphrase wrap file format (not valid JSON)', 500);
    }
    
    $salt  = base64_decode($meta['salt']  ?? '');
    $nonce = base64_decode($meta['nonce'] ?? '');
    $ct    = base64_decode($meta['ct']    ?? '');
    
    if (!$salt || !$nonce || !$ct) {
      error_log("Missing fields in wrap - salt: " . (empty($salt) ? 'empty' : 'ok') . ", nonce: " . (empty($nonce) ? 'empty' : 'ok') . ", ct: " . (empty($ct) ? 'empty' : 'ok'));
      fail('Invalid passphrase wrap format - missing required fields', 500);
    }

    $kek = sodium_crypto_pwhash(
      32, $passphrase, $salt,
      SODIUM_CRYPTO_PWHASH_OPSLIMIT_MODERATE,
      SODIUM_CRYPTO_PWHASH_MEMLIMIT_MODERATE,
      SODIUM_CRYPTO_PWHASH_ALG_DEFAULT
    );
    $dek = sodium_crypto_aead_xchacha20poly1305_ietf_decrypt($ct, '', $nonce, $kek);
    if ($dek === false) fail('Wrong passphrase or corrupted wrap', 400);

  } elseif ($prfKeyB64u) {
    // ---- PRF path (optional; enable once you add wraps/cred_<id>.json) ----
    $userIdSafe = preg_replace('/[^A-Za-z0-9_\-]/', '_', $_SESSION['user_id'] ?? 'default');
    $credWrapPath = $wrapDir . "/cred_{$userIdSafe}.json";
    if (!is_file($credWrapPath)) fail('No PRF wrap for this passkey', 404);

    $meta = json_decode(file_get_contents($credWrapPath), true) ?: [];
    $nonce = base64_decode($meta['nonce'] ?? '');
    $ct    = base64_decode($meta['ct']    ?? '');
    if (!$nonce || !$ct) fail('Invalid PRF wrap format', 500);

    $kek = b64u_dec($prfKeyB64u);
    if (strlen($kek) < 32) fail('PRF key too short', 400);

    $dek = sodium_crypto_aead_xchacha20poly1305_ietf_decrypt($ct, '', $nonce, $kek);
    if ($dek === false) fail('PRF unwrap failed', 400);

  } else {
    // No passphrase or PRF key provided - check what's available
    $userIdSafe = preg_replace('/[^A-Za-z0-9_\-]/', '_', $_SESSION['user_id'] ?? $_SESSION['credential_id'] ?? 'default');
    $credWrapPath = $wrapDir . "/cred_{$userIdSafe}.json";
    $hasPrfWrap = is_file($credWrapPath);
    
    if ($hasPrfWrap) {
      // PRF wrap exists but no PRF key provided - this means PRF isn't available from the passkey
      // Fall back to passphrase if available
      if (is_file($passWrap)) {
        fail('PRF not available from this passkey. Passphrase required', 400);
      } else {
        fail('PRF not available from this passkey and no passphrase wrap found', 400);
      }
    } else {
      // No PRF wrap - use passphrase if available
      if (is_file($passWrap)) {
        fail('Passphrase required', 400);
      }
      fail('No wrap available; create config first', 404);
    }
  }

  // Success — keep DEK only in session (base64url)
  $_SESSION['DEK'] = b64u_enc($dek);

  // Clear buffer and output JSON
  if (ob_get_level() > 0) {
    ob_clean();
  }
  echo json_encode(['ok' => true], JSON_UNESCAPED_SLASHES);
  if (ob_get_level() > 0) {
    ob_end_flush();
  }
  exit;
} catch (Throwable $e) {
  // Log the full error for debugging
  $errorMsg = $e->getMessage();
  $errorFile = $e->getFile();
  $errorLine = $e->getLine();
  error_log("Unlock error: $errorMsg in $errorFile:$errorLine");
  error_log("Stack trace: " . $e->getTraceAsString());
  error_log("Session user_id: " . ($_SESSION['user_id'] ?? 'not set'));
  error_log("Session credential_id: " . ($_SESSION['credential_id'] ?? 'not set'));
  
  // Clean output and send error
  if (ob_get_level() > 0) {
    ob_clean();
  }
  http_response_code(500);
  echo json_encode([
    'error' => 'Server error: ' . $errorMsg,
    'details' => 'Check server logs for more information'
  ], JSON_UNESCAPED_SLASHES);
  if (ob_get_level() > 0) {
    ob_end_flush();
  }
  exit;
}

