<?php
// Default jokes for the 'joke' activity type.
// IDs are permanent — never reuse a deleted ID.
return [
    ['id' =>  1, 'setup' => "Why don't scientists trust atoms?",                   'punchline' => "Because they make up everything."],
    ['id' =>  2, 'setup' => "I told my doctor I broke my arm in two places.",       'punchline' => "He told me to stop going to those places."],
    ['id' =>  3, 'setup' => "Why did the scarecrow win an award?",                  'punchline' => "He was outstanding in his field."],
    ['id' =>  4, 'setup' => "What do you call cheese that isn't yours?",            'punchline' => "Nacho cheese."],
    ['id' =>  5, 'setup' => "Why can't a bicycle stand on its own?",                'punchline' => "Because it's two-tired."],
    ['id' =>  6, 'setup' => "What do you call a factory that makes okay products?", 'punchline' => "A satisfactory."],
    ['id' =>  7, 'setup' => "I'm reading a book about anti-gravity.",               'punchline' => "It's impossible to put down."],
    ['id' =>  8, 'setup' => "Did you hear about the claustrophobic astronaut?",     'punchline' => "He just needed a little space."],
    ['id' =>  9, 'setup' => "Why do cows wear bells?",                              'punchline' => "Because their horns don't work."],
    ['id' => 10, 'setup' => "What do you call an alligator in a vest?",             'punchline' => "An investigator."],
    ['id' => 11, 'setup' => "How do you organise a space party?",                   'punchline' => "You planet."],
    ['id' => 12, 'setup' => "What did the ocean say to the beach?",                 'punchline' => "Nothing. It just waved."],
    ['id' => 13, 'setup' => "Why couldn't the leopard play hide and seek?",         'punchline' => "Because he was always spotted."],
    ['id' => 14, 'setup' => "What's a computer's favourite snack?",                 'punchline' => "Microchips."],
    ['id' => 15, 'setup' => "Why do we tell actors to 'break a leg'?",              'punchline' => "Because every play has a cast."],
    ['id' => 16, 'setup' => "What do you call a parade of rabbits hopping backwards?", 'punchline' => "A receding hare-line."],
    ['id' => 17, 'setup' => "I asked my dog what two minus two is.",                'punchline' => "He said nothing."],
    ['id' => 18, 'setup' => "What did one wall say to the other wall?",             'punchline' => "I'll meet you at the corner."],
    ['id' => 19, 'setup' => "Why did the math book look so sad?",                   'punchline' => "It had too many problems."],
    ['id' => 20, 'setup' => "I used to hate facial hair.",                          'punchline' => "Then it grew on me."],
    ['id' => 21, 'setup' => "Time flies like an arrow.",                            'punchline' => "Fruit flies like a banana."],
    ['id' => 22, 'setup' => "What do you call a sleeping dinosaur?",               'punchline' => "A dino-snore."],
    ['id' => 23, 'setup' => "I tried to come up with a joke about infinity.",       'punchline' => "But I couldn't find an ending."],
    ['id' => 24, 'setup' => "Why don't eggs tell jokes?",                          'punchline' => "They'd crack each other up."],
    ['id' => 25, 'setup' => "What do you call a fish without eyes?",               'punchline' => "A fsh."],
    ['id' => 26, 'setup' => "I only know 25 letters of the alphabet.",             'punchline' => "I don't know y."],
    ['id' => 27, 'setup' => "What's brown and sticky?",                            'punchline' => "A stick."],
    ['id' => 28, 'setup' => "Why did the golfer bring an extra pair of pants?",    'punchline' => "In case he got a hole in one."],
    ['id' => 29, 'setup' => "I have a joke about paper.",                          'punchline' => "It's tearable."],
    ['id' => 30, 'setup' => "What do you call a bear with no teeth?",              'punchline' => "A gummy bear."],
];
